### ISSUE TITLE
Forbidden error when using ceph-demo and accessing radosgw through API

### ISSUE THREAD

**Issue by ink1** [ceph/ceph-docker#106]
Once ceph-demo is started, radosgw responds
```
curl localhost
<?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>anonymous</ID><DisplayName></DisplayName></Owner><Buckets></Buckets></ListAllMyBucketsResult>
```
In order to access radosgw using API I need to create a user. Following
http://ceph.com/docs/master/radosgw/config/
we can issue
```
docker exec cd30ab09156 radosgw-admin user create --uid="testuser" --display-name="First User"
```
and then use Python code like this one
```
import boto
import boto.s3.connection
conn = boto.connect_s3(
    aws_access_key_id='3HYE82O7DGS49LKIY4WJ',
    aws_secret_access_key='pARGxDCQ+D3fS+s6EQjeCGWLnEhMWdbncXeB\/hQu',
    host='localhost',    
    is_secure=False,
    calling_format = boto.s3.connection.OrdinaryCallingFormat(),)

    bucket = conn.create_bucket('my-new-bucket')
```

Unfortunately I get
```
    bucket = conn.create_bucket('my-new-bucket')
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 590, in create_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
```

What else am I missing?
As far as I can tell ceph-demo is no different from ceph-rgw in terms rgw default behaviour.

**Comment by leseb** [comment]
I can reproduce your problem, however I'm not good enough with rados gateway to help you debugging this. You will have more luck on the Ceph user mailing list.

I don't think it's a container issue.

**Comment by Ulexus** [comment]
I agree with @leseb  in that I doubt this is a container problem.  I do have some experience with trying to use the S3 compatibility layer, however.  I have found it to be finicky about the bucket names.  Try using an upper-case first bucket character; then, if that still fails, try an upper-case bucket name without any special characters (i.e., remove the dashes).

**Comment by ink1** [comment]
Thank you both. I have asked for help on the ceph user list.
The problem is not limited to bucket creation, it is more general. Eg. listing buckets does not work too
```
for bucket in conn.get_all_buckets():
    print "{name}\t{created}".format(
        name = bucket.name,
        created = bucket.creation_date,
    )
```

**Comment by leseb** [comment]
Ok thanks for reporting this. Closing this issue now :).

**Comment by ink1** [comment]
That's fine. I can confirm that this is not a ceph-docker issue. Everything is fine.
It's just it seems that radosgw-admin adds escape characters to the keys as in the example above
```
pARGxDCQ+D3fS+s6EQjeCGWLnEhMWdbncXeB\/hQu
```
Python does not need escape char for forward slash therefore resulting in the wrong secret key (one char longer). In this case the solution is simply to drop the back slash
```
aws_secret_access_key='pARGxDCQ+D3fS+s6EQjeCGWLnEhMWdbncXeB/hQu'
```
and everything works! No dark magic.

**Comment by leseb** [comment]
Weird I was thinking about this, but I generated a key like this: `5lVVZy0tmx5fVjwKCCbxjfocleFKZlOQ0ezrqeFf` and got the error as well.

Maybe I made a mistake during my copy/paste.
Glad to hear that it works now :).

**Comment by ink1** [comment]
I've also added the following to /etc/ceph/ceph.conf
```
[client.radosgw.gateway]
host = scintel
keyring = /var/lib/ceph/radosgw/scintel/keyring
rgw socket path = /var/run/ceph/ceph-client.radosgw.gateway.asok
log file = /var/log/radosgw/ceph-client.radosgw.gateway.log
rgw frontends = "civetweb port=80"
rgw print continue = false
rgw enable apis = s3, swift, admin
```
I'll try deleting this and restarting rgw

**Comment by ink1** [comment]
No difference. S3 and Swift APIs must be enabled by default. So it's just a matter of getting the key right.

**Comment by kneufeld** [comment]
For future googlers, my issue was that `rgw_dns_name` didn't match the hostname of the url I was connecting too. ie: I was trying to `curl s3.example.com` but but config was as below:

```
[client.radosgw.gateway]
    rgw_dns_name = host1.example.com
```
