### ISSUE TITLE
ceph/daemon totally broken

### ISSUE THREAD

**Issue by dmitryint** [ceph/ceph-docker#116]
for example, if run MDS:
```
sudo docker run -d --net=host \
-v /var/lib/ceph/:/var/lib/ceph/ \
-v /etc/ceph:/etc/ceph \
-e CEPHFS_CREATE=1 \
ceph/daemon mds
```

in entrypoint.sh kviator runs with `--kvstore=none` argument, what causes error:  `Backend storage not supported yet, please choose another one`

**Comment by Ulexus** [comment]
That's not good.  I'm guessing these `KV_TYPE` checks are failing... looking into it

**Comment by Ulexus** [comment]
Nope; leaky `KV_TYPE` walling... line 502 is the problem.  I'm going to hack-fix this for now, but this script needs to be refactored.

**Comment by dmitryint** [comment]
Sorry, I was wrong not all broken, but only MDS and RESTAPI.

**Comment by dmitryint** [comment]
line 572?

**Comment by Ulexus** [comment]
Yeah, I see.  I'm working on a cleanup right now that will get that, too.

**Comment by Ulexus** [comment]
Feel free to PR a quick-fix for that one, too, though.  This cleanup will take me a while, but I'll be happy to merge in a hack-fix

**Comment by Ulexus** [comment]
I believe that should do it; reopen, if necessary
