### ISSUE TITLE
What's the default .s3cfg file

### ISSUE THREAD

**Issue by tobegit3hub** [ceph/ceph-docker#124]
I'm running ceph/demo in localhost and try to test the rgw service.

Then I download the `s3cmd`. But what's the default `.s3cfg` file should I use? Can anyone help to give an sample file for me to test?

**Comment by Ulexus** [comment]
* http://lmgtfy.com/?q=ceph+.s3cmd
* http://ceph.com/docs/master/radosgw/s3/

**Comment by tobegit3hub** [comment]
I have googled it and hope you would help me out to give an tutorial to use ceph/demo. The usages of ceph cluster and single ceph container are quiet different. Anyway, if you don't need this, I will not update it any more.

**Comment by Ulexus** [comment]
Sorry, I probably went overboard with the lmgtfy link...

There really shouldn't be any differences between the containerized rgw and the bare rgw, with respect to the s3cmd function, but there _are_ some things to know about using s3cmd with rgw.  The first link in the Google search describes these peculiarities and distinctions very well:

[http://lollyrock.com/articles/s3cmd-with-radosgw/](http://lollyrock.com/articles/s3cmd-with-radosgw/)

The primary quirk I ran into was also mentioned on that page:

> Sidenote: I had a few issues using lowercase bucket names with radosgw. Uppercase buckets worked like a charm.

They also provide a detailed example `.s3cfg` file on that same page.  I don't know of anything else needed to get s3cmd working with out rgw... if you have some specific problem, though, please do open an issue for it.

**Comment by tobegit3hub** [comment]
It's fine. I'm thinking to add the `.s3cfg` file in `ceph/demo` image so that everyone can use it easily. Because the container is predictable and really suitable for tutorial or presentation. And all developers should use the same `.s3cfg` which means they don't need to configure or change anything before using.

I'm finding that one so that everyone can use it and it would be better to add it in container instead of the blog. Then I have to read through the blog and test if it works or not.

**Comment by tobegit3hub** [comment]
And I'm sorry that the blog doesn't work for `ceph/docker` because we don't setup `radosgw.example.com`. Not a repeatable tutorial.

**Comment by Ulexus** [comment]
@tobegit3hub I think the inclusion of an example `.s3cfg` file sounds like a fine idea for the demo.  Please feel free to PR one such.

(As I've tried many times, humour does not translate well to this medium... please pardon me if your last comment was meant as a joke.)

The name `radosgw.example.com` does not matter.  Simply use the hostname on which is running `radosgw`.

**Comment by tobegit3hub** [comment]
Sorry for my bad expression. I will send the pull-request if I get something :)
