### ISSUE TITLE
Update Docker Hub Ceph org with all the images

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#13]
TODO

**Comment by Ulexus** [comment]
I've added mds, rados, rbd, and rbd-volume and kicked off new builds for base,mon, and osd.

I did not add:
*  `radosgw` - it doesn't really exist
*  `rbd-(un)lock` - I don't really see it as being useful generally, since it is tied to etcd

**Comment by leseb** [comment]
Great :)
I'm working on a radosgw, I'll ship something soon, if you want to test ;-)

**Comment by Ulexus** [comment]
I'll happily test the radosgw when you get it reworked.  I've been putting that off forever.

When you get a chance, you might look at hooking up the build triggers for Github on the Docker Hub.  They've got instructions for it, and the repositories themselves are set up.  All you should have to to is enable the triggers for each of the container images.  That will make them automatically rebuild whenever a new push it done to Github.  I don't have permission, but perhaps you do.

**Comment by leseb** [comment]
I'm reworking it, however they are some many packages to install that the docker run is not that snappy anymore, that's why I built the base-rgw :/
I can ship a new version now.

Hum I'll read about it
