### ISSUE TITLE
Make ceph/demo launch using existing data

### ISSUE THREAD

**Issue by F21** [ceph/ceph-docker#130]
I really love the ceph/demo docker image because it provides a quick and simple way to spin up ceph for a development environment.

The only problem is that it currently treats every launch as a new cluster. I want to be able to keep my data when the docker container is terminated and then restart it at a later stage.

This is the command I am using to run the container:

```
sudo docker run --net=host -v /work/data/ceph/config:/etc/ceph -v /work/data/ceph/data:/var/lib/ceph -e MON_IP=192.168.33.12 -e CEPH_NETWORK=192.168.33.0/24 ceph/demo
```

Unfortunately, if I terminate the container and then launch it again, I get this error:

```
2015-07-19 06:33:20.903601 7fd39a6a9900 -1  ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-0: (22) Invalid argument
```

I believe this is because the `entrypoint.sh` file treats each launch as a new cluster and will go and create the OSDs and MDS from scratch.

If would be awesome if the script has some checks in place so that it's able to "restore" if data exists rather than create a brand new cluster.

**Comment by leseb** [comment]
Hey @F21,

This shouldn't be that difficult. I'll see if I can find some time this week to work on that.
