### ISSUE TITLE
Import https://github.com/bobrik/docker-radosgw as radosgw

### ISSUE THREAD

**Issue by Ulexus** [ceph/ceph-docker#14]
Because I didn't ever actually get around to writing a radosgw, I was looking around at what's out there.  @bobrik's image looks good to me, but he uses nginx (which I prefer, but is not reflective of what is on ceph.com).  I asked him, and he's happy to supply his code.

@leseb  Does that work for you, or do you want to try and keep with an Apache installation, consistent with the docs on ceph.com?

**Comment by bobrik** [comment]
My container actually uses tengine (nginx with patches from taobao) to
enable unbuffered uploads. I had to make my own deb package for it. Maybe
using apache isn't that bad decision for now, I'm just not using apache for
like 10 years already.

The more important issue with docker and ceph and docker is this one:
http://tracker.ceph.com/issues/10763


On 19 February 2015 at 16:13, Seán C. McCord <notifications@github.com>
wrote:

> Because I didn't ever actually get around to writing a radosgw, I was
> looking around at what's out there. @bobrik <https://github.com/bobrik>'s
> image looks good to me, but he uses nginx (which I prefer, but is not
> reflective of what is on ceph.com). I asked him, and he's happy to supply
> his code.
>
> @leseb <https://github.com/leseb> Does that work for you, or do you want
> to try and keep with an Apache installation, consistent with the docs on
> ceph.com?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph-docker/issues/14>.
>



-- 
Regards, Ian Babrou
http://bobrik.name http://twitter.com/ibobrik skype:i.babrou

**Comment by Ulexus** [comment]
@bobrik Here is a good place for that issue, if you want to open it.  I know it's a real pain, and I'm no closer to figuring it out.  After seeing that email from you, I rearranged all my OSDs to be only one per box, and it *markedly* reduced the load on my boxes.  Unfortunately, that also means I'm just avoiding the problem, rather than tracking it down.

**Comment by Ulexus** [comment]
@bobrik Ah, right.  tengine; I remember seeing that, now.  It might well be getting a bit far afield.

Unfortunately, I'm just slammed with work right now.  I actually _do_ need radosgw for Docker; I just don't have time to get it done myself right now.

I'll close this for now.

**Comment by leseb** [comment]
Having both might be an option.
I'll try to see if I can get a box with RGW running.

**Comment by bobrik** [comment]
nginx 1.8.0 was released with needed `fastcgi_request_buffering`. I'll try to update my image to see if it works as expected.
