### ISSUE TITLE
Current and future status of rbd-volume

### ISSUE THREAD

**Issue by h0tbird** [ceph/ceph-docker#141]
I am opening this issue to ask about the current status of [rbd-volume](https://github.com/ceph/ceph-docker/tree/master/rbd-volume) and what is planned for it in the future. I am trying to figure out a nice pattern to deliver RBDs to my user's containers. Seems that docker/docker#8854 will be the long term solution but meanwhile I need another approach.

So, why is `rbd-volume` tagged as NON-FUNCTIONAL? Should I give it a try?

**Comment by leseb** [comment]
Unfortunately I've never got the chance to play with it, so I don't really know.
However I don't see any reasons why you wouldn't give it a try :).
@Ulexus will definitely answer your question  but as far as I know he is currently on Holidays so you might have to wait a bit :).

**Comment by hookenz** [comment]
In some earlier docker versions --volumes-from also worked from containers with network nfs shares etc.  But then it was removed (or mount namespaces were added) and --volumes-from some-other-container containing remote mounts no longer works.  So as it stands rbd-volume will never work.  A pity that! So because of the direction docker seems to be taking in this regard, I think rbd-volume should now be removed as it's never going to work and it appears unlikely they will make it work this way again.  Instead they are coming up with an alternative but it isn't yet implemented.

Which leaves only the rbd device mounted from the host or from the container directly.  On CoreOS mounting on the host is difficult.  So hacked around an existing script someone else wrote to manage it without ceph-common installed.  It's found in the examples/CoreOS/rbdmap directory.

**Comment by Ulexus** [comment]
Thanks to a number of patches from @dmitryint  ([rbd-related PRs](https://github.com/ceph/ceph-docker/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed++rbd)), but I wouldn't design a system around it.

At best, it is a stop-gap hack to work around lack of RBD support for Docker volumes.  I looked at implementing that a year or so ago, and at that time, I didn't see a good place to hook in RBD support to the volume code.  I'm hoping with the new storage driver, that will change... but up to this point, I believe that only affects the container root, not volumes.

For now, it is (as @hookenz just said), best to mount the RBD volumes to the host and bind-mount them into the container, which is what I do.

**Comment by hookenz** [comment]
Hmm, that docker rbd-volume fix @dmitryint came up with looks interesting! I'll have to experiment with that.

**Comment by Ulexus** [comment]
As I'm combing through my vacation email, I see a reference to this on the docker-dev list:

[https://github.com/calavera/dkvolume](https://github.com/calavera/dkvolume)

Docker has volume plugins, now.  Yay!   That's definitely the way to go for `rbd-volume`, not the current implementation.

**Comment by hookenz** [comment]
@Ulexus - If I get some time over the next week I'll write a volume plugin for RBD.

**Comment by h0tbird** [comment]
Checkout this [docker-volume-ceph-rbd](https://github.com/AcalephStorage/docker-volume-ceph-rbd) I have just discovered :-)

**Comment by hookenz** [comment]
@h0tbird - Sweet! Does it work!?

**Comment by hookenz** [comment]
Of course, this is all well and good, but on CoreOS you're kindof stuck with the stable (not experimental branch) of docker.  Which means these efforts can't be used by most people yet.  Still, it's an exciting development.   Looking forward to seeing this in the mainstream.

**Comment by h0tbird** [comment]
@hookenz I don't know if it works I guess we have to try it ;-)
Thank you all for the info! I think I have enough to close the issue now.

**Comment by Ulexus** [comment]
A note:  Docker version 1.8.0 was just release with official support for volume plugins.

**Comment by h0tbird** [comment]
So far under the radar:
- https://github.com/contiv/volplugin
- https://github.com/yp-engineering/rbd-docker-plugin
- https://github.com/AcalephStorage/docker-volume-ceph-rbd

**Comment by leseb** [comment]
I'm planning on testing this soon.

**Comment by h0tbird** [comment]
@leseb great! I have already started to test one.
Check this issue I have just opened: yp-engineering/rbd-docker-plugin#1

**Comment by leseb** [comment]
@h0tbird just looked at the various repositories, setting up all these things is not as easy as I thought it'd be :). It looks like someone has started an interesting initiative here: https://github.com/contiv/volplugin/issues/10
