### ISSUE TITLE
Kubernetes example v1 api is using wrong json

### ISSUE THREAD

**Issue by lleszczu** [ceph/ceph-docker#144]
According to V1 api volume section should use "hostpath" key instead of "source"->"hostdir".

http://kubernetes.io/third_party/swagger-ui/#!/api%2Fv1/createReplicationController

**Comment by leseb** [comment]
@lleszczu can you validate this and then do a PR? I'll be happy to merge it.
Thanks!

**Comment by leseb** [comment]
Closing this for now, feel free to reopen.
