### ISSUE TITLE
ceph-docker-osd CPU Usage rate very very high

### ISSUE THREAD

**Issue by Georce** [ceph/ceph-docker#148]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                 
28750 root      20   0 1133936 176848  23364 S 465.8  0.7  26:38.37 ceph-osd -i 10 -k /var/lib/ceph/osd/ceph-10/keyring                                                                                                                     
28438 root      20   0 1116804 220084  23660 S 465.2  0.9  26:45.00 ceph-osd -i 9 -k /var/lib/ceph/osd/ceph-9/keyring                                                                                                                       
21411 root      20   0  971124 146392  21652 S   9.0  0.6   1:26.98 ceph-osd -i 11 -k /var/lib/ceph/osd/ceph-11/keyring 

My environment is Ubuntu14.04.3 Docker version 1.8.1, build d12ea79

Double  Intel(R) Xeon(R) CPU           L5520  @ 2.27GHz

Memory 32G

**Comment by Georce** [comment]
Kernel 4.0.9 My Comand is
docker run -itd --name=ceph-osd-11 --net=host -v /data/disk3/ceph-11:/var/lib/ceph/osd/ceph-11 ceph/osd

But I install ceph-osd in Physical machine Cpu Usage is little

**Comment by Ulexus** [comment]
This sounds very much as if you are running separate OSD containers on the same machine.  In that case, you need to share the ipc namespace between them.  The easiest way to do that is to add `--ipc=host` to each of those `docker run` commands.  You can also execute a _single_ container with each of the OSD directories bound in.  In this case, the container will appropriately launch the number of OSD's whose directories you pass.

See Issue #19 for more information.

**Comment by Georce** [comment]
@Ulexus  My problem has been solved. By add --pid=host
Thank you very much
