### ISSUE TITLE
Running ceph/demo on a Mac (using VBox)

### ISSUE THREAD

**Issue by TravelingTechGuy** [ceph/ceph-docker#157]
I'm trying to run ceph/demo on a Mac, using Docker Toolbox (previously tried Boot2Docker). Essentially, I'm running into the issue of what to provide for the CEPH_NETWORK and MON_IP parameters. I tried providing values based on the VM's network adapter 192.168.99.100, (so 192.168.99/24 and 192.168.99.100 respectively). I keep getting "7faeadc498c0 -1 unable to find any IP address in networks: 192.168.99.0/24" - any idea how to run the demo using a VM?

Any way to Vagrant-ize the demo, btw?

Thanks for the hard work!

**Comment by leseb** [comment]
Can you send `ip -4 a` from your VM?

**Comment by TravelingTechGuy** [comment]
```
[guy@localhost demo]$ ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 83279sec preferred_lft 83279sec
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

The command I'm trying to run, based on this info is:
`sudo docker run -d --net=host -v /etc/ceph:/etc/ceph -e MON_IP=10.0.2.15 -e CEPH_NETWORK=10.0.2.0/24 ceph/demo`

**Comment by leseb** [comment]
Using `10.0.2.15` should work, so now within the VM you can reach the cluster.
It might work from the outside using port forwarding, if it does not then use a bridged interface instead.

**Comment by TravelingTechGuy** [comment]
The problem is this fails immediately - I see no error from the docker command itself, but when listing the images after issuing it, I get:

```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                         PORTS               NAMES
5bbc47190a3c        ceph/demo           "/entrypoint.sh"    4 seconds ago       Exited (1) 4 seconds ago                           serene_stallman
8bfc67900d8d        ceph/demo           "/entrypoint.sh"    About an hour ago   Exited (1) About an hour ago                       grave_mccarthy
7cd60aefd058        ceph/demo           "/entrypoint.sh"    About an hour ago   Exited (1) About an hour ago                       furious_kowalevski
01253490fa21        ceph/demo           "/entrypoint.sh"    2 days ago          Exited (1) 2 days ago                              agitated_newton
...
```

Should I be looking for an error log somewhere?

**Comment by leseb** [comment]
Can you do a `docker logs <container id>`?

**Comment by TravelingTechGuy** [comment]
```
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
2015-09-21 16:43:19.813253 7ff731e108c0 -1 unable to find any IP address in networks: 192.168.0.0/24
```

Did it ignore the `CEPH_NETWORK` parameter?

**Comment by leseb** [comment]
This rings a bell but AFAIR the only time when I encountered this was with Kubernetes where I had trouble to pass the variables.
This should not be the case in your setup.

I just tried to run ceph/demo from a fresh pulled image and I don't have this problem :/
Which distro are you running on?

**Comment by TravelingTechGuy** [comment]
Distro: CentOS Linux release 7.1.1503 (Core)
Kernel: 3.10.0-229.14.1.el7.x86_64

I could send you the entire image if you'd like - I built it to test Ceph and it has nothing else in it.

My theory is that somewhere down the line, a script is anticipating something on the 192.168.x.x ip range. Could you try to change the base ip of your image and run the docker to verify?

**Comment by TravelingTechGuy** [comment]
Ok, I tried a brand new distro - I installed Ubuntu 15.04 on a new VM - and now it works!
So it could be something to do with CentOS (very unfortunate as our Vagrant machines use that as a base image), or something we're still missing.

One question: how do I access the RGW? It does not appear in the list of nodes shown by `ceph -s`.
I'm looking to use the S3 API, so I'll probably need to map the port to outside the VM.

**Comment by Ulexus** [comment]
@TravelingTechGuy Correct: it's really just a web server.  As such, you'll need access to its service port from whatever clients should need to use it.

**Comment by leseb** [comment]
@TravelingTechGuy I've been using ceph/demo on RHEL 7.1 and Atomic without any issues. Not sure why you're having issue.
Perhaps SELinux?

**Comment by TravelingTechGuy** [comment]
@leseb anything in particular you'd like me to check?
Also, pinging localhost:80 inside the machine, or machineip:mappedport outside yields no answer. What else should I be doing to verify RGW is up and running?

**Comment by leseb** [comment]
@TravelingTechGuy you can simply run `curl http://ip:80`. You should get an answer from rgw.
Can you see if disabling selinux changed anything?

**Comment by TravelingTechGuy** [comment]
Tried both, here are the results:
1. CentOS - disabled SELinux, rebooted - same error
2. In Ubuntu machine, curl-ing works! I now have access to RGW!
I consider this partial success as our ops guys want a CentOS solution, but it's definitely a start!
Thanks for your assistance @leseb !

**Comment by leseb** [comment]
@TravelingTechGuy how could I possibly try to reproduce your error? If you can tell me I'll see what I can do.

**Comment by TravelingTechGuy** [comment]
Any chance I can upload the VB image somewhere?

**Comment by leseb** [comment]
hum isn't Docker Toolbox only?

**Comment by TravelingTechGuy** [comment]
Oh, yes - that's how we started this thread :)
Install Docker Toolbox, use either the terminal or Kitematic to get an run the ceph/demo docker image, add the the 2 env variables - and you'll see that network error.

**Comment by leseb** [comment]
I'm kinda busy at the moment, I'll try that but I can't tell you exactly when.
Will give it a shot next week probably.

**Comment by TravelingTechGuy** [comment]
I appreciate it - no problem, take your time.
One question though, if you know the answer off the top of your head: I'm trying to access the S3 API through the RGW on port 80. It seems like the root is only targeting the bucket endpoint (unless I'm missing something). Where can i see the internal configuration you used (or the default one, if you have not manually configured it?)

**Comment by Ulexus** [comment]
@TravelingTechGuy There are no endpoint assumptions, but Ceph RGW is not 100% compatible with S3.  Take a look [here](http://docs.ceph.com/docs/master/radosgw/s3/) for the supported endpoints.

Also, if you are using `s3cmd`, there are some implementational quirks.  [This](http://lollyrock.com/articles/s3cmd-with-radosgw/) is a good reference for them.

**Comment by TravelingTechGuy** [comment]
Thanks @Ulexus - I've encountered several problems accessing the API (I'm using Node code):
1. By default the API tries to access <bucketname>.127.0.0.1:port instead of 127.0.0.1:port/bucketname
1. By default it tries accessing over SSL
1. If you provide '127.0.0.1:port' as your endpoint, it'd fail. It requires the endpoint start with `http://` or `https://` (in which case, `sslEnabled` should be set to `true`)

I used the following parameters in the S3 class constructor to circumnavigate these problems:

```
  "accessKeyId": "myKey",
  "secretAccessKey": "mySecret",
  "endpoint": "http://127.0.0.1:7778",
  "sslEnabled": false,
  "s3ForcePathStyle": true,
  "s3BucketEndpoint": false
```

Not great - but then again, this is a demo cluster.

**Comment by leseb** [comment]
Closing this for now, feel free to reopen.

**Comment by slnovak** [comment]
@TravelingTechGuy:

> Did it ignore the CEPH_NETWORK parameter?

I found out that I included the mounting of a volume to `/etc/ceph` without any configuration files in the mounted volume, I got that same error. By removing the `-v /etc/ceph:/etc/ceph`, the demo should spin up.

Hope that helps!

**Comment by TravelingTechGuy** [comment]
Thanks @sinovak, I'll give it a try!

**Comment by doukha** [comment]
@slnovak I confirm.
Thanks for @all.
