### ISSUE TITLE
Option to deploy the admin keyring in OSD containers

### ISSUE THREAD

**Issue by h0tbird** [ceph/ceph-docker#158]
I wish I had the option to deploy the admin keyring in OSD containers.
Something like `${OSD_GET_ADMIN_KEY:=0}` which triggers the `get_admin_key` function.
In my platform I run OSD containers alongside a docker RBD volume plugin which performs rbd operations.

**Comment by h0tbird** [comment]
Here you have a PR #159

**Comment by h0tbird** [comment]
And this is what I am working on:
![stack](https://cloud.githubusercontent.com/assets/417440/10194019/a8616cf0-6786-11e5-89be-4e2458858046.png)

**Comment by Ulexus** [comment]
@h0tbird I'm curious:  why bother running your CoreOS machines inside VMs, with multiple per machine, as opposed to running CoreOS on baremetal, with each instance running multiple OSDs?  Surface comprehension would lead me to believe that you will suffer more loss due to the virtualisation... but have you found some performance oddity?  (I ask because I run the latter configuration, myself.)

**Comment by h0tbird** [comment]
###### Historical reason
It all started with a pair of physical machines at home. Two where not enough for my tests so I decided to run 4 VMs per hypervisor.

###### Some other reasons I can think of
- I absorb hardware diversity at the hypervisor layer which runs CentOS 7 and they know how to deal with hardware very well.
- I can overcommit cores and RAM in order to maximize resource utilization (not proved useful yet).
- Each VM acts as an error-contention domain.
- Running puppet on the hypervisors allows me to dynamically generate cloud-config configurations before booting CoreOS.
- Using 9p virtio file system pass-through and puppet allows me to inject dynamically generated config files into the CoreOS VMs.
- I might be able to migrate this stack to the cloud if I decouple the hypervisor layer.
- I can destroy and re-build very fast for testing purposes.

I have no load yet on the system so I can't tell you how it performs.
