### ISSUE TITLE
Rebuild ceph/base

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#16]
Since wget was missing, the repo's key is not present.

**Comment by Ulexus** [comment]
I'm not sure I follow what you mean... you merged PR #10 this morning to fix the missing wget.  That was the purpose of the rebuild, to get it included.

`docker pull ceph/base && docker run -it ceph/base bash` works as expected for me, after the latest build.

**Comment by leseb** [comment]
Weird after pulling the last image today I had issue with wget (missing).
Just tested, wget is present.

**Comment by Ulexus** [comment]
Perhaps when you pulled this morning, the new build hadn't been pushed out yet.  Because they are pseudo-automated builds, they are done by Docker's servers.  It takes a few minutes to become available.
