### ISSUE TITLE
Populate KV store from container

### ISSUE THREAD

**Issue by DoubleDensity** [ceph/ceph-docker#163]
Could we consider adding populate.sh functionality in to the daemon container?

It seems that populating etcd2 is now a requirement when bootstrapping a new ceph cluster using the daemon container, but I can't find an elegant way to use it with it located externally in the examples directory.

Previously was using ceph-config but it seems that is now deprecated. Am I missing something on the proper containerized way to use this?

**Comment by Ulexus** [comment]
You're definitely correct that the _intention_ going forward is to leverage the KV store.  Unfortunately, none of us appear to have had much time, recently, to get this better tested and integrated.  PRs for this are very welcome.

**Comment by DoubleDensity** [comment]
Cool! How do you envision the ideal way to integrate this? Would it be included in the daemon container, or separate?

As a workaround for the time being I am building a separate container based off of ceph-docker/base that includes the populate.sh script. It works nicely since you already have all the dependencies in there, but the downside is that the I am including a site-specific copy of populate.sh.

Thank you and @leseb for this awesome project!

**Comment by Ulexus** [comment]
On the surface at least, I don't see a downside to using populate.sh, generalized to the runtime environment variables, within the initial statup (after all the key creation).

Ref #146 for some more things I have run across.

**Comment by DoubleDensity** [comment]
Aha! I should have found Ref #146
<https://github.com/ceph/ceph-docker/issues/146> first, it is exactly what
I was thinking.

Ideally I'd like to be able to accomplish etcd population somehow via a
systemd unit file so I can include the step in automated cluster
deployment.

**Comment by Ulexus** [comment]
The problem with it being an external unit is that you have to know when the keys are finished being built, so that they can be loaded in.  I don't think you can have a one-shot unit which triggers after the (first) exit of another unit.

I really think the keys should be loaded into etcd as they are created, by the same script as generates them.

**Comment by DoubleDensity** [comment]
I wonder though, does it need to be a one-shot unit? Would there be any harm if it attempted to populate the same keys on every boot?

**Comment by Ulexus** [comment]
Potentially, yes.  It should be expected that users may tweak the configuration.  It's unsafe for the script to automatically update existing keys, in my opinion.

**Comment by h0tbird** [comment]
I use the same [systemd unit](https://github.com/h0tbird/config-fleet/blob/master/ceph-mon.service#L14) to populate etcd and to start the Ceph monitors. All I do is use `ExecStartPre` to run the [population script](https://github.com/h0tbird/puppet-r_kvm/blob/master/templates/ceph/populate_etcd.erb). The script takes care of locking and versioning. It is actually a puppet template. The real data lives in a [YAML file](https://github.com/h0tbird/r10k-kvm/blob/production/hieradata/demo.lan/dc-1/data.yaml#L19-L78).

**Comment by streamnsight** [comment]
populate_kvstore is now integrated in the daemon image, and will populate with the defaults but will not overwrite an existing key. 
Maybe we can close this now
