### ISSUE TITLE
ceph/demo image fails to start with hostname=default

### ISSUE THREAD

**Issue by Ecsy** [ceph/ceph-docker#168]
Using docker-machine with **default** name causes failure in chrushmap creation and osd will fail.
https://github.com/ceph/ceph-docker/blob/master/demo/entrypoint.sh#L104
causes: `Error EINVAL: (22) Invalid argument`
Please handle `hostname -s` = default in entrypoint.sh

**Comment by leseb** [comment]
Do you have the entire trace?

**Comment by Ecsy** [comment]
You can reproduce it on osx:
```
docker-machine create --driver virtualbox default
eval "$(docker-machine env default)"
docker run --net=host -e MON_IP=`docker-machine ip default` -e CEPH_NETWORK=`docker-machine ip default | awk -F '.' '{print $1"."$2"."$3".0/24"}'` ceph/demo
```
this will output:
```
creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
monmaptool: monmap file /etc/ceph/ceph.monmap
monmaptool: set fsid to 76e71b27-34ba-4124-a4ed-3afc9b477cb4
monmaptool: writing epoch 0 to /etc/ceph/ceph.monmap (1 monitors)
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
ceph-mon: set fsid to 76e71b27-34ba-4124-a4ed-3afc9b477cb4
ceph-mon: created monfs at /var/lib/ceph/mon/ceph-default for mon.default
set pool 0 size to 1
0
2015-11-26 14:12:59.280447 7f9500f90900 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
2015-11-26 14:12:59.291491 7f9500f90900 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
2015-11-26 14:12:59.296381 7f9500f90900 -1 filestore(/var/lib/ceph/osd/ceph-0) could not find 23c2fcde/osd_superblock/0//-1 in index: (2) No such file or directory
2015-11-26 14:12:59.307050 7f9500f90900 -1 created object store /var/lib/ceph/osd/ceph-0 journal /var/lib/ceph/osd/ceph-0/journal for osd.0 fsid 76e71b27-34ba-4124-a4ed-3afc9b477cb4
Error EINVAL: (22) Invalid argument
```

**Comment by leseb** [comment]
You seem to be saying that this is because of the name "default". Did you try with another hostname?
If it's really because of **default** there is nothing we can do about it. It might be a Ceph issue, not ceph-docker one.

**Comment by Ecsy** [comment]
Yes I have tried and it works.
I think than main problem is here that the entrypoint.sh will try to make a call:
`ceph ${CEPH_OPTS} osd crush add 0 1 root=default host=$(hostname -s)`
which will be a `root=default host=default`, which would cause a recusrion in the crushmap and the osd will fail and could not recover without a proper crushmap configuration.
Do you think this should not be fixed in the entrypoint.sh?

**Comment by leseb** [comment]
Not sure how to fix in the entrypoint if it's a ceph issue.
What would you like to do? Check if the hostname=default then change to something else?

What don't you just use another hostname?

**Comment by Ecsy** [comment]
I will use an another hostname, just wanted to make sure nobody else runs into this issue.
Checking hostname=default and changing it should be sufficient.

**Comment by leseb** [comment]
@Ecsy Ok thanks for reporting this then. Perhaps you can PR a documentation update about this? ;)
