### ISSUE TITLE
Step-by-step guide for deploying a cluster on CoreOS

### ISSUE THREAD

**Issue by tobilg** [ceph/ceph-docker#172]
I was trying to deploy Ceph on a three node CoreOS cluster, but I wasn't successful in multiple ways. 

First, I tried to follow the manual installation video linked at https://github.com/ceph/ceph-docker#manually but this uses shell scripts (like `./3-copy`), but it's nowhere mentioned nor described what these scripts do.

Also, an overall description of the second method I tried is not available: Using `ceph/config` and then later starting the `ceph/daemon` containers on each host. A short overview would be great and would probably a lot of wasted time for a lot of people. Thanks in advance!

**Comment by tobilg** [comment]
When I start the `ceph/config` image like

```
$ docker run -e ETCDCTL_PEERS=http://192.168.200.161:4001,http://192.168.200.162:4001,http://192.168.200.163:4001 -e MON_IP=192.168.200.163 -e MON_NAME=mon-163 -e CLUSTER=ais-ceph -v /etc/ceph:/etc/ceph ceph/config
No configuration found for cluster aic-ceph. Generating.
creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
monmaptool: monmap file /etc/ceph/monmap
monmaptool: set fsid to a3d2116f-094e-4399-b872-90afb2c82960
monmaptool: writing epoch 0 to /etc/ceph/monmap (1 monitors)
completed initialization for mon-163
unlocking configuration
```

I don't receive any error. When I try to start a `mon` container afterwards like the following

```
$ docker run -d --name ceph-mon --net=host \
   -v /var/lib/ceph:/var/lib/ceph \
   -v /etc/ceph:/etc/ceph \
   -e MON_IP=192.168.200.163 \
   -e CEPH_PUBLIC_NETWORK=192.168.200.0/24 \
   -e MON_NAME=mon-163 \
   -e CLUSTER=ais-ceph \
   -e KV_TYPE=etcd \
   -e KV_IP=192.168.200.163 \
   -e KV_PORT=4001 \
   ceph/daemon mon
```

it starts the container, but if I have a look in the logs, there's an error message that the key `/ceph-config/aic-ceph/global` wasn't found:

```
$ docker logs ceph-mon
Adding Mon Host - mon-163
No configuration found for cluster ais-ceph. Generating.
2015-12-04T11:29:45Z coreos-hw-node-3.ais.local confd[21]: INFO Backend set to etcd
2015-12-04T11:29:45Z coreos-hw-node-3.ais.local confd[21]: INFO Starting confd
2015-12-04T11:29:45Z coreos-hw-node-3.ais.local confd[21]: INFO Backend nodes set to 192.168.200.163:4001
2015-12-04T11:29:45Z coreos-hw-node-3.ais.local confd[21]: ERROR 100: Key not found (/ceph-config/aic-ceph/global) [1966842]
Waiting for confd to write initial templates...
```

**Comment by Ulexus** [comment]
Ref #146 #163 

Bootstrapping the key-value stores is still a lack.  Unfortunately, I haven't had the time to smooth it out.  There is a [populate script](/examples/confd/populate.sh) which you can use to manually set up your key-value store.

That population should be a part of the internal bootstrapping, but we haven't gotten there yet.

**Comment by tobilg** [comment]
@Ulexus Thanks for the feedback. If I understand this correctly, the `populate.sh` script would need to be  integrated in the `ceph/config` image, right? If so, maybe I could do this.

Still, I think so more docs are very necessary. I tried to use the [CoreOS unit files](https://github.com/ceph/ceph-docker/tree/master/examples/coreos/units), but also failed. This feels like being stuck at 95% because there's already so much there yet :-| I really appreciate the work you and others have done on this project, but I'd like to really *beg* for more documentation.

**Comment by Ulexus** [comment]
What didn't work with the unit files?  Those are almost verbatim what I use.

**Comment by Ulexus** [comment]
And no, I wouldn't attach the populate script to `ceph/config`... the use-case for `ceph/config` is somewhat suspect.  It should go into `ceph/daemon` with the rest of the bootstrapping stuff (in the `mon` section).

**Comment by streamnsight** [comment]
using -e ETCDCTL_PEERS=http://${IP}:4001 worked fine for me bootstraping config with my etcd backend

the full command:

`docker run -e ETCDCTL_PEERS=http://${IP}:4001 -e MON_IP=${IP} -e MON_NAME=ceph_mon -e CLUSTER=ceph -v /var/lib/ceph:/var/lib/ceph -v /etc/ceph:/etc/ceph ceph/config`

**Comment by streamnsight** [comment]
Actually. After gettign to configuring the OSDs, this doesn't work.
I think this is all related to the refactor of the services in the daemon: the KV store paths have changed

with ceph/config the data is in /ceph/cluster_id/config

when the daemon using KV store looks for data in /ceph-config/cluster_id/

**Comment by tobilg** [comment]
@streamnsight If you look closely, my Docker run configuration is mostly the same. And, as I outlined, I get an error with a missing value in etcd. That's not something I can actively configure with the `ceph/config` image.

Furthermore, it's obvious that the fleet unit files will contain per-host values. But they will ideally auto-populated when run via fleet imho. And therefore I think some docs would be great, otherwise it's just guesswork.

**Comment by Ulexus** [comment]
@tobilg Correct.  The CoreOS units are the ones I built, which use the older `osd_directory` method.  I use the `MachineID=%i` `X-Fleet` scheme for both my OSD and MON deployments.  Basically, the MON_ID is equivalent to the machine-id.

My cloud-config setup for each of my OSDs formats and mounts each disk into `/var/lib/ceph/osd/*`, and I determine in advance what the OSD IDs are going to be (by manually running `ceph osd create` on a monitor node).

**Comment by tobilg** [comment]
@Ulexus Does that mean that what is described at https://github.com/ceph/ceph-docker/tree/master/daemon#populate-key-value-store is replaced by running the [populate script](https://github.com/ceph/ceph-docker/blob/master/examples/confd/populate.sh) manually?

If so, which Docker image should be started, and with which parameters? Thanks in advance!

**Comment by Ulexus** [comment]
No, the populate-kvstore option is more the evolution and inclusion of the populate script.  That was a recent, welcome addition (a couple weeks ago; more recent than my last reply) by @streamnsight .

You want the `ceph/daemon` image.  It should have everything you need.  You simply run it with different arguments to run the different daemons.

**Comment by tobilg** [comment]
@Ulexus Thanks for the clarification. I still think that a step-by-step guide would be useful, because there is currently no central place IMHO where the current status of the Docker images is reflected. ("How do I deploy a Ceph cluster, one by one...").

Furthermore, with the `latest` version of `ceph/daemon` I can't get it to work so that I can use more than one monitor. Also, it only works if I specity another value than `CLUSTER=ceph` for the `populate-kvstore` step, and then use the standard value `ceph` with the monitor step.

This seems completly random and based on trial and error, which is somehow frustrating to me because Ceph seems to be the ideal solution for us.

**Comment by Ulexus** [comment]
You are absolutely correct.  Such a guide does need to be written.  I will try to make that happen in January, if someone else doesn't get it done first.

`populate-kvstore` should be run once, only, for the cluster.  However, it should be fine to run it multiple times if you want to integrate it with your MON startup.  You'll get a whole bunch of "value is already set" messages, but it should run through and be fine.  Note that the population is just to your etcd or consul, not to your local Ceph config.  You'll still need to make sure you are telling the MON that you are using whatever KV store you are using, so that it can build the configuration files from there.

Can you post the details if this isn't working for you?

**Comment by tobilg** [comment]
I'm not running the populate step twice, I'm trying to set up three monitor instances on three different hosts.

**Configuration**:
```
docker run -it --name ceph-populate --net=host \
-v /etc/ceph:/etc/ceph \
-v /var/lib/ceph/:/var/lib/ceph/ \
-e MON_IP=192.168.200.163 \
-e CEPH_PUBLIC_NETWORK=192.168.200.0/24 \
-e CLUSTER=ais-ceph \
-e KV_TYPE=etcd \
-e KV_IP=192.168.200.163 \
-e KV_PORT=4001 \
ceph/daemon populate_kvstore
```

produces

```
adding key /auth/cephx with value true to KV store
adding key /auth/cephx_require_signatures with value false to KV store
adding key /auth/cephx_cluster_require_signatures with value true to KV store
adding key /auth/cephx_service_require_signatures with value false to KV store
adding key /global/max_open_files with value 131072 to KV store
adding key /global/osd_pool_default_pg_num with value 128 to KV store
adding key /global/osd_pool_default_pgp_num with value 128 to KV store
adding key /global/osd_pool_default_size with value 3 to KV store
adding key /global/osd_pool_default_min_size with value 1 to KV store
adding key /global/mon_osd_full_ratio with value .95 to KV store
adding key /global/mon_osd_nearfull_ratio with value .85 to KV store
adding key /mon/mon_osd_down_out_interval with value 600 to KV store
adding key /mon/mon_osd_min_down_reporters with value 4 to KV store
adding key /mon/mon_clock_drift_allowed with value .15 to KV store
adding key /mon/mon_clock_drift_warn_backoff with value 30 to KV store
adding key /mon/mon_osd_report_timeout with value 300 to KV store
adding key /osd/journal_size with value 100 to KV store
adding key /osd/osd_mkfs_type with value xfs to KV store
adding key /osd/osd_mkfs_options_xfs with value "-f -i size=2048" to KV store
adding key /osd/osd_mon_heartbeat_interval with value 30 to KV store
adding key /osd/pool_default_crush_rule with value 0 to KV store
adding key /osd/osd_crush_update_on_start with value true to KV store
adding key /osd/osd_objectstore with value filestore to KV store
adding key /osd/filestore_merge_threshold with value 40 to KV store
adding key /osd/filestore_split_multiple with value 8 to KV store
adding key /osd/osd_op_threads with value 8 to KV store
adding key /osd/filestore_op_threads with value 8 to KV store
adding key /osd/filestore_max_sync_interval with value 5 to KV store
adding key /osd/osd_max_scrubs with value 1 to KV store
adding key /osd/osd_recovery_max_active with value 5 to KV store
adding key /osd/osd_max_backfills with value 2 to KV store
adding key /osd/osd_recovery_op_priority with value 2 to KV store
adding key /osd/osd_client_op_priority with value 63 to KV store
adding key /osd/osd_recovery_max_chunk with value 1048576 to KV store
adding key /osd/osd_recovery_threads with value 1 to KV store
adding key /osd/ms_bind_port_min with value 6800 to KV store
adding key /osd/ms_bind_port_max with value 7100 to KV store
adding key /client/rbd_cache_enabled with value true to KV store
adding key /client/rbd_cache_writethrough_until_flush with value true to KV store
adding key /mds/mds_cache_size with value 100000 to KV store
```

**Monitor 1**:
```
docker run -d --name ceph-mon --net=host \
-v /var/lib/ceph:/var/lib/ceph \
-e MON_IP=192.168.200.163 \
-e CEPH_PUBLIC_NETWORK=192.168.200.0/24 \
-e KV_TYPE=etcd \
-e KV_IP=192.168.200.163 \
-e KV_PORT=4001 \
ceph/daemon mon
```

produces

```
admin@coreos-hw-node-3 ~ $ docker logs ceph-mon
Adding Mon Host - coreos-hw-node-3
No configuration found for cluster ceph. Generating.
2015-12-22T14:19:59Z coreos-hw-node-3 confd[64]: INFO Backend set to etcd
2015-12-22T14:19:59Z coreos-hw-node-3 confd[64]: INFO Starting confd
2015-12-22T14:19:59Z coreos-hw-node-3 confd[64]: INFO Backend nodes set to 192.168.200.163:4001
2015-12-22T14:19:59Z coreos-hw-node-3 confd[64]: INFO Target config /etc/ceph/ceph.conf out of sync
2015-12-22T14:19:59Z coreos-hw-node-3 confd[64]: INFO Target config /etc/ceph/ceph.conf has been updated
Creating Keyrings
creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
creating /var/lib/ceph/bootstrap-osd/ceph.keyring
creating /var/lib/ceph/bootstrap-mds/ceph.keyring
creating /var/lib/ceph/bootstrap-rgw/ceph.keyring
Creating Monmap
monmaptool: monmap file /etc/ceph/monmap
monmaptool: set fsid to b6955cd3-6fcb-47b8-879a-5c570888b92c
monmaptool: writing epoch 0 to /etc/ceph/monmap (1 monitors)
Importing Keyrings and Monmap to KV
Completed initialization for coreos-hw-node-3
Removing lock for coreos-hw-node-3
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
ceph-mon: set fsid to b6955cd3-6fcb-47b8-879a-5c570888b92c
ceph-mon: created monfs at /var/lib/ceph/mon/ceph-coreos-hw-node-3 for mon.coreos-hw-node-3
2015-12-22 14:20:00.480292 7fa0b8adf8c0  0 set uid:gid to 64045:64045
2015-12-22 14:20:00.480373 7fa0b8adf8c0  0 ceph version 9.2.0 (bb2ecea240f3a1d525bcb35670cb07bd1f0ca299), process ceph-mon, pid 1
2015-12-22 14:20:00.535948 7fa0b8adf8c0 -1 WARNING: 'mon addr' config option 192.168.200.163:0/0 does not match monmap file
         continuing with monmap configuration
2015-12-22 14:20:00.535969 7fa0b8adf8c0  0 starting mon.coreos-hw-node-3 rank 0 at 192.168.200.163:6789/0 mon_data /var/lib/ceph/mon/ceph-coreos-hw-node-3 fsid b6955cd3-6fcb-47b8-879a-5c570888b92c
starting mon.coreos-hw-node-3 rank 0 at 192.168.200.163:6789/0 mon_data /var/lib/ceph/mon/ceph-coreos-hw-node-3 fsid b6955cd3-6fcb-47b8-879a-5c570888b92c
2015-12-22 14:20:00.536090 7fa0b8adf8c0  1 mon.coreos-hw-node-3@-1(probing) e0 preinit fsid b6955cd3-6fcb-47b8-879a-5c570888b92c
2015-12-22 14:20:00.536334 7fa0b8adf8c0  0 mon.coreos-hw-node-3@-1(probing) e0  my rank is now 0 (was -1)
2015-12-22 14:20:00.536343 7fa0b8adf8c0  1 mon.coreos-hw-node-3@0(probing) e0 win_standalone_election
2015-12-22 14:20:00.551699 7fa0b8adf8c0  0 log_channel(cluster) log [INF] : mon.coreos-hw-node-3@0 won leader election with quorum 0
2015-12-22 14:20:00.567496 7fa0b8adf8c0  1 mon.coreos-hw-node-3@0(leader) e0 apply_quorum_to_compatset_features enabling new quorum features: compat={},rocompat={},incompat={4=support erasure code pools,5=new-style osdmap encoding,6=support isa/lrc erasure code,7=support shec erasure code}
2015-12-22 14:20:00.701109 7fa0b22a9700  1 mon.coreos-hw-node-3@0(leader).paxosservice(pgmap 0..0) refresh upgraded, format 1 -> 0
2015-12-22 14:20:00.701117 7fa0b22a9700  1 mon.coreos-hw-node-3@0(leader).pg v0 on_upgrade discarding in-core PGMap
2015-12-22 14:20:00.711963 7fa0b22a9700  1 mon.coreos-hw-node-3@0(leader).paxosservice(auth 0..0) refresh upgraded, format 1 -> 0
2015-12-22 14:20:00.712039 7fa0b22a9700  1 mon.coreos-hw-node-3@0(probing) e1 win_standalone_election
2015-12-22 14:20:00.728085 7fa0b22a9700  0 log_channel(cluster) log [INF] : mon.coreos-hw-node-3@0 won leader election with quorum 0
2015-12-22 14:20:00.743939 7fa0b22a9700  0 log_channel(cluster) log [INF] : monmap e1: 1 mons at {coreos-hw-node-3=192.168.200.163:6789/0}
2015-12-22 14:20:00.875548 7fa0b22a9700  1 mon.coreos-hw-node-3@0(leader).paxosservice(auth 0..0) refresh upgraded, format 1 -> 0
2015-12-22 14:20:00.875575 7fa0b22a9700  0 log_channel(cluster) log [INF] : pgmap v1: 0 pgs: ; 0 bytes data, 0 kB used, 0 kB / 0 kB avail
2015-12-22 14:20:00.905542 7fa0b22a9700  0 mon.coreos-hw-node-3@0(leader).mds e1 print_map
epoch   1
flags   0
created 0.000000
modified        2015-12-22 14:20:00.760020
tableserver     0
root    0
session_timeout 0
session_autoclose       0
max_file_size   0
last_failure    0
last_failure_osd_epoch  0
compat  compat={},rocompat={},incompat={}
max_mds 0
in
up      {}
failed
damaged
stopped
data_pools
metadata_pool   0
inline_data     disabled

2015-12-22 14:20:00.905621 7fa0b22a9700  1 mon.coreos-hw-node-3@0(leader).osd e1 e1: 0 osds: 0 up, 0 in
2015-12-22 14:20:00.921462 7fa0b22a9700  0 mon.coreos-hw-node-3@0(leader).osd e1 crush map has features 1107558400, adjusting msgr requires
2015-12-22 14:20:00.921465 7fa0b22a9700  0 mon.coreos-hw-node-3@0(leader).osd e1 crush map has features 1107558400, adjusting msgr requires
2015-12-22 14:20:00.921468 7fa0b22a9700  0 mon.coreos-hw-node-3@0(leader).osd e1 crush map has features 1107558400, adjusting msgr requires
2015-12-22 14:20:00.921471 7fa0b22a9700  0 mon.coreos-hw-node-3@0(leader).osd e1 crush map has features 1107558400, adjusting msgr requires
2015-12-22 14:20:00.921596 7fa0b22a9700  1 mon.coreos-hw-node-3@0(leader).paxosservice(auth 1..1) refresh upgraded, format 0 -> 1
2015-12-22 14:20:00.921762 7fa0b22a9700  0 log_channel(cluster) log [INF] : mdsmap e1: 0/0/0 up
2015-12-22 14:20:00.938621 7fa0b22a9700  0 log_channel(cluster) log [INF] : osdmap e1: 0 osds: 0 up, 0 in
2015-12-22 14:20:00.954922 7fa0b22a9700  0 log_channel(cluster) log [INF] : pgmap v2: 64 pgs: 64 creating; 0 bytes data, 0 kB used, 0 kB / 0 kB avail
```

If I add `-e CLUSTER=ais-ceph \` to the *Montor 1* step, the monitor will not start, only if I run it with the standard `ceph` value.

Also, as said, I can't run the same monitor command (only with host-specific `MON_IP`s) more than once. The containers just don't start, and the logs are empty.

Thanks a lot for your help.

**Comment by streamnsight** [comment]
@tobilg 
Sorry about the troubles. I guess this is my fault: I work with etcd and had found several issues I had put together into one big PR, but was told it would be better to split that into bug fixes and features.
I guess I missed pushing this bug fix.
I added the step in `config-kv.sh` that tries to pre-populate the different keys needed by `confd`, which otherwise fails with etcd because etcdctl does not have the ability to check for empty directories.
However, what you see happens because once you run the populate_kvstore, the keys already exist (the opposite problem!)

I just opened a PR to fix this by ignoring errors when the key already exists.

As far as the second issue, where you say you can't use anything but `ceph` for `CLUSTER`, I think it is probably linked.
What you need to do when things have failed, is clear the etcd store, and the folders with the files the monitor uses. 
To clear everything:
```
rm -rf /etc/ceph
rm -rf /var/lib/ceph
etcdctl rm /ceph-config --recursive
```

The script looks for those files and if they exists, will just try to start the existing monitor defined in /etc/ceph, but if somehow something failed (here because the KV config could not be retrieved) and the monmap was created, it will try to start a broken monitor.

With the PR is just opened, it should fix the problem.
Sorry about the troubles.

**Comment by streamnsight** [comment]
@tobilg 
btw, you're not supposed to have more than one monitor per host, so the part where you say 
*I can't run the same monitor command (only with host-specific MON_IPs) more than once. The containers just don't start, and the logs are empty.*
makes sense, although we should probably have better logging there to explain what's going on.

**Comment by tobilg** [comment]
@streamnsight First of all, thanks a lot for the fast feedback. Looking forward to test the PR tomorrow. 

Sorry for the confusion about the monitors. I was trying to say that I start one monitor per host, on three hosts overall. 

I can start one monitor, but when I try to start one on each of the two other hosts, it fails without error message. I believe it could be something about locking in etcd, but I'm not sure...

**Comment by tobilg** [comment]
I forgot to mention: Each time before I tried to start the cluster config, I removed the traces of earlier attempts with the exact steps you outlined. 

So etcd and the file system should have been "als new"...

**Comment by tobilg** [comment]
Quick feedback: Now I can successfully run `populate_kvstore` and afterwards start 3 different monitors on my 3 different hosts. Thanks a lot for the fixes!

I'll try to write up what I did to set up my cluster on CoreOS... Once this is done, I can submit it as documentation via pull request...
