### ISSUE TITLE
RGW_NAME is not used, client.radosgw.gateway is hardcoded

### ISSUE THREAD

**Issue by bobrik** [ceph/ceph-docker#186]
I want to run two s3 gateways on different hostnames:

* s3.aaa.com
* s3.bbb.com

In theory, it should be possible by having the following in the config:

```
[client.radosgw.aaa]
rgw_dns_name = s3.aaa.com

[client.radosgw.bbb]
rgw_dns_name = s3.bbb.com
```

and running two instances of radosgw with different `RGW_NAME`. In fact, `client.radosgw.gateway` is always passed an the instance name.

**Comment by Ulexus** [comment]
Perhaps I'm missing something, but It appears to me to be using the `RGW_NAME` variable in the `radosgw` [execution](https://github.com/ceph/ceph-docker/blob/master/daemon/entrypoint.sh#L414).  

Where is it failing for you, or are you talking about something else?

**Comment by bobrik** [comment]
What about this one? https://github.com/ceph/ceph-docker/blob/master/radosgw/entrypoint.sh#L37-L41

**Comment by Ulexus** [comment]
Ah, yes.  We aren't really maintaining the discrete daemons, at this point.  It looks like that one has missed the update.  Can you use the `ceph/daemon` one instead?

**Comment by Ulexus** [comment]
It should be just a matter of changing `ceph/radosgw` to `ceph/daemon rgw`

**Comment by bobrik** [comment]
I actually worked around by doing nginx magic in front of rgw.

Will switch to `ceph/daemon` next time I update containers, thanks!
