### ISSUE TITLE
Question: How to setup users for Rados Gateway

### ISSUE THREAD

**Issue by tobilg** [ceph/ceph-docker#193]
I was able to create my Ceph three-node cluster, and also to start a Rados Gateway. If I access my RGW URL, I see

```xml
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Owner>
        <ID>anonymous</ID>
        <DisplayName/>
        </Owner>
    <Buckets/>
</ListAllMyBucketsResult>
```

Now, if I want to create a bucket via `PUT http://192.168.200.162:10000/bucket1` I receive a 403 error as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <RequestId>tx000000000000000000004-00568d0a9b-373f-default</RequestId>
</Error>
```

I read in the [docs](http://docs.ceph.com/docs/master/radosgw/config/#create-a-radosgw-user-for-s3-access) that one can create users like this:

    sudo radosgw-admin user create --uid="testuser" --display-name="First User"

If I try this with my running container, I get an error message:

```
$ docker exec 6053b4bdb2c8 radosgw-admin user create --uid="project1_user" --display-name="Project 1 User"
2016-01-06 13:20:32.646837 7f83a47287c0 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
2016-01-06 13:20:32.646849 7f83a47287c0 -1 monclient(hunting): ERROR: missing keyring, cannot use cephx for authentication
2016-01-06 13:20:32.646850 7f83a47287c0  0 librados: client.admin initialization error (2) No such file or directory
couldn't init storage provider
```

How is the authentication/users/permissions meant to be managed if I use a KV backend (etcd)? I'm running on CoreOS latest stable.

**Comment by tobilg** [comment]
I checked the [old docs](https://github.com/ceph/ceph-docker/tree/master/radosgw#usage) and found

> It will look for `/etc/ceph/ceph.client.admin.keyring` with which to authenticate. You can get ceph.client.admin.keyring from another Ceph node.

This matches somehow the error message I'm seeing. A keyring file was created on my host successfully, named `/var/lib/ceph/radosgw/coreos-hw-node-2/keyring`. 

Would the creation of a symbolic link (at/after https://github.com/ceph/ceph-docker/blob/master/daemon/entrypoint.sh#L464) help to fix this?

**Comment by leseb** [comment]
@tobilg the symlink won't solve the entire issue for 2 reasons:

* i'm not sure if the permissions are enough
* you'd have to call `radosgw-admin` like this:

`radosgw-admin -n client.rgw.${RGW_NAME} -k /etc/ceph/keyring``


First try to call it like this and check it works:

`radosgw-admin -n client.rgw.${RGW_NAME} -k /var/lib/ceph/radosgw/${RGW_NAME}/keyring user create --uid="project1_user" --display-name="Project 1 User"`

**Comment by tobilg** [comment]
Thanks for the fast feedback @leseb I set up Ceph with etcd, I think that why there's no keyring in `/etc/ceph` by default:

```
$ docker exec <rgwContainerId> ls -la /etc/ceph
total 64
drwxr-xr-x. 2 root root 4096 Jan  6 15:11 .
drwxr-xr-x. 1 root root 4096 Jan  6 14:52 ..
-rw-r--r--. 1 root root 1853 Jan  6 14:52 ceph.conf
-rw-r--r--. 1 root root   92 Nov 10 12:09 rbdmap
```

Concerning your last suggestion, I don't seem to have the `RGW_NAME` present in my environment (as far as I understand it's only set in `entrypoint.sh`, but I might be wrong, noob here):

```
$ docker exec <rgwContainerId> env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=coreos-hw-node-2
KV_TYPE=etcd
KV_IP=192.168.200.163
KV_PORT=4001
RGW_CIVETWEB_PORT=10000
ETCDCTL_VERSION=v2.2.0
ETCDCTL_ARCH=linux-amd64
CEPH_VERSION=infernalis
KVIATOR_VERSION=0.0.5
CONFD_VERSION=0.10.0
HOME=/root
```

After a lot of trial and error I found out that after I create a symlink manually like

    docker exec <rgwContainerId> ln -s /var/lib/ceph/radosgw/coreos-hw-node-2/keyring /etc/ceph/ceph.client.rgw.coreos-hw-node-2.keyring

I can run 

    docker exec <rgwContainerId> radosgw-admin user create --uid="project1_user" --display-name="Project 1 User" --name client.rgw.coreos-hw-node-2

successfully.

**Comment by leseb** [comment]
@tobilg yes `RGW_NAME` is likely to be the hostname unless you specify anything else.
Ok so it seems permissions on that key are enough, we can go ahead and do the symlink you suggested.
Want to submit a PR? :) Thanks!

**Comment by tobilg** [comment]
I can surely submit a PR... What I'm not sure about is if non-KV store setups are potentially negatively affected by symlinking to `/etc/ceph`. Do you have more insight on this?

What could also probably be enough (well, I'd prefer to do this in all cases) is to amend the docs regarding the usage of `radosgw-admin`.

After having a look at https://github.com/ceph/ceph-docker/blob/master/daemon/entrypoint.sh#L8 

```
docker exec <rgwContainerId> radosgw-admin -n client.rgw.${hostname -s} -k /var/lib/ceph/radosgw/${hostname -s}/keyring <commands>
``` 

seems to be a general starting point as far as I understand.

Still, one question remains: How does one handle the storage of the user configuration?

**Comment by Ulexus** [comment]
So far as I am aware, the user configuration (permissions and auth material) is stored within Ceph's internal datastore.  Is that the configuration to which you refer?

**Comment by tobilg** [comment]
Yes, that is what I meant. I'll try to submit a PR today then.

**Comment by tobilg** [comment]
Added a hint in the README.md, see https://github.com/ceph/ceph-docker/pull/196
