### ISSUE TITLE
Question about defaults

### ISSUE THREAD

**Issue by nazar-pc** [ceph/ceph-docker#194]
Why is it necessary to populate Key Value store?
I've tried to start everything with Consul without populating defaults and it seems to work fine.
I guess those are defaults already provided by Ceph and mentioned in respective docs.
If it is so, then why do we need to populate them explicitly, are they any different from defaults in docs?

**Comment by Ulexus** [comment]
It _should_ no longer be necessary to manually populate the KV store; a recent update implemented the auto-population feature, but it is not yet very widely tested.

To which docs do you refer?

**Comment by nazar-pc** [comment]
Official docs, for instance, one of pages: http://docs.ceph.com/docs/master/cephfs/mds-config-ref/
There are keys and respective default values.
Even with auto-population (I'm just exploring last commits/PRs, one of which was about population entrypoint, didn't go through all of them), why is it necessary in the first place?

**Comment by leseb** [comment]
It is necessary to generate ceph's initial config file.

**Comment by nazar-pc** [comment]
I understood this from readme, I do not understand why? It works perfectly fine without this step. Defaults are already present in docs, so from practical point of view it is redundant to specify the same settings explicitly.
In my opinion it is better to hardcode as few configs as possible to be as close to stock as possible and change anything if only it is required.

**Comment by leseb** [comment]
There is no real impact since as you said they are default options anyway. The idea here is to point users to valuable configuration options. That's was the initial intention.

**Comment by nazar-pc** [comment]
In this case I'd not say in readme that this step is crucial to get Ceph up and running, but rather say like *Hey, those are defaults, you can extend base image by providing modified file of mount `/etc/ceph` with modified settings and then populate them to KV stoge, but generally those are already used by default, so if you are fine with them - no extra steps needed*.

I really like to always condense examples to bare minimum that still works and clearly state what is required in order to start and what is optional.

**Comment by leseb** [comment]
I agree, would you be so kind to send a PR about this?
So we clarify this for everyone?

Thanks!
