### ISSUE TITLE
cannot cold-start multiple monitors

### ISSUE THREAD

**Issue by fmeppo** [ceph/ceph-docker#219]
I had a set of 3x monitors created, then rebooted all parts of my ceph cluster.  OSDs come up, and try to find MONs - as expected.  MONs don't start, though.  I'm using etcd; from the logs I can see ceph/daemon pulling out config & keyrings, then connecting to peers (which are all dead) for the latest monmap.  Then I get this:

Peers not found, using initial monmap.
Removing lock for MON_HOST_1
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
ceph-mon: error decoding monmap /etc/ceph/monmap: buffer::malformed_input: void MonMap::decode(ceph::buffer::list::iterator&) decode past end of struct encoding

That terminal error message comes from the ceph-mon binary.  Looking at /etc/ceph/monmap, it appears to only have a single entry for MON_HOST_1, so I could believe it's trying to pull 2 more entries (for my 2 non-existant MONs).  Currently diving through the ceph-mon source to confirm.

Any idea how to easily rebuild this ceph cluster - or at least restart the redundant MONs?

**Comment by leseb** [comment]
@fmeppo do you run this through k8s?
can you describe your env a bit more?

**Comment by fmeppo** [comment]
Nope - no kubernetes here.  I'm PXE-booting CoreOS, making stateless docker hosts.  Ideally, I'll start docker daemons straight from the cloud init config in Core, and scale this out across dozens (and eventually hundreds) of hosts.  Right now, I'm using ceph-docker (fairly successfully) across 10ish older test machines, each with 4 internal drives completely dedicated to ceph-osd (and no in-node persistent storage).  Longer term, I intend to use Ceph as backing store for block & filesystem purposes underneath a wide variety of docker containers.

Right now, I'm simulating a cold boot of the whole world.  The ceph-docker config lives in etcd, and we've got some etcd replicas running on hosts with persistent storage, so that's good.  I was hoping to avoid persistent storage in monitors completely....but we'll still need to be able to cold-boot the whole world.  Recommendations welcome.

**Comment by fmeppo** [comment]
More digging: looks like a binary monmap in my etcd was being corrupted on extraction (opened issue #220 ), and that's the root cause of the error message from ceph-mon.  It's not clear if this is the only problem; I'll need to patch #220, then recreate my test cluster and repeat this testing to be sure.

**Comment by fmeppo** [comment]
Finally had time to finish testing this.  #220 was an issue, but that's fixed now (and my apologies for the lack of auto-migration there).  There's also a documentation miss; the notes on starting a monitor do not indicate mapping a volume to /var/lib/ceph.  If this is omitted, /var/lib/ceph isn't persistent - which means things like the crushmap are also not persistent.  The monitor map can be pulled from etcd, but crushmaps can't (and ostensibly shouldn't, since they can change fairly frequently and there's no hook to store that data externally).  Without persistence, if all monitors ever go down the crushmap is lost, and data on the filesystem isn't really recoverable.  As-is, the rebooting monitors form a new Ceph, with a new (default) rbd pool, and any OSDs from the previous boot are missing (even if they boot up again).

I should have a PR fixing up the docs and explaining this shortly.

**Comment by leseb** [comment]
@fmeppo thanks for your feedback on this, you're right we should probably (well the operator) use persistent store to store the mon store content. Looking forward to seeing your PR.

**Comment by fmeppo** [comment]
See PR #224 
I think this can be closed out with just a documentation update at this point.
