### ISSUE TITLE
ceph/tools image does not exist in Docker Hub

### ISSUE THREAD

**Issue by thecanadianbaker** [ceph/ceph-docker#229]
In the examples for [CoreOS tools](https://github.com/ceph/ceph-docker/tree/master/examples/coreos/tools) the README references the image `ceph/tools` which does not exist in the official [Ceph repos](https://hub.docker.com/u/ceph/).

Can we have this added to the registry?

**Comment by Ulexus** [comment]
Curious.  There has never been a `ceph/tools`.  I imagine this should read `ceph/base`, as the base image contains all of the Ceph tools with no entrypoint script.

**Comment by thecanadianbaker** [comment]
Per discussions on #228 the name has been changed to `ceph/install-utils`
Once #230 is merged and pushed this can be closed

**Comment by thecanadianbaker** [comment]
Closed with #230
