### ISSUE TITLE
deploy your Ceph cluster demo video‘s scripts

### ISSUE THREAD

**Issue by guijianfeng** [ceph/ceph-docker#232]
There're several scripts in the video like 2-mon, 3-copy, but I can't find them. Could you please provide those scripts?

**Comment by macropin** [comment]
And while you're at it can you please document the usage of `ceph/demo` to make it easy for noobs to get started.

**Comment by leseb** [comment]
@guijianfeng I don't have the scripts anymore but it's just scp files from /etc/ceph/ and /var/lib/ceph/bootstrap* on the other hosts.

@macropin what's not clear about `ceph/demo` and what's missing from https://github.com/ceph/ceph-docker/blob/master/demo/README.md?

**Comment by macropin** [comment]
@leseb I felt that there was not enough explanation given as to what the container does, or next steps (I started some daemons.. so now what?). It would also be nice to have a complete demo that includes client usage. A demo should hold the user's hand all the way till they have the "a ha" moment of realisation that they have achieved success!

I found a bit more information here: http://ceph.com/planet/ceph-cluster-on-docker-for-testing/, but not really sufficient for a complete noob to get started.

You might want to reference your blog here also. I found this post more useful that anything here on github: http://www.sebastien-han.fr/blog/2015/06/23/bootstrap-your-ceph-cluster-in-docker/

**Comment by jing-tw** [comment]
Hi,
I wrote a document for demo and 3 host demos for using ceph/docker based on the video. You can pull the code to try.

[ceph, installation, docker, allinone] How to install ceph using Docker -- allinone, https://docs.google.com/document/d/194uP5cvrbArDCvUbNHaj7_XIeKoKCb_p8kGRk63OsLc/edit?usp=sharing

[ceph, installation, docker, 3 hosts] How to install ceph using Docker -- 3 hosts, https://docs.google.com/document/d/1ZkG3X0RmwCHTiuu_3usYpoZRbxeHQhrZQ-54EhsQuL8/edit?usp=sharing


Jing.
