### ISSUE TITLE
RFC: new bootstrap strategy for config 

### ISSUE THREAD

**Issue by rootfs** [ceph/ceph-docker#249]
Current config container uses the [following strategy](https://hub.docker.com/r/ceph/config/):
- An /etc/ceph/ceph.conf is found, do nothing.
- If a cluster configuration is available, it will be written to /etc/ceph
- If no cluster configuration is available, it will be bootstrapped. A lock mechanism is used to allow concurrent deployment of multiple hosts.

I am proposing:
- if /etc/ceph/ceph.conf is found, skip creating /etc/ceph/ceph.conf, but continue the following steps
- If a cluster configuration is available, it will be written to /etc/ceph
- If no cluster configuration is available, it will be bootstrapped. A lock mechanism is used to allow concurrent deployment of multiple hosts. In particular, for each keyring (mon, osd, admin, etc), if it exists, skip; otherwise create this keyring.

The idea is that when we deploy containers using ansible and we create ceph.conf from a template, we can still be able to allow config to bootstrap.

@leseb

**Comment by Ulexus** [comment]
I can wholeheartedly agree, that is a much better process.  I think the differences are less intentional design and more just not having gotten around to it.
