### ISSUE TITLE
coreos/units-etcd/ceph-osd@.service OSD_DEVICE setting

### ISSUE THREAD

**Issue by BenjaminThong** [ceph/ceph-docker#253]
hi, I'm having trouble getting ceph-osd running.

Filesystem     1K-blocks    Used Available Use% Mounted on
devtmpfs         1010908       0   1010908   0% /dev
tmpfs            1025884       0   1025884   0% /dev/shm
tmpfs            1025884     504   1025380   1% /run
tmpfs            1025884       0   1025884   0% /sys/fs/cgroup
/dev/xvda9      13833852 4080016   9141972  31% /
/dev/xvda3       1007760  542800    412944  57% /usr
/dev/xvda1        130798   36108     94690  28% /boot
tmpfs            1025884       0   1025884   0% /tmp
tmpfs            1025884       0   1025884   0% /media
/dev/xvda6        110576      60    101344   1% /usr/share/oem

when I try to launch the ceph-osd@.service without any modification (besides KV_PORT=2379), the error reports:

Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: Adding bootstrap keyrings
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: No bootstrapped OSDs found; trying ceph-disk
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: HEALTH_ERR 64 pgs stuck inactive; 64 pgs stuck unclean; no osds
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: INFO:ceph-disk:Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: INFO:ceph-disk:Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: INFO:ceph-disk:Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: Traceback (most recent call last):
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: File "/usr/sbin/ceph-disk", line 3636, in <module>
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: main(sys.argv[1:])
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: File "/usr/sbin/ceph-disk", line 3590, in main
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: args.func(args)
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: File "/usr/sbin/ceph-disk", line 1749, in main_prepare
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: raise Error('data path does not exist', args.data)
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal docker[18422]: **main**.Error: Error: data path does not exist: /dev/sdb
Apr 28 11:05:15 ip-172-16-1-218.ap-northeast-1.compute.internal systemd[1]: ceph-osd@1.service: Main process exited, code=exited, status=1/FAILURE

if I change OSD_DEVICE to /dev/xvda9, I get:

11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: Adding bootstrap keyrings
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: No bootstrapped OSDs found; trying ceph-disk
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: HEALTH_ERR 64 pgs stuck inactive; 64 pgs stuck unclean; no osds
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: INFO:ceph-disk:Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: INFO:ceph-disk:Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: INFO:ceph-disk:Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: Traceback (most recent call last):
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: File "/usr/sbin/ceph-disk", line 3636, in <module>
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: main(sys.argv[1:])
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: File "/usr/sbin/ceph-disk", line 3590, in main
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: args.func(args)
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: File "/usr/sbin/ceph-disk", line 1754, in main_prepare
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: verify_not_in_use(args.data, True)
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: File "/usr/sbin/ceph-disk", line 693, in verify_not_in_use
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: raise Error('Device is mounted', dev)
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25151]: **main**.Error: Error: Device is mounted: /dev/xvda9
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25252]: Error response from daemon: no such id: ceph-osd
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal docker[25252]: Error: failed to stop containers: [ceph-osd]
Apr 28 11:14:17 ip-172-16-1-218.ap-northeast-1.compute.internal systemd[1]: ceph-osd@1.service: Main process exited, code=exited, status=1/FAILURE

I've got the ceph-mon@.service running, but can't get the ceph-osd@.service working... is there any step I'm missing?

I'm on CoreOS Stable, etcd2, AWS EC2. I'm a regular programmer, not a sysadmin. Thank you for your patience :)

**Comment by leseb** [comment]
what's the docker command line?

**Comment by Ulexus** [comment]
The example `ceph-osd@.service` file uses the simple `osd` command.  It expects the directory corresponding to the instance id to be mounted to `/var/lib/ceph/osd/ceph-1` (using your example of `1` being your OSD ID and `ceph` being the cluster name, which is the default).  This is known as the "directory" method of starting an OSD.  If you wish to use a different method, you will want to change the unit to specify the method.

**Comment by Ulexus** [comment]
I forgot... it does fall through to attempting the disk method.  Disk method isn't likely to work, though, without also bind mounting the device in place, and probably other things, as well.
