### ISSUE TITLE
Add daemon for jewel

### ISSUE THREAD

**Issue by ivotron** [ceph/ceph-docker#254]
I have an experimental working version for `jewel` at https://github.com/ivotron/ceph-docker/tree/jewel . I've only tested this as a mon, osd and mds. This has only one commit https://github.com/ivotron/ceph-docker/commit/b072724935e23ad90ad56155cd250a6dc9de0d9c

**Comment by ivotron** [comment]
I have an experimental working version for `jewel` at https://github.com/ivotron/ceph-docker/tree/jewel . I've only tested this as a mon, osd and mds

**Comment by leseb** [comment]
Neat! Would you mind pushing a PR for this?

**Comment by ivotron** [comment]
Should this be against master or a new jewel branch?

**Comment by leseb** [comment]
New jewel branch please

**Comment by ivotron** [comment]
@leseb Oops, sorry, I can't push a new branch. Can you please create one and then I open a pull request against it? Or can I request a pull against `master` and then you merge it as a new `jewel` one? I've never done that, not sure if github has that feature

**Comment by leseb** [comment]
I see, I will do that tomorrow. I don't have my laptop with me at the moment.

**Comment by leseb** [comment]
@ivotron done!

**Comment by ivotron** [comment]
fixed by #255
