### ISSUE TITLE
Do not install packages in daemon/entrypoint

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#261]
We shouldn't have to install packages in from the Dockerfile of the daemon image.
I don't think we have any real reasons to do: https://github.com/ceph/ceph-docker/blob/master/daemon/Dockerfile#L12

**Comment by dmitryint** [comment]
runit need to do this: https://github.com/ceph/ceph-docker/blob/master/daemon/entrypoint.sh#L519

**Comment by leseb** [comment]
what do you mean? does runit need this or runit should be doing this?

**Comment by dmitryint** [comment]
Sorry. Runit is needed to run OSD in OSD_DISKS mode.

**Comment by leseb** [comment]
Ok but we can do the installation part in `ceph/base` instead right?

**Comment by dmitryint** [comment]
Yes, of course.
