### ISSUE TITLE
Can't find radosgw-agent

### ISSUE THREAD

**Issue by JrCs** [ceph/ceph-docker#267]
Hi,
can you add the radosgw-agent to the base image ?

**Comment by Ulexus** [comment]
It's not really a part of the ceph base daemon set.  It uses a separate configuration structure, and it isn't a core daemon.   Moreover, it is a tool for federating multiple ceph clusters, not for running a ceph cluster.  I don't think it should be in base.

Of course, it could be argued that python is already in the image and this is a fairly small set of python scripts...

That said, I don't see a reason not to provide it as a separate container.  Would you care to post a PR for it (Dockerfile + script/config) in a separate directory?

**Comment by JrCs** [comment]
It's ok if it is in another image other than the base.
I don't known well the radgosgw-agent to create a PR for the image. But i need one to federate multiple ceph clusters between WAN.
Do  you knows if we can sync DATA using radosgw-agent and not only the metadate like it said in the documentation ?

**Comment by Ulexus** [comment]
I know nothing of the script beyond what I can read on its Github page.

**Comment by ktdreyer** [comment]
My guess is that radosgw-agent will be retired as soon as Hammer itself goes EOL, and it would probably be better to focus on making jewel's RGW multi-site work smoothly.

**Comment by JrCs** [comment]
Yes jewel's RGW work great !
