### ISSUE TITLE
jewel OSD no longer starts

### ISSUE THREAD

**Issue by fmeppo** [ceph/ceph-docker#293]
Went to restart OSDs to the latest upstream jewel (rather than my fork), now that the dust is settling on the tree re-org.  ceph/daemon:tag-build-master-jewel-ubuntu-14.04 fails to start; the entrypoint logs:

sed: can't read /etc/confd/src/ceph.conf.toml.in: No such file or directory

**Comment by leseb** [comment]
@fmeppo shit, sorry about that. I'm going to merge #285 and then trigger the workflow script to generate new versions.
Sorry about that.

**Comment by leseb** [comment]
Just pushed everything, you can check the status here: https://hub.docker.com/r/ceph/daemon/builds/

**Comment by leseb** [comment]
I need to improve the CI to test the kv scenario

**Comment by fmeppo** [comment]
Are you going to backport this fix to all the other ceph-release
directories?  Because I just checked infernalis/ubuntu/14.04, and it's
broken (and I assume others are as well).

Also, it looks like there's an additional regression in infernalis - the
patches to ceph-disk aren't there, and neither is the uudecode stuff.  Did
the (obsolete) infernalis branch get pulled into the new master, rather
than what was previously in master?


--
Mike Shuey

**Comment by leseb** [comment]
To populate Infernalis I used the infernalis branch.
Sorry about that, would you mind doing a PR for the missing things?

**Comment by fmeppo** [comment]
I've moved our testbed up to Jewel, and it looks like all the pieces landed
there correctly.  There's about 6 months of infernalis changes that were
only in master, and not in the branch, and I'd rather not pull all of that
forward to something we aren't actively using anymore.  Is anyone out there
still trying to use ceph-docker's infernalis branch?  If so, I may be able
to start in on this, but if not I'd rather not be hacking on obsolete
code...



--
Mike Shuey

**Comment by leseb** [comment]
Fixed a couple of other issues, and re-pushed new branches.
If you're happy with Jewel, let's stick with it and deprecate other ceph versions.

**Comment by fmeppo** [comment]
Sounds good to me.  I'm quite pleased with Jewel - small file cephFS
performance is way up from Infernalis.

You can likely close this issue now.  Thanks!


--
Mike Shuey
