### ISSUE TITLE
Create new images with tags for ceph version

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#31]
We currently ship firefly as latest tag, we should move to giant and add a tag for firefly.

Next steps:
- [x] Create `firefly` branch in Github
- [x] Create `firefly` tag referencing that branch on Docker Hub
- [x] Update each `FROM` statements in `Dockerfile`s for downstream components in the `firefly` branch to reference `ceph/base:firefly`
- [x] Create `firefly` tags for each downstream component on Docker Hub
- [x] Create `giant` tags for each component on Docker Hub

**Comment by Ulexus** [comment]
I've got to run for a few hours; if it's not done before 20:00 UTC, I'll complete the last two steps here.

**Comment by leseb** [comment]
I don't think I'll have time to do this today.

**Comment by Ulexus** [comment]
No problem; I just wanted to make sure we didn't both work on it, since this was assigned to you at the time.

**Comment by Ulexus** [comment]
Giant tags on docker track the master branch, for now.
