### ISSUE TITLE
Document docker tag structure

### ISSUE THREAD

**Issue by KarlHerler** [ceph/ceph-docker#310]
It would be nice if e.g. the [ceph/daemon](https://github.com/ceph/ceph-docker/tree/master/ceph-releases/jewel/ubuntu/14.04/daemon) documentation would have a section about how the docker tags work.

Currently it is rather unclear which tag one should use, especially if `latest` is not sufficient (as of writing `latest` is an _infernalis_ build). As far as I understand the docker tag: `tag-build-master-jewel-ubuntu-14.04` is the actual recommended _jewel_ release tag, while the `jewel` tag seems to not be maintained.

Further, it is unclear if the `tag-build-master-*` builds the master git branch of ceph or if they use a released/tagged version.

**Comment by leseb** [comment]
I just created a new `latest` tag for base, daemon and demo that points to build-master-jewel-ubuntu-14.04.

Tags  named: `tag-build-master-*` are built from master.
