### ISSUE TITLE
Can't create OSD (CentOS 7)

### ISSUE THREAD

**Issue by russell-islam** [ceph/ceph-docker#319]
[root@ceph-client68 daemon]# docker logs 7893efa8e13c
static: does not generate config
HEALTH_OK
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
zap: Zapping partition table on /dev/sdc
command_check_call: Running command: /usr/sbin/sgdisk --zap-all -- /dev/sdc
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.

Warning! One or more CRCs don't match. You should repair the disk!

command_check_call: Running command: /usr/sbin/sgdisk --clear --mbrtogpt -- /dev/sdc

---

Caution: Found protective or hybrid MBR and corrupt GPT. Using GPT, but disk
verification and recovery are STRONGLY recommended.

---

GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
Creating new GPT entries.
The operation has completed successfully.
update_partition: Calling partprobe on zapped device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/sbin/partprobe /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
set_type: Will colocate journal with data on /dev/sdc
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
ptype_tobe_for_name: name = journal
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
create_partition: Creating journal partition num 2 size 100 on /dev/sdc
command_check_call: Running command: /usr/sbin/sgdisk --new=2:0:+100M --change-name=2:ceph journal --partition-guid=2:77881fce-e428-427c-97d3-455db688683b --typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106 --mbrtogpt -- /dev/sdc
update_partition: Calling partprobe on created device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
The operation has completed successfully.
command: Running command: /usr/sbin/partprobe /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc2 uuid path is /sys/dev/block/8:34/dm/uuid
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/77881fce-e428-427c-97d3-455db688683b
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/77881fce-e428-427c-97d3-455db688683b
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
set_data_partition: Creating osd partition on /dev/sdc
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
ptype_tobe_for_name: name = data
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
create_partition: Creating data partition num 1 size 0 on /dev/sdc
command_check_call: Running command: /usr/sbin/sgdisk --largest-new=1 --change-name=1:ceph data --partition-guid=1:1486385f-f345-47ad-b242-3f8b53a8ccba --typecode=1:89c57f98-2fe5-4dc0-89c1-f3ad0ceff2be --mbrtogpt -- /dev/sdc
update_partition: Calling partprobe on created device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command: Running command: /usr/sbin/partprobe /dev/sdc
The operation has completed successfully.
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc1 uuid path is /sys/dev/block/8:33/dm/uuid
populate_data_path_device: Creating xfs fs on /dev/sdc1
command_check_call: Running command: /usr/sbin/mkfs -t xfs -f -i size=2048 -- /dev/sdc1
meta-data=/dev/sdc1              isize=2048   agcount=4, agsize=1563853 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=0        finobt=0
data     =                       bsize=4096   blocks=6255411, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=0
log      =internal log           bsize=4096   blocks=3054, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
mount: Mounting /dev/sdc1 on /var/lib/ceph/tmp/mnt.aLb_BT with options noatime,inode64
command_check_call: Running command: /usr/bin/mount -t xfs -o noatime,inode64 -- /dev/sdc1 /var/lib/ceph/tmp/mnt.aLb_BT
command: Running command: /usr/sbin/restorecon /var/lib/ceph/tmp/mnt.aLb_BT
populate_data_path: Preparing osd data dir /var/lib/ceph/tmp/mnt.aLb_BT
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.aLb_BT/ceph_fsid.19425.tmp
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aLb_BT/ceph_fsid.19425.tmp
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.aLb_BT/fsid.19425.tmp
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aLb_BT/fsid.19425.tmp
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.aLb_BT/magic.19425.tmp
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aLb_BT/magic.19425.tmp
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.aLb_BT/journal_uuid.19425.tmp
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aLb_BT/journal_uuid.19425.tmp
adjust_symlink: Creating symlink /var/lib/ceph/tmp/mnt.aLb_BT/journal -> /dev/disk/by-partuuid/77881fce-e428-427c-97d3-455db688683b
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.aLb_BT
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aLb_BT
unmount: Unmounting /var/lib/ceph/tmp/mnt.aLb_BT
command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.aLb_BT
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
command_check_call: Running command: /usr/sbin/sgdisk --typecode=1:4fbd7e29-9d25-41b8-afd0-062c0ceff05d -- /dev/sdc
update_partition: Calling partprobe on prepared device /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
The operation has completed successfully.
command: Running command: /usr/sbin/partprobe /dev/sdc
command_check_call: Running command: /usr/bin/udevadm settle --timeout=600
command_check_call: Running command: /usr/bin/udevadm trigger --action=add --sysname-match sdc1
main_activate: path = /dev/sdc1
get_dm_uuid: get_dm_uuid /dev/sdc1 uuid path is /sys/dev/block/8:33/dm/uuid
command: Running command: /usr/sbin/blkid -o udev -p /dev/sdc1
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sdc1
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
mount: Mounting /dev/sdc1 on /var/lib/ceph/tmp/mnt.7DaUv_ with options noatime,inode64
command_check_call: Running command: /usr/bin/mount -t xfs -o noatime,inode64 -- /dev/sdc1 /var/lib/ceph/tmp/mnt.7DaUv_
command: Running command: /usr/sbin/restorecon /var/lib/ceph/tmp/mnt.7DaUv_
activate: Cluster uuid is 7d7507e6-bf6a-4a7f-8b65-a6b77add6d65
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
activate: Cluster name is ceph
activate: OSD uuid is 1486385f-f345-47ad-b242-3f8b53a8ccba
allocate_osd_id: Allocating OSD id...
command: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd create --concise 1486385f-f345-47ad-b242-3f8b53a8ccba
command: Running command: /usr/sbin/restorecon -R /var/lib/ceph/tmp/mnt.7DaUv_/whoami.19555.tmp
command: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.7DaUv_/whoami.19555.tmp
activate: OSD id is 1
activate: Initializing OSD...
command_check_call: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/tmp/mnt.7DaUv_/activate.monmap
got monmap epoch 1
command: Running command: /usr/bin/timeout 300 ceph-osd --cluster ceph --mkfs --mkkey -i 1 --monmap /var/lib/ceph/tmp/mnt.7DaUv_/activate.monmap --osd-data /var/lib/ceph/tmp/mnt.7DaUv_ --osd-journal /var/lib/ceph/tmp/mnt.7DaUv_/journal --osd-uuid 1486385f-f345-47ad-b242-3f8b53a8ccba --keyring /var/lib/ceph/tmp/mnt.7DaUv_/keyring --setuser ceph --setgroup disk
mount_activate: Failed to activate
unmount: Unmounting /var/lib/ceph/tmp/mnt.7DaUv_
command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.7DaUv_
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 4994, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 4945, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 3299, in main_activate
    reactivate=args.reactivate,
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 3056, in mount_activate
    (osd_id, cluster) = activate(path, activate_key_template, init)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 3232, in activate
    keyring=keyring,
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2725, in mkfs
    '--setgroup', get_ceph_group(),
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2672, in ceph_osd_mkfs
    raise Error('%s failed : %s' % (str(arguments), error))
ceph_disk.main.Error: Error: ['ceph-osd', '--cluster', 'ceph', '--mkfs', '--mkkey', '-i', '1', '--monmap', '/var/lib/ceph/tmp/mnt.7DaUv_/activate.monmap', '--osd-data', '/var/lib/ceph/tmp/mnt.7DaUv_', '--osd-journal', '/var/lib/ceph/tmp/mnt.7DaUv_/journal', '--osd-uuid', '1486385f-f345-47ad-b242-3f8b53a8ccba', '--keyring', '/var/lib/ceph/tmp/mnt.7DaUv_/keyring', '--setuser', 'ceph', '--setgroup', 'disk'] failed : 2016-06-27 18:33:12.209384 7fe36d94f800 -1 filestore(/var/lib/ceph/tmp/mnt.7DaUv_) mkjournal error creating journal on /var/lib/ceph/tmp/mnt.7DaUv_/journal: (2) No such file or directory
2016-06-27 18:33:12.209462 7fe36d94f800 -1 OSD::mkfs: ObjectStore::mkfs failed with error -2
2016-06-27 18:33:12.209521 7fe36d94f800 -1  *\* ERROR: error creating empty object store in /var/lib/ceph/tmp/mnt.7DaUv_: (2) No such file or directory

**Comment by russell-islam** [comment]
Command used to craete OSD:
sudo docker run -d --net=host --pid=host --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev/:/dev/ -e OSD_DEVICE=/dev/sdc -e OSD_FORCE_ZAP=1 ceph:tag-daemon osd_ceph_disk

**Comment by russell-islam** [comment]
@leseb Ca you take a look on this error?

**Comment by leseb** [comment]
hum `tag-daemon`  does not exist please use `tag-build-master-jewel-ubuntu-14.04`

**Comment by russell-islam** [comment]
I built the docker image using docker file so it is already there with the specified tag name.

**Comment by leseb** [comment]
I can't reproduce your issue, I suspect you have a problem with your drive.

**Comment by russell-islam** [comment]
I will try and update the output soon.
