### ISSUE TITLE
Ceph Restapi not using right configuration

### ISSUE THREAD

**Issue by JrCs** [ceph/ceph-docker#320]
HI,
i have try to change the restapi port whith the `RESTAPI_PORT` environment variable but it's not take into account.
After investigation in /entrypoint.sh we have:

``` bash
function start_restapi {
...
  # Check to see if we need to add a [client.restapi] section; add, if necessary
  if [[ ! "$(egrep "\[client.restapi\]" /etc/ceph/${CLUSTER}.conf)" ]]; then
    cat <<ENDHERE >>/etc/ceph/${CLUSTER}.conf

[client.restapi]
  public addr = ${RESTAPI_IP}:${RESTAPI_PORT}
  restapi base url = ${RESTAPI_BASE_URL}
  restapi log level = ${RESTAPI_LOG_LEVEL}
  log file = ${RESTAPI_LOG_FILE}
ENDHERE
  fi

  # start ceph-rest-api
  exec /usr/bin/ceph-rest-api ${CEPH_OPTS} -n client.admin
}
```

The `start_restapi` function create a `client.restapi` section if not exist with the right IP and Port.

 BUT in the `exec` line the program is start with the `-n client.admin` option.
 So ceph-rest-api will use the **client.admin** section (which doesn't exist if we use kvstore for example) and not the **client.restapi** section.
This result that the ceph-rest-api server will listen on the default port (5000) instead of the port defined by the `RESTAPI_PORT` environment variable.

**Comment by leseb** [comment]
Good catch, we need to create a dedicated key for the restapi user.
Would you mind getting a stab at this?

Thanks!

**Comment by JrCs** [comment]
I will try to create a PR for this (need to check how other keys are create and store automatically on kvstore).

**Comment by leseb** [comment]
Thanks @JrCs
