### ISSUE TITLE
restarting   docker ceph osd  container problem

### ISSUE THREAD

**Issue by aoreshkin** [ceph/ceph-docker#326]
I've created docker container for ceph osd server using such commands:

```
docker run -d --net=none --name="pnpi-osd1" --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /var/lib/ceph/pnpi-osd1:/var/lib/ceph/osd -v /dev/:/dev/ -e HOSTNAME="pnpi-osd1" -e OSD_DEVICE="/dev/sdq" -e OSD_FORCE_ZAP=1 -e OSD_TYPE=disk ceph/daemon osd
```
```
ovs-docker add-port br-public-1 eth0 pnpi-osd1 --ipaddress=10.10.2.2/24
ovs-docker add-port br-cluster-1 eth1 pnpi-osd1 --ipaddress=10.100.2.2/24
```

```
docker exec pnpi-osd1 ifconfig eth0 inet 10.10.2.2/24 broadcast 10.10.2.255
docker exec pnpi-osd1 ifconfig eth1 inet 10.100.2.2/24 broadcast 10.100.2.255
```

It works.

```
docker exec pnpi-mon ceph osd tree
shows
ID WEIGHT  TYPE NAME          UP/DOWN REWEIGHT PRIMARY-AFFINITY 
-1 7.28000 root default                                         
-2 3.64000     host pnpi-osd1                                   
 0 3.64000         osd.0           up  1.00000          1.00000 
-3 3.64000     host pnpi-osd2                                   
 2 3.64000         osd.2           up  1.00000          1.00000 
```

But if I reboot host or restart ceph osd container

```
docker stop pnpi-osd1
docker start pnpi-osd1
```

 then  disk /dev/sdq is reformatted again and data on disk is lost
See below extract from docker logs pnpi-osd1

```
command_check_call: Running command: /sbin/sgdisk --clear --mbrtogpt -- /dev/sdq
...
command_check_call: Running command: /sbin/sgdisk --zap-all -- /dev/sdq
...
populate_data_path_device: Creating xfs fs on /dev/sdq1
command_check_call: Running command: /sbin/mkfs -t xfs -f -i size=2048 -- /dev/sdq1
```

What is wrong ? What scenarios for creating ceph in docker could be proposed ?
Any help !

**Comment by leseb** [comment]
I cannot reproduce your issue, if I do: `docker restart bc8b79a566d4` it works and same goes for `docker stop bc8b79a566d4 ; docker start bc8b79a566d4`.

**Comment by aoreshkin** [comment]
I've tried another variant of ceph osd bootstrapping like this:

docker run -d --net=none --name="pnpi-osd3" --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /var/lib/ceph/pnpi-osd3:/var/lib/ceph/osd -v /dev/:/dev/ -e HOSTNAME="pnpi-osd3" -e OSD_DEVICE="/dev/sdu" -e OSD_FORCE_ZAP=1  ceph/daemon osd

The only difference is that I've not specified OSD_TYPE
And this variant works !
 After restarting osd container a disk is not reformatted.
extract from docker logs  pnpi-osd3:

Bootstrapped OSD(s) found; using /dev/sdu
main_activate: path = /dev/sdu1
...command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sdu1 /var/lib/ceph/tmp/mnt.AXEFex
activate: Cluster uuid is 837aaee6-5797-4543-b56d-ec067d925c41
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
activate: Cluster name is ceph
activate: OSD uuid is bc31078e-f788-45aa-ba45-dc4c5c3ede21
activate: OSD id is 1
...
start_daemon: Starting ceph osd.1...
command_check_call: Running command: /sbin/initctl emit --no-wait -- ceph-osd cluster=ceph id=1
...

However I don't uderstand why that happened.

**Comment by leseb** [comment]
https://github.com/ceph/ceph-docker/commit/e83dabdc936fc19dcf99417c8e980b42927efaf7
