### ISSUE TITLE
Ceph/daemon mon exiting (1) status

### ISSUE THREAD

**Issue by rahulraju93** [ceph/ceph-docker#329]
I have built the ceph/base and ceph/daemon Dockerfiles from fedora/jewel/24. When I try to start a monitor using, 

sudo docker run -d --net=host \
-v /etc/ceph:/etc/ceph \
-v /var/lib/ceph/:/var/lib/ceph/ \
-e MON_IP=192.168.0.20 \
-e CEPH_PUBLIC_NETWORK=192.168.0.0/24 \
ceph/daemon mon

I start the monitor but then it's status is exited (1) and it is not up. Why is this happening?

Please help and details about how to go about this smoothly would be great.

**Comment by font** [comment]
Could you share your docker container logs using the `docker logs CONTAINER` command? It may show some details about why it's failing.

**Comment by rahulraju93** [comment]
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into
/tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into
/tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into
/tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into
/tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
2016-07-08 17:30:08.416839 7f82c6d178c0 -1 unable to find any IP address in
networks: 192.168.0.0/24

These are my logs. I am able to create an osd using the ceph-disk option
for storage but it exits as well because of the following.

 [rtalari@ryu ~]$ sudo docker logs 5dea1abf85d6
static: does not generate config

How do I go about this properly?

1. I have pulled the ceph-docker repository from Github.
2. I have built the ceph/base and ceph/daemon DockerFiles to get the images.
3. I start running the daemon options such as mon and osd to set up a
cluster on a node.

Please explain in detail as it is for my research and I have deadlines
coming up.

Thank you





On Thu, Jul 7, 2016 at 5:13 PM, Ivan Font <notifications@github.com> wrote:

> Could you share your docker container logs using the docker logs CONTAINER
> command? It may show some details about why it's failing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ceph/ceph-docker/issues/329#issuecomment-231243771>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AP4jAdEixBnk3FaeIVhBCy60fz2M031Wks5qTZYbgaJpZM4JHit1>
> .
>



-- 
Rahul Talari
*University of Illinois Urbana Champaign - **Computer Engineering **|
University of California Santa Cruz - Computer Science | Alpha Tau Omega |
SSRC - UCSC *

**Comment by rahulraju93** [comment]
Hey, 
       Just curious if you got my email?

Thank you

**Comment by leseb** [comment]
@rahulraju93 your error is:

` unable to find any IP address in
networks: 192.168.0.0/24``

Please make sure that you are using the right subnet and IP.
