### ISSUE TITLE
ceph/daemon:latest tag no longer exists

### ISSUE THREAD

**Issue by erikh** [ceph/ceph-docker#330]
Not sure why, not in the automated build log either. Trying to provision containers with your latest ansible kit and can't seem to do it because of this.

Thanks for fighting the good fight. :)

**Comment by Ulexus** [comment]
See #278 and #310 

Basically, we don't know what to do about `latest` right now.  Choose an OS-and-release tag, and things will be safer for you, anyway.

**Comment by erikh** [comment]
ok, that makes a lot of sense WRT krbd and friends. Thanks for the heads up.

**Comment by leseb** [comment]
My bad I removed the tag `latest` yesterday, I just created one that points to build-master-jewel-ubuntu-14.04

**Comment by erikh** [comment]
thanks @leseb!
