### ISSUE TITLE
Add support for bluestore OSD

### ISSUE THREAD

**Issue by TimJones** [ceph/ceph-docker#351]
Can an option be added for an OSD to use a bluestore disk?
I understand that Bluestore is still a tech-preview, but being able to easily test it with the rapid build-up and tear-down of docker containers would be a huge plus.

**Comment by leseb** [comment]
Agree, will assign this to myself, expect this in the upcoming weeks or so.

**Comment by immesys** [comment]
Isn't this in now?

**Comment by TimJones** [comment]
Yes, looks like it was added with #352 if someone can test & confirm this can be closed.

**Comment by leseb** [comment]
@immesys yup should work, let me close this.
