### ISSUE TITLE
ceph_disk.main.Error: Error: No cluster conf found in /etc/ceph with fsid 00000000-0000-0000-0000-000000000000

### ISSUE THREAD

**Issue by pineking** [ceph/ceph-docker#355]
the cluster name :  ceph_tf 
use the etcd as the backend
the command is:
docker run -d --pid=host --net=host --privileged=true  -v /dev:/dev  -e CLUSTER=ceph_tf -e KV_TYPE=etcd -e OSD_TYPE=disk -e OSD_FORCE_ZAP=1 -e OSD_DEVICE=/dev/sdb ceph/daemon osd                 

the log is:

2016-08-12T14:21:03Z 00-25-90-c0-f7-ac confd[16656]: INFO Backend set to etcd
2016-08-12T14:21:03Z 00-25-90-c0-f7-ac confd[16656]: INFO Starting confd
2016-08-12T14:21:03Z 00-25-90-c0-f7-ac confd[16656]: INFO Backend nodes set to http://127.0.0.1:4001
2016-08-12T14:21:03Z 00-25-90-c0-f7-ac confd[16656]: INFO Target config /etc/ceph/ceph_tf.conf out of sync
2016-08-12T14:21:03Z 00-25-90-c0-f7-ac confd[16656]: INFO Target config /etc/ceph/ceph_tf.conf has been updated
Adding bootstrap keyrings
HEALTH_ERR 64 pgs are stuck inactive for more than 300 seconds; 64 pgs stuck inactive; no osds
It looks like /dev/sdb is an OSD, however OSD_FORCE_ZAP is enabled so we are zapping the device anyway
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
zap: Zapping partition table on /dev/sdb
command_check_call: Running command: /sbin/sgdisk --zap-all -- /dev/sdb
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.

Warning! One or more CRCs don't match. You should repair the disk!

****************************************************************************
Caution: Found protective or hybrid MBR and corrupt GPT. Using GPT, but disk
verification and recovery are STRONGLY recommended.

---

GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
command_check_call: Running command: /sbin/sgdisk --clear --mbrtogpt -- /dev/sdb
Creating new GPT entries.
The operation has completed successfully.
update_partition: Calling partprobe on zapped device /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
set_type: Will colocate journal with data on /dev/sdb
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
ptype_tobe_for_name: name = journal
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
create_partition: Creating journal partition num 2 size 5120 on /dev/sdb
command_check_call: Running command: /sbin/sgdisk --new=2:0:+5120M --change-name=2:ceph journal --partition-guid=2:d3c67b34-79e3-4151-a1bb-0ba7635bde1c --typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106 --mbrtogpt -- /dev/sdb
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb2 uuid path is /sys/dev/block/8:18/dm/uuid
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/d3c67b34-79e3-4151-a1bb-0ba7635bde1c
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/d3c67b34-79e3-4151-a1bb-0ba7635bde1c
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
set_data_partition: Creating osd partition on /dev/sdb
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
ptype_tobe_for_name: name = data
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
create_partition: Creating data partition num 1 size 0 on /dev/sdb
command_check_call: Running command: /sbin/sgdisk --largest-new=1 --change-name=1:ceph data --partition-guid=1:dc6f57d4-65b4-4982-9499-a0d721db6f63 --typecode=1:89c57f98-2fe5-4dc0-89c1-f3ad0ceff2be --mbrtogpt -- /dev/sdb
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb1 uuid path is /sys/dev/block/8:17/dm/uuid
populate_data_path_device: Creating xfs fs on /dev/sdb1
command_check_call: Running command: /sbin/mkfs -t xfs -f -i size=2048 -- /dev/sdb1
meta-data=/dev/sdb1              isize=2048   agcount=4, agsize=60719917 blks
         =                       sectsz=512   attr=2, projid32bit=0
data     =                       bsize=4096   blocks=242879665, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0
log      =internal log           bsize=4096   blocks=118593, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
mount: Mounting /dev/sdb1 on /var/lib/ceph/tmp/mnt.MSP8x0 with options noatime,inode64
command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sdb1 /var/lib/ceph/tmp/mnt.MSP8x0
populate_data_path: Preparing osd data dir /var/lib/ceph/tmp/mnt.MSP8x0
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.MSP8x0/ceph_fsid.16757.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.MSP8x0/fsid.16757.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.MSP8x0/magic.16757.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.MSP8x0/journal_uuid.16757.tmp
adjust_symlink: Creating symlink /var/lib/ceph/tmp/mnt.MSP8x0/journal -> /dev/disk/by-partuuid/d3c67b34-79e3-4151-a1bb-0ba7635bde1c
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.MSP8x0
unmount: Unmounting /var/lib/ceph/tmp/mnt.MSP8x0
command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.MSP8x0
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
command_check_call: Running command: /sbin/sgdisk --typecode=1:4fbd7e29-9d25-41b8-afd0-062c0ceff05d -- /dev/sdb
The operation has completed successfully.
update_partition: Calling partprobe on prepared device /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command_check_call: Running command: /sbin/udevadm trigger --action=add --sysname-match sdb1
main_activate: path = /dev/sdb1
get_dm_uuid: get_dm_uuid /dev/sdb1 uuid path is /sys/dev/block/8:17/dm/uuid
command: Running command: /sbin/blkid -o udev -p /dev/sdb1
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sdb1
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
mount: Mounting /dev/sdb1 on /var/lib/ceph/tmp/mnt.9ayXOd with options noatime,inode64
command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sdb1 /var/lib/ceph/tmp/mnt.9ayXOd
activate: Cluster uuid is 00000000-0000-0000-0000-000000000000
command: Running command: /usr/bin/ceph-osd --cluster=ceph_tf --show-config-value=fsid
mount_activate: Failed to activate
unmount: Unmounting /var/lib/ceph/tmp/mnt.9ayXOd
command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.9ayXOd
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4994, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4945, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3299, in main_activate
    reactivate=args.reactivate,
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3056, in mount_activate
    (osd_id, cluster) = activate(path, activate_key_template, init)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3203, in activate
    ' with fsid %s' % ceph_fsid)
ceph_disk.main.Error: Error: No cluster conf found in /etc/ceph with fsid 00000000-0000-0000-0000-000000000000

**Comment by pineking** [comment]
I found there is a file named "ceph_fsid" in /dev/sdb1 , and this file contains a string with all zero "00000000-0000-0000-0000-000000000000".  change this string to the correct fsid, and restart the osd daemon, fix the problem.

**Comment by leseb** [comment]
the string shouldn't be filled with 0... are you able to reproduce this everytime?
