### ISSUE TITLE
KV clusters do not work

### ISSUE THREAD

**Issue by immesys** [ceph/ceph-docker#357]
#349 broke clusters using a KV store.

During bootstrap in get_mon_config in config.kv , `/etc/ceph/monmap` is created. Then immediately afterwards, entrypoint dies because it expects `/etc/ceph/monmap-$CLUSTER`

**Comment by danielin917** [comment]
Pull request has been submitted

**Comment by linekin** [comment]
k8s cluster is also broken due to the same cause.
config.k8s.sh should also be fixed.

**Comment by immesys** [comment]
Fix PR is pending, just waiting for feedback on if hammer/infernalis should receive changes or not

**Comment by immesys** [comment]
I believe this was fixed by #359
