### ISSUE TITLE
entrypoint: mixup between osd processes

### ISSUE THREAD

**Issue by immesys** [ceph/ceph-docker#358]
Towards the end of the osd activation ([here](https://github.com/ceph/ceph-docker/blob/492fe894430c1eb53bcc98bd858ed8598dc6ad3e/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L553)) the entrypoint script attempts to get the PID of the recently launched ceph osd process. 

The problem is that the filter here is too general. The recommended docker incantation for starting the daemon includes --pid=host which means that ps gives all the processes. This can lead to multiple PIDs matching, which crashes the test below with 

```
/entrypoint.sh: line 556: [: too many arguments
```

I happened to hit this because my docker --name matched my unit (which was ceph-osd-0.service) and I was also be running journalctl -f on the unit, so there were three processes that matched.

I imagine though that people could also hit this with osd.1 clashing with osd.10 etc.

I'm a little overworked atm so I can't PR this any time soon.

**Comment by leseb** [comment]
I'm not that good with regex, what about something like this to quickly solve your issue and only stick with the OSD_ID?

`ps -ef | grep [c]eph-osd test | egrep "\-i ${OSD_ID} \-\-setuser"`

**Comment by immesys** [comment]
I think that would work. I'll test it out and submit a PR today if it works (as it happens I need to rebuild and test for #347 anyway)

**Comment by leseb** [comment]
Great thanks :) waiting for the PR then.

**Comment by immesys** [comment]
This is tracked by #362
