### ISSUE TITLE
Can't run ceph/config

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#36]
On a CoreOS host I run:

core@coreos ~ $ etcdctl ls
/coreos.com

docker run --net=host -e ETCDCTL_PEERS=http://192.168.0.20:4001 -e MON_IP=192.168.0.20 -e MON_NAME=etcdmon -e CLUSTER=ceph -v /etc/ceph:/etc/ceph ceph/config
Configuration found for cluster ceph. Writing to disk.
Error:  100: Key not found (/ceph-config/ceph/ceph.conf) [30]

Not sure why the script believes that /ceph-config/ceph/done exists...
Tried to dig a bit but without much luck.

@Ulexus did you get a chance to test that new container?

**Comment by Ulexus** [comment]
@leseb  I haven't no.  I built and ran it just to make sure it was clean, but I haven't tested it.  Not sure when I'll have time for that.

It looks like the `if` on line 33 is failing.  It should probably be rewritten to check the return code.  I'm going to guess it's seeing the output from `stderr` and thinking that the key exists.  Checking for the retcode to be 0 should be safer.

**Comment by Ulexus** [comment]
@leseb Do you want to see if PR #38 fixes this for you?

**Comment by leseb** [comment]
It does fix it.
