### ISSUE TITLE
Documentation for Docker image generation

### ISSUE THREAD

**Issue by gbraad** [ceph/ceph-docker#366]
Although this should be very extensive, I am missing the documentation that refers to the image generation...

Since symlinks are used, the build process can fail by not resolving the file `entrypoint.sh`. The build can succeed if called as follows:

```
$ cd ceph-releases/jewel/fedora/24/base
$ tar -czh . | docker build -t jewel-base-f24 -
```

Adding a topic to the README? Just let me know...

**Comment by immesys** [comment]
In the readme it tells you how to init the dev environment for a specific version of Ceph and Linux distribution. I've never had that process fail to link entrypoint.sh. Can you tell us the commands you are running?

**Comment by gbraad** [comment]
You are referring to: https://github.com/ceph/ceph-docker#prepare-your-development-environment, and `generate-dev-env.sh`. (TBH, I hadn't noticed this file) *facepalm*...  however, is this really needed?

When a normal build is done
```
$ cd ceph-docker/ceph-releases/jewel/fedora/24/base
$ docker build -t jewel-base-f24 .
```

it would fail with: 
```
Step 15 : ADD entrypoint.sh /entrypoint.sh
lstat entrypoint.sh: no such file or directory
```
as the symlink will not be resolved. This is due to Docker.

However, doing:

```
$ cd ceph-releases/jewel/fedora/24/base
$ tar -czh . | docker build -t jewel-base-f24 -
```

will have the same effect dealing with the symlinks, as the tar command will resolve them.

**Comment by leseb** [comment]
@gbraad not sure what to say, yes the `tar` command does the job too :).
`generate-dev-env.sh` will resolve all the symlinks by itself.
