### ISSUE TITLE
Question: Specific osd numbers

### ISSUE THREAD

**Issue by immesys** [ceph/ceph-docker#368]
I am aware this is tricky, but would it be possible to prepare an osd with a specific osd id?

My use case is in speeding up automated cluster installations. At present my process is:
- start all the mons
- zap all the disks
- generate systemd unit files for each osd, named osd-(num) 
- start them one by one, waiting for each one to be allocated an id and appear in ceph osd tree. This sequential start of 100 osds waiting 10 sec between each one is a bit tedious.

Doing this allows me to have osd numbers match the unit file name and roughly match disk numbers. It's important for me that if my users see osd.16 is funky they can say 'systemctl stop osd-16' and maybe have an easy to decipher mapping of osd to server and disk tray

I understand that ceph common practice is not to be picky about your osd ids, and as you fault and replace drives these evolve, so I am not set on the id to disk tray relationship, but the unit file to id is important.

How are other people getting around this problem?

**Comment by leseb** [comment]
We can not force the ID of an OSD since the allocation happens incrementally, starting from 0 to N.
I think in most cases people don't care about ID mappings since this will get messed up after your first failure.

**Comment by immesys** [comment]
Yeah, so I am willing to give up on having the OSD have a specific ID, but is there some way I can fix what the ID of the disk will be (whatever that ID may be) faster than just starting the service?

Ideally what I would like, and I think this still fits ceph dont-care-about-osd-id best practice, is:

- zap all N disks in parallel (you already did work to support that, thanks!)
- allocate N osd IDs whatever they may be
- start the services, all in parallel, knowing they will have specific IDs.

At the moment I think my best bet is start all N osds. Stop them. Inspect their IDs and rename the unit files, but that seems a little ugly.

**Comment by immesys** [comment]
I'll close this for now. It's not particularly important.

**Comment by leseb** [comment]
@immesys sorry I was on PTO, so I'm slowly catching up.
You can determine the osd ID your disk will get if you do:

`ceph osd create $partuuid`

You will always get the same number.
Does that help?

**Comment by immesys** [comment]
Yeah, thanks. That does help
