### ISSUE TITLE
ipv6 and CEPH_PUBLIC_NETWORK ceph/daemon startup failure

### ISSUE THREAD

**Issue by coffeepac** [ceph/ceph-docker#369]
When the entrypoint.sh script finds an ipv6 MON_IP it does not set CEPH_PUBLIC_NETWORK (https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L214).  At this point, MON_IP is set to an ipv6 address and the code then jumps to the MON_IP and CEPH_PUBLIC_NETWORK test (https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L236),  CEPH_PUBLIC_NETWORK is empty at this point.  

I am uncertain what the networking needs of ceph are when using ipv6.  However, I was able to get the ceph cluster running and a HEALTH_OK from a 'ceph -s' executed against a mon pod by adding the following block to the mon deployment yaml:

```
            - name: CEPH_PUBLIC_NETWORK
              value: 10.244.0.0/16
```

I believe the answer is either:
- modify the check to not check for CEPH_PUBLIC_NETWORK when MON_IP is an ipv6 address
- set CEPH_PUBLIC_NETWORK to something meaningful when an ipv6 address is used

Kubernetes version:  1.3.6
OS: CoreOS v1122.1.0 (Beta Channel)

**Comment by leseb** [comment]
I think we need to set the proper ipv6 subnet, I suspect something like this should work:

`ip -6 r | grep $NIC_MORE_TRAFFIC  | awk '{ print $1}'`

**Comment by coffeepac** [comment]
sure, where should I drop that line?  right after the ipv6 assignment, line 214?

**Comment by leseb** [comment]
@coffeepac yup, quickly pushed this: https://github.com/ceph/ceph-docker/pull/379

**Comment by coffeepac** [comment]
rad.  I'll start this now.  will take ~2 hours.  got other things to handle as well.

**Comment by leseb** [comment]
yeah no worries, I was on PTO last week, so I'm slowly cashing up :)

**Comment by coffeepac** [comment]
Tried it out and it works just fine.  I'll close this when 379 is merged.

**Comment by leseb** [comment]
Thanks for testing @coffeepac
