### ISSUE TITLE
OSD entrypoint script exits when pgrep fails

### ISSUE THREAD

**Issue by csainty** [ceph/ceph-docker#370]
I'm trying to get some OSDs up and running on CoreOS. They fail when I try to run `activate` and I believe the `entrypoint.sh` script has a small bug.

```
Sep 06 08:33:41 test-storage-001 docker[15543]: create-or-move updated item name 'osd.0' weight 0.01 at location {host=test-storage-001,root=default} to crush map
Sep 06 08:33:41 test-storage-001 systemd[1]: ceph-osd.service: Main process exited, code=exited, status=1/FAILURE
```

https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L556

When the entrypoint script reaches that line it is aborting, I assume because `pgrep` exits with status 1 when there are no result.

```
root@test-storage-001:/# pgrep -U ceph -f "^/usr/bin/ceph-osd \-\-cluster ceph.*\-i 0 \-\-setuser"
root@test-storage-001:/# echo $?
1
```

When I patch in a hacked script that skips the check and just runs the `else` case, the OSD starts as expected.

**Comment by csainty** [comment]
Looks related to #362

Running the previous command does not exit with a 1.

```
root@test-storage-001:/# ps -ef |grep ceph-osd |grep osd.0 |awk '{print $2}'
root@test-storage-001:/# echo $?
0
```

**Comment by immesys** [comment]
Oops. This is my bad. I'll try reproduce and fix. For completeness, what is the docker command line being run?

**Comment by immesys** [comment]
Eugh. My bad. I'm sorry. I had accidentally removed the set -e when testing. Much embarrass.
