### ISSUE TITLE
Runit exits with status 127

### ISSUE THREAD

**Issue by ganeshmaharaj** [ceph/ceph-docker#381]
With the latest master, using fedora 24 images, not able to start osd and it exits with 
```
*** Booting runit daemon...
*** Runit started as PID 20
*** Runit exited with status 127
sh: /usr/bin/sv: No such file or directory
sh: /usr/bin/sv: No such file or directory
*** Killing all processes...
```

I see fixes #334 and #336, but seems like fedora 24 base image does not seem to have runit included in it.

**Comment by leseb** [comment]
Indeed, f24 doesn't support directory mode.
If you don't have any strong requirements in terms of distro (some of us do due to their companies affiliations) I'd recommend to go with an Ubuntu image :).

Thanks!

**Comment by ganeshmaharaj** [comment]
Definitely no strong requirements, but more of the OSD choosing to fix it given that we are supporting that container base :)

**Comment by leseb** [comment]
Sure ;)
