### ISSUE TITLE
10.2.3 images

### ISSUE THREAD

**Issue by hunter** [ceph/ceph-docker#387]
It's been a week or two since the Jewel docker images were built. They're missing a few of the latest repo changes along with 10.2.3 which was released yesterday. Any chance we can get a new build?

Also, Is there a better way to request an image update rather than file a new ticket? Would like to keep noise to a minimum :)

**Comment by leseb** [comment]
Yup, sorry for the delay. I just triggered a build.

**Comment by hunter** [comment]
Thanks @leseb. It seems that the Ubuntu images for Jewel missed out on getting that update?

**Comment by leseb** [comment]
Hum let me look into that.

**Comment by leseb** [comment]
Should be good now :)

**Comment by ktdreyer** [comment]
What was the exact problem?
