### ISSUE TITLE
"docker stop" requires at least 1 argument(s).

### ISSUE THREAD

**Issue by iliul** [ceph/ceph-docker#396]
root@vultr:~/ceph-docker# sudo ./travis-builds/purge_cluster.sh
"docker stop" requires at least 1 argument(s).
See 'docker stop --help'.

Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]

Stop one or more running containers

**Comment by leseb** [comment]
Yes I noticed, however I think it's harmless.
Perhaps you can check if there are any containers running, if not we skip this?
