### ISSUE TITLE
add a "marking" string at the end of all entrypoint scripts

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-docker#399]
The docker API does not block waiting on an entry script being fully executed, this causes an issue when trying to bring up a container, docker reporting that the container is running correctly, then the entry point script runs and detects some input is invalid and breaks the container.

That scenario is impossible to deal with programmatically, because we don't know how long will the entry script will take to complete, and nothing in the Docker API tells us that the entry point script is being executed (or at what point of execution it is).

Since we do get access to `stderr` and `stdout` when starting a container, we can easily check for a string at the very end of the entry point script. Something like:

    SUCCESS

As the very last line would work.

**Comment by font** [comment]
In the success path, the entrypoint script typically execs into a ceph daemon so we'd have to print the SUCCESS before that happens. This means that there is still an opportunity for the container to fail if the ceph daemon fails independently.

**Comment by leseb** [comment]
+1 for @font's comment. The actual "success" is a running process.

**Comment by alfredodeza** [comment]
If running the ceph daemon is indicative of having been able to accept input and work with it, that sounds like a good spot to indicate success of the bootstrap script.

It is acceptable if the ceph process dies later for whatever other reason (tests would be able to pick that up later).

Something like this would be great:

    # entrypoint completed
    echo "SUCCESS"

    exec ceph ${CEPH_OPTS} -w

**Comment by leseb** [comment]
What about for a mon, replacing the following line: https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L278

With`exec echo "SUCCESS" && exec /usr/bin/ceph-mon ${CEPH_OPTS} -d -i ${MON_NAME} --public-addr "${MON_IP}:6789" --setuser ceph --setgroup ceph``

Thoughts? @font?

**Comment by leseb** [comment]
Alright, after thoughts, @alfredodeza's solution by putting an `echo` before running the `exec` is fine, no need for my `exec echo ... && ceph-mon` etc.

**Comment by alfredodeza** [comment]
Yep, I am OK with the actual ceph process failing for whatever reason. I just need validation that the entrypoint succeeded. Thanks @leseb !

**Comment by leseb** [comment]
That makes me thing that entry points are too silent and they are hard to debug so after adding the SUCCESS we can potentially start to add some log info. Waiting for your PR :)
