### ISSUE TITLE
entrypoint for  ceph/daemon:tag-build-master-jewel-fedora-23 fails

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-docker#400]
While running some tests:

    [ERROR][setup] failed to setup container for ceph/daemon:tag-build-master-jewel-fedora-23
    [ERROR][setup] creating /etc/ceph/ceph.client.admin.keyring
    [ERROR][setup] creating /etc/ceph/ceph.mon.keyring
    [ERROR][setup] chown: invalid user: 'ceph.'

**Comment by leseb** [comment]
hum weird, could it be that Fedora 24 doesn't have Jewel? I though it had. Let me check.

**Comment by leseb** [comment]
Alright, somehow f23 has `ceph version 0.94.7 (d56bdf93ced6b80b07397d57e3fa68fe68304432)`

That's the issue.

**Comment by leseb** [comment]
What's really weird is that the tag should not exist so let me remove it.

**Comment by leseb** [comment]
Just removed the tag, we only want to keep f24 for Jewel, nice catch @alfredodeza I think this one was a leftover from an old attempt.
