### ISSUE TITLE
{config,rados,rbd}/Dockerfile refers to "monitor", executes "/usr/bin/rados"

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-docker#402]
I assume it's just a boilerplate error, although I'm truly not sure about config/

**Comment by leseb** [comment]
Focus should be kept on everything inside `ceph-releases`, the other images are not maintained anymore.

**Comment by dmick** [comment]
It would avoid losing time if it weren't in the repo, or were in an "unmaintained" subdir.  Dead code is dead.

**Comment by ktdreyer** [comment]
Agreed, we should delete it if it's not maintained

**Comment by leseb** [comment]
Alright I'll create an UNMAINTAINED ANYMORE directory and move everything.
