### ISSUE TITLE
Create RBD Failed

### ISSUE THREAD

**Issue by Henryballs** [ceph/ceph-docker#411]
I just deployed the cepy cluster and the status is HEALTH_OK. But when I tried to create  a RBD images, command return an error message which is librbd: error setting image id: (95) Operation not supported after I created a pool.

here is the error detail:
root@Client-04:/# rbd create dpool/dimage --size 10240
2016-10-28 01:56:55.920752 7ff2659ffd40 -1 librbd: error setting image id: (95) Operation not supported
rbd: create error: (95) Operation not supported

the pool info is:
root@Client-04:/usr/lib/x86_64-linux-gnu# ceph osd dump |grep pool
pool 2 'dpool0' replicated size 2 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 128 pgp_num 128 last_change 49 flags hashpspool stripe_width 0

I think it may cause by missed some rbd lib files, but I'm not sure.

Do you know what's the root cause and how to fix it?

Thanks so much!

**Comment by leseb** [comment]
Hum you tried to create an image on the pool `dpool` where the pool seems to be named `dpool0`.
