### ISSUE TITLE
Multi node cluser

### ISSUE THREAD

**Issue by russell-islam** [ceph/ceph-docker#412]
I can create single node cluster but not multi node. May be I am missing the distribution of conf/keyring to other nodes. I followed the youtube video but did not understand the 3-copy.sh and 3-restore script.
If anyone has the detailed steps please share. Thanks.  
FYI: I am suing redhat 7.2.

**Comment by leseb** [comment]
Copy and restore just copy `/var/lib/ceph/bootstrap-*`, `/etc/ceph/*` on all the nodes.
