### ISSUE TITLE
all containers need to be re-published

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-docker#415]
So that they include the `SUCCESS` marker introduced by PR #408 

Otherwise the container testing cannot make use of this and will still have to call `sleep(0.5)` to wait for the `entrypoint.sh` script to complete

**Comment by leseb** [comment]
Hum I pushed a new version this morning so the current image should have all the recent changes. Can you test again and make sure you have the latest image?

Thanks!

**Comment by alfredodeza** [comment]
I only see this working for Jewel containers. Not Hammer. Is that correct?

**Comment by font** [comment]
It looks like all the container images (Jewel, Hammer, Infernalis) were updated except for `tag-build-master-hammer-centos-7`.

https://hub.docker.com/r/ceph/daemon/tags/

**Comment by leseb** [comment]
@font https://github.com/ceph/ceph-docker/pull/424 should fix the build.
