### ISSUE TITLE
Project licensing

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#416]
Hi @Ulexus 

Our current license is MIT, which seems to prevent us from being used by other projects such as OpenStack Kolla (containerized OpenStack services).

Ideally we would move from MIT to Apache. Is it a problem for you?
Thanks!

**Comment by Ulexus** [comment]
Not at all.  That's fine with me.

**Comment by Ulexus** [comment]
Odd that a more permissive license is not allowed... but I'm perfectly fine with an Apache license.

**Comment by Ulexus** [comment]
For that matter, I don't really think I have much right to continue to hold the exclusive license.  I haven't been much involved in quite some time, and there have been a lot of changes and updates.   I doubt there's much left of what I originally wrote, anyway.

**Comment by leseb** [comment]
Argh don't say that! There are many valuable contributions from you at the very core of the current images :).

Thanks for your consent.

**Comment by leseb** [comment]
@Ulexus FYI https://github.com/ceph/ceph-docker/blob/master/LICENSE#L189-L190

**Comment by v1k0d3n** [comment]
hey guys, sorry to continue the discussion, but I'm wondering if...since _Ceph itself is GPL licensed_...if we're _still_ not going to have the same issues?

**Comment by leseb** [comment]
@v1k0d3n no bloody idea. I suspect this won't be an issue otherwise we wouldn't have tools integrating Ceph to deploy OpenStack but I might be wrong.
