### ISSUE TITLE
Hammer CentOS 7 image missing /etc/ceph/monmap-ceph

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-docker#418]
__ TestHammer.test_monmap_exists[ceph/daemon:tag-build-master-hammer-centos-7] __
    
    self = <test_monitors.TestHammer object at 0x7fc974175c90>, hammer_containers = {'Id': '534523c4e9b8d35a5bba089dfb5e8979103a7807b9c23b4deadd0bbb1eb9467f', 'Warnings': None}
    client = <docker.client.Client object at 0x7fc97424d090>
    
        def test_monmap_exists(self, hammer_containers, client):
            command = client.exec_create(hammer_containers, cmd='stat /etc/ceph/monmap-ceph')
            result = client.exec_start(command)
            if client.exec_inspect(command)['ExitCode'] != 0:
    >           raise AssertionError(result)
    E           AssertionError: stat: cannot stat '/etc/ceph/monmap-ceph': No such file or directory
    
    base/test_monitors.py:63: AssertionError

Both 14.04 and 16.06 have monmap-ceph:

    base/test_monitors.py::TestHammer::test_monmap_exists[ceph/daemon:tag-build-master-hammer-ubuntu-16.04] PASSED
    base/test_monitors.py::TestHammer::test_monmap_exists[ceph/daemon:tag-build-master-hammer-ubuntu-14.04] PASSED

**Comment by leseb** [comment]
The problem is that the image hasn't been updated for a while and the name of the monmap is still `monmap`, let me fix the build for that image.

**Comment by leseb** [comment]
Just updates the image, let's see if it builds this time.

**Comment by leseb** [comment]
The build succeeds now.

**Comment by leseb** [comment]
@alfredodeza can you test if we have the right file now? Thanks!
