### ISSUE TITLE
Jewel Fedora 24 missing /etc/ceph/ceph.monmap

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-docker#419]
Similar to issue #418 there are no monmap files for Jewel Fedora 24 on the daemon image:

    __ TestJewel.test_monmap_exists[ceph/daemon:tag-build-master-jewel-fedora-24] __
    
    self = <test_monitors.TestJewel object at 0x7fc974116590>, jewel_containers = {'Id': '822ccb18c94a705745d1760603809c50e93d3c534166cf33cc8946be65b08e53', 'Warnings': None}
    client = <docker.client.Client object at 0x7fc97424d090>
    
        def test_monmap_exists(self, jewel_containers, client):
            command = client.exec_create(jewel_containers, cmd='stat /etc/ceph/ceph.monmap')
            result = client.exec_start(command)
            if client.exec_inspect(command)['ExitCode'] != 0:
    >           raise AssertionError(result)
    E           AssertionError: stat: cannot stat '/etc/ceph/ceph.monmap': No such file or directory
    
    base/test_monitors.py:47: AssertionError

**Comment by font** [comment]
@alfredodeza This appears to be the same issue you reported in #422.

**Comment by leseb** [comment]
@alfredodeza why are you testing `/etc/ceph/ceph.monmap` instead of `/etc/ceph/monmap-ceph`?
