### ISSUE TITLE
ceph images in error state

### ISSUE THREAD

**Issue by CoRfr** [ceph/ceph-docker#42]
https://registry.hub.docker.com/u/ceph/config/builds_history/151300/

Not sure why, but:
buh82pyfb6yjciwqaspwweb	Error	2015-03-05 00:06:05	2015-03-05 00:17:02

Could someone retrigger the build and/or fix the issue ?

Thanks

**Comment by Ulexus** [comment]
They build cleanly for me; not sure why they failed there, but I've kicked off another build, and I'll watch it.

**Comment by Ulexus** [comment]
That worked, so I'm guessing it was a transient Docker Hub issue.

**Comment by Ulexus** [comment]
Thanks for the heads-up, though.  I really wish Docker Hub would get some sort of alert system in place.
