### ISSUE TITLE
CentOS and RHEL containers differ

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-docker#447]
`diff -u ceph-releases/jewel/centos/7 ceph-releases/jewel/redhat/7.2/`

We are building our CI system around testing with the CentOS image, but the RHEL 7 image does not align with the CentOS image.

The two should be completely aligned.

**Comment by leseb** [comment]
@ktdreyer you're right Ken, my concern is that some components/packages from this repo won't be allowed/supported by Red Hat so we need to establish a clear strategy...

**Comment by ktdreyer** [comment]
Would you please go over the diff and provide details for why we need each of the extra items in the CentOS containers that are not in the RHEL containers?

We can take that analysis and figure out which extra packages we should provide in the RHEL environment, and which extra packages we can just drop from CentOS.

**Comment by leseb** [comment]
Sure, will do.

**Comment by dmick** [comment]
I see the differences still exist.  What is the plan to reconcile these?  are confd and forego required or not?  If not, why are they in the centos image?

**Comment by leseb** [comment]
The content is the same, only the `Dockerfile` is different (which is normal). To disable scenarios we have a simple file here: https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/rhel/7.3/daemon/disabled_scenario. This file disables unwanted/unsupported scenarios for RHEL.
