### ISSUE TITLE
Need to specify OSD_ID using "prepare" disk option

### ISSUE THREAD

**Issue by bzub** [ceph/ceph-docker#482]
The prepare OSD_TYPE option works great when all disks are on one host in a cluster.  I'm using kubernetes and when I start using this option on a second host it starts over with osd IDs at 0, and reuses that ID for a different daemon/disk.

It would be great if the OSD_ID could be given to the entrypoint script, or if it could pick up on a naming convention like the directory option does.

**Comment by leseb** [comment]
Just to be clear.
Are you saying you are getting conflicting OSD IDs when using `osd_disk_prepare` scenario?

**Comment by bzub** [comment]
That's correct.  Conflicting OSD IDs when I start OSDs on two or more hosts.

I'd get logs but currently I'm having other issues with OSD_TYPE=prepare where the OSD containers keep restarting after what looks like a successful zap of the drives.  Need to see what the root cause of all this is, I'll try to find it.
