### ISSUE TITLE
CEPH_PUBLIC_NETWORK hard coded to 192.168...?

### ISSUE THREAD

**Issue by gator1** [ceph/ceph-docker#484]
I tried to set ceph up on my Ubuntu 16.04.1 LTS

Here is what I got and the docker container is not running after the complain. My network is in 10.142.20.xxx. 

Does this somehow hard code to 192.168?

gary@fw0012189:~$ sudo docker run --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph/ -e MON_IP=10.145.82.20 -e CEPH_NETWORK=10.145.82.0/24 ceph/daemon mon
2017-02-11 02:30:17  /entrypoint.sh: ERROR- CEPH_PUBLIC_NETWORK must be defined as the name of the network for the OSDs
gary@fw0012189:~$ sudo docker run --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph/ -e MON_IP=10.145.82.20 -e CEPH_NETWORK=10.145.82.0/24 -e CEPH_PUBLIC_NETWORK=10.145.82.0/24 ceph/daemon mon
creating /var/lib/ceph/bootstrap-osd/ceph.keyring
creating /var/lib/ceph/bootstrap-mds/ceph.keyring
creating /var/lib/ceph/bootstrap-rgw/ceph.keyring
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /tmp/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
2017-02-11 02:31:25.894638 7f6944149840 -1 unable to find any IP address in networks: 192.168.0.0/24
gary@fw0012189:~$

**Comment by leseb** [comment]
`CEPH_NETWORK` variable does not exist. Just use `CEPH_PUBLIC_NETWORK`.
We do not hardcode anything.
Are you sure that there is no leftover in `/etc/ceph`?

**Comment by gator1** [comment]
"Commonly, you will want to bind-mount your host's /etc/ceph into the container. "

What should be the content of host's /etc/ceph? I have an empty directory since I don't have ceph on my host; I am trying to run containers on my host to run ceph. Perhaps I mis-understand the whole thing here. Please explain a little bit, thanks!

**Comment by leseb** [comment]
Bind-mounting is not mandatory for the demo container.`/etc/ceph` contains several files:

* ceph configuration file
* ceph admin key

**Comment by gator1** [comment]
resolved. it's because I had that address in the host /etc/ceph.
