### ISSUE TITLE
Question: Mon persistence 

### ISSUE THREAD

**Issue by qrpike** [ceph/ceph-docker#485]
I have ceph up and running in kubernetes ( THANK YOU ).

I see the warning says: "This example does not survive Kubernetes cluster restart! The Monitors need persistent storage. This is not covered here."

I have set the osd's using durable storage on each's host machine ( daemonset ). Do I also need to set the mon's (also daemonset) to use host machine mount point? If so what directory(s).

Are those the only 2 services that require data to persist restarts?

Thanks again for your hard work on this project. Cheers!

**Comment by leseb** [comment]
Yes this is the only 2 services that need persistent storage to survive restart. Have you looked at our k8s examples?

**Comment by galexrt** [comment]
@leseb But there is an issue with the mon persistence when all mon pods are deleted at the same time.
The data is gone as the data is saved in a directory named `$CLUSTER_NAME-$MON_NAME` and the `MON_NAME` (/hostname) changes on every pod "recreation" when the hostname changes and you **can't** use the same `MON_NAME` for all the mons in the cluster.
I personally think that this is related to this questions as it is an issue/question for/about the persistence.
Is there a workaround for the Ceph mon data "loss" on recreate issue?

**Comment by qrpike** [comment]
@leseb Yes, I used the kubernetes example to get my cluster up and running. However,

The Mon dp/ds does not have a volume mount:
- https://github.com/ceph/ceph-docker/blob/master/examples/kubernetes/ceph-mon-v1-ds.yaml

The Osd does have a volume mount, which I changed to be a host mount:
- https://github.com/ceph/ceph-docker/blob/master/examples/kubernetes/ceph-osd-v1-ds.yaml#L39

So if the Mon dp/ds needs to write to a directory, it's not clear where to mount the host directory.

**Comment by leseb** [comment]
@galexrt If you lose everything at once then you have a big problem. I don't think we have any workaround if you loose all the monitors. What we could do is to connect k8s to an external storage entity, maybe another Ceph cluster that can provide PVC to the containers.

**Comment by galexrt** [comment]
@leseb The fix for that maybe to use a fixed data directory and not a data directory named after `$CLUSTER_NAME-$HOSTNAME`, as seen in my submitted PR #492

**Comment by qrpike** [comment]
@leseb I put the monitors on specified hosts, so I just need to know the root directory to mount and it should be there on any reboots.

**Comment by qrpike** [comment]
@galexrt Your PR makes a lot of sense and would fix this issue.

**Comment by leseb** [comment]
LGTM, let's wait for the CI, even if I guess it's broken for now..

**Comment by galexrt** [comment]
For documentation:
To persist the OSD data mount `/var/lib/ceph/osd` to your host.
For persistent Mon data mount `/var/lib/ceph/mon` to your host.

@qrpike

**Comment by qrpike** [comment]
@leseb When will the docker image contain these changes?

Thanks,

**Comment by font** [comment]
Although specifying a specific directory as done in #492 is a workaround, the best thing would probably be to use a [Kubernetes StatefulSet](https://kubernetes.io/docs/concepts/abstractions/controllers/statefulsets/). That way the monitor hostnames are predictable and do not change while having persistent storage attached to it.

**Comment by leseb** [comment]
@qrpike I'll push the new images today.

**Comment by qrpike** [comment]
@leseb you da man!

**Comment by leseb** [comment]
@qrpike New images available!
