### ISSUE TITLE
Deprecating kv stores?

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#497]
Hi contributors,
@galindro ,@pokoli ,@ibotty ,@sajal ,@jayconroy ,@alanmeadows ,@coffeepac ,@linuxwind ,@clinta ,@ivotron ,@mainboy ,@a-nldisr ,@bnoon ,@mbessler ,@walkerlee ,@theanalyst ,@rjfd ,@minshenglin ,@osixia ,@tobilg ,@nazar-pc ,@rochaporto ,@tobegit3hub ,@BugRoger ,@mkkie ,@ohmystack ,@xcompass ,@lorieri ,@Raboo ,@CoRfr ,@slang800 ,@yxwzaxns ,@untoreh ,@immesys ,@deviantintegral ,@hookenz ,@TelanJ ,@elsonrodriguez ,@fmeppo ,@chaosaffe ,@h0tbird ,@cornelius-keller ,@rootfs ,@andrewschoen ,@font ,@streamnsight ,@dmitryint ,@hunter ,@Ulexus, @ktdreyer 

Our last survey, in https://github.com/ceph/ceph-docker/issues/472 gave us a better understanding on how ceph-docker is being used. If we look at the results here: https://www.poll-maker.com/results968938xb3e2202E-41#tab-2 it seems that consul kv store is not really popular. Over the 58 people that answered, 21 people use a kv store and only 4 people use consul. Within these 4 people, it's not clear if they use kviator to push their keys or the consul CLI.

At the very beginning, we were providing support for `etcdctl` only. Now the project is getting more attention and companies like Red Hat and potentially Suse (due to their recent image addition) are looking at productizing this.
For that, we would like to have as low packages dependencies as possible. Kviator development is not really moving, maybe for a simple reason: it does the job and there is nothing to add.

What I propose is to remove kviator and go back to `etcdctl` and `consulctl`, use separate files so anyone who wants to use or drop them can do so. This will not change existing behaviour.

Also given the last discussion we had, it seems that ConfigMaps from k8s is getting popular. As mentioned as well, the Ceph team will start working on a configuration option mapping in the Ceph mon kv store directly.
The kv support is really tight to confd, which has the same problem for us (packaging, security etc).

So if there is no real interest we would simply drop this.

So my questions are:

* Is confd needed for k8s if we use ConfigMaps?
* Can we start putting deprecation warnings?
* Is it fine if we start recommending to use ConfigMaps for k8s?

Comments? Suggestions? How can we improve this with known tools?
Thanks!

**Comment by galindro** [comment]
@leseb I agree with you to remove `kviator` and go back to `etcdctl` and `consulctl`. These are official tools with support for many features that etcd and consul have (like ACL). `kaviator` stopped in the time and we can't continue with it IMHO.
But, my doubt is: how this integration will work? I mean, how the user will choose between consul / etcd? This will be simple or he/she needs knowledge about these tools to provide the correct options to them?

**Comment by leseb** [comment]
@galindro I think we are going to have a variable to decide which KV to use and depending on the choice we will use a certain file which has the right CLI (either etcd or consul).

**Comment by elsonrodriguez** [comment]
@leseb Confd isn't needed for config maps. For that matter, another project is emerging to take its place in the k8s ecosystem: http://github.com/kelseyhightower/konfd

Konfd basically manages config maps, and those config maps can be exposed as flat config files to applications running in Kubernetes.

**Comment by ktdreyer** [comment]
In particular, please speak up in this ticket if you're continuing to use consul for configuring your Ceph cluster. Our https://jenkins.ceph.com jobs do not test this path currently.

**Comment by nazar-pc** [comment]
I'm not using it in production yet (just experimenting for now), but what I currently have uses Consul. Another difference is that my target is Docker Swarm Mode (much easier to deal with) rather than Kubernetes.

With that being said I have nothing against changing backend of the `ceph/daemon` image (in particular, dropping kviator in favor of etcdctl and consulctl) as soon as the interface for using image is the same or nearly the same. I had quite a lot of customizations to the stock image in past, but modern version of image is much better and what I'm doing now is a thin wrapper around `ceph/daemon`, so any not user-facing changes are completely fine for me.

**Comment by leseb** [comment]
@elsonrodriguez so this new konfd is a clone of confd using ConfigMaps this time. I think this is the same issue for us. Supportability etc...

**Comment by hunter** [comment]
No issues from us removing `kaviator` and switching to the tools specific to the KV backend. We've gone the K8s route with configmaps and secrets and sadly `kaviator` hasn't seen the attention needed to keep it maintained (and I assume not enough users to contribute patches required).

One downside we'd found with K8s is that configmaps and secrets can't live in the same directory (unless that changed in a recent K8s). We found the easiest way was to mount each config/secret and [symlink](https://github.com/AcalephStorage/ceph-docker/blob/more-kube-examples/ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh#L72-L80) in to /etc/ceph. We may need to add something like this to the K8s specific entrypoint code.

**Comment by elsonrodriguez** [comment]
@leseb Sorry, I think I've muddled the conversation. You don't need confd or konfd to use ConfigMaps, and any application can consume configmaps as a local file. Applications can also use config maps as a kv config store, but that requires a code change.

**Comment by leseb** [comment]
Thanks everyone for the feedback, I'll start working on this and will send a PR soon.
Thanks!

**Comment by JrCs** [comment]
Sorry i was not seeing the survey.
I use consul as a kv store for the config.
I can create a PR to add the consul support. You speak about consulctl but there are many version of consulctl on github. Which version do you recommend ?

**Comment by Raboo** [comment]
@JrCs Hi, you should probably use consul binary instead or curl.
We never know how long these consulctl projects are supported.

The consul binary can act as a kv client for consul, see here https://www.consul.io/intro/getting-started/kv.html.  So no need to use third party, only downside of using consul binary is that it's a bit big, currently around 38 MB.

Or perhaps use curl using the HTTP API, https://www.consul.io/api/kv.html
