### ISSUE TITLE
Can't create an automated Docker Registry build without access to the github Ceph org

### ISSUE THREAD

**Issue by Ulexus** [ceph/ceph-docker#5]
I was going to set up the Docker Registry automated builds for these Dockerfiles, but I cannot do so without access to the Github Ceph org.  (I do have access to the Docker Registry Ceph org.)

**Comment by Ulexus** [comment]
Relatedly, there is currently no ceph/ceph-base:latest tag, which makes it impossible to simply do a `docker pull ceph/ceph-docker`.

**Comment by leseb** [comment]
Sorry for the delay @Ulexus, can you tell me what you need and I'll make you have it.
Thanks!

**Comment by Ulexus** [comment]
Thanks, I'm now a member, so I can get this done.  I'll add the automated builds as soon as PR #9 is merged (so we don't have to rename again)

**Comment by Ulexus** [comment]
Apparently, I still don't have sufficient access to bind the Docker hooks on this repository (necessary for the automated build).  I don't know what access level that requires, but it may be easier for someone else with access to set up the automated builds.

**Comment by Ulexus** [comment]
It does let me generate an "automated build" without the build trigger, though.  That's good enough, I think.

**Comment by leseb** [comment]
Looks like the build fails:
Specified Dockerfile was not found. (/tmp/build_bczahbt4xwimbssvauckpd8/Dockerfile)

I guess the dockerfile path is wrong.

**Comment by leseb** [comment]
Hum looks like the build is looking for a Dockerfile at the root but since we have multiple Dockerfile, I'm not sure how this should work for us. Perhaps we will have to split everything into individual repos... not sure.
@Ulexus if you have an idea :), you seem to know better than I do these automated builds.

**Comment by Ulexus** [comment]
Yeah, I see.  I've actually set up each of the automated builds; you don't need to add another repo for it.  All you have to do is setup the webhooks on Github to send to each of the Docker repositories.

The documentation is [here](http://docs.docker.com/docker-hub/builds/) (skip down to the Github Service Hooks section)

**Comment by leseb** [comment]
Putting this here as a reminder for me to setup: http://docs.docker.com/docker-hub/builds/#webhooks

**Comment by Ulexus** [comment]
The service hooks appear to be in place; commits are triggering builds.
