### ISSUE TITLE
osd_disk_prepare command not found

### ISSUE THREAD

**Issue by alanv72** [ceph/ceph-docker#500]
It looks to me like the source path is wrong in the start_osd.sh. The osd_disk_prepare.sh file is in a sub-dir called osd_scenarios.

root@opcs1:~# sfdisk -d /dev/sda
label: dos
label-id: 0x5313ce2b
device: /dev/sda
unit: sectors

/dev/sda1 : start=        2048, size=   117184512, type=fd, bootable
/dev/sda2 : start=   117186560, size=    10485760, type=fd
/dev/sda3 : start=   127672320, size=    10485760, type=fd
/dev/sda4 : start=   138158080, size=   962846720, type=5
/dev/sda5 : start=   138160128, size=    10485760, type=fd
/dev/sda6 : start=   148647936, size=    10485760, type=fd
/dev/sda7 : start=   159135744, size=   941869056, type=83
root@opcs1:~#
root@opcs1:~# ceph-disk prepare --bluestore /dev/sda7 /dev/md1
set_data_partition: incorrect partition UUID: 0x83, expected ['4fbd7e29-9d25-41b8-afd0-5ec00ceff05d', '4fbd7e29-9d25-41b8-afd0-062c0ceff05d', '4fbd7e29-8ae0-4982-bf9d-5a8d867af560', '4fbd7e29-9d25-41b8-afd0-35865ceff05d']
meta-data=/dev/sda7              isize=2048   agcount=4, agsize=29433408 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=0
data     =                       bsize=4096   blocks=117733632, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=57487, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
root@opcs1:~#

root@opcs1:~# docker run -d --net=host --pid=host --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -v /dev/:/dev/ -e OSD_type=activate -e OSD_DEVICE=/dev/sda7 -e OSD_JOURNAL=/dev/md1 -e OSD_BLUESTORE=1  ceph/daemon osd
d32ed6f8f7e5a252011926e33eec044a3b154a346f8057668b5f781599f1404a

root@opcs1:~# docker logs d32ed6f8f7e5
2017-02-18 08:11:48  /entrypoint.sh: static: does not generate config
2017-02-18 08:11:48  /entrypoint.sh: Device detected, assuming ceph-disk scenario is desired
2017-02-18 08:11:48  /entrypoint.sh: Preparing and activating /dev/sda7
start_osd.sh: line 49: osd_disk_prepare: command not found

**Comment by leseb** [comment]
Fixed by https://github.com/ceph/ceph-docker/pull/491.
I just triggered a build on the docker hub.
