### ISSUE TITLE
osd - no way to specify bluestore raw,db,writelog

### ISSUE THREAD

**Issue by alanv72** [ceph/ceph-docker#502]
Need a way to deploy OSD with these options...

  bluestore block path = /dev/disk/by-partlabel/osd-device-0-block
  bluestore block db path = /dev/disk/by-partlabel/osd-device-0-db
  bluestore block wal path = /dev/disk/by-partlabel/osd-device-0-wal

**Comment by leseb** [comment]
Correct, I'll have a look into this.

**Comment by queez12** [comment]
bump
