### ISSUE TITLE
Setup a ceph cluster in docker, how do I start the containers, what image and command lines

### ISSUE THREAD

**Issue by gator1** [ceph/ceph-docker#513]
Hi,

I want to have a setup of 7 nodes, mgmt, mon1, mon2, mon3, osd1, osd2, osd3. mgmt also serves as a client. 

I think the easier way is to use ansible. From the ansible video you have five nodes up. I assume that these are based on daemon image. 

My thought is: I start those containers first. From mgmt node basically follow your video to run ansible. 

However I am not able to start the container.   I have a 36 core ubuntu 16.04 with the latest docker engine, 1.13.1.  I tried jewel with ubuntu 16.04 containers

what command do I use? I tried
docker run -d --net=host ceph-daemon
docker run -d --net=host ceph-daemon -e MON_IP=my hostip -e CEPH_PUBLIC_NETWORK=my net mask ceph/daemon 
docker run -d --net=host ceph-daemon -e MON_IP=my hostip -e CEPH_PUBLIC_NETWORK=my net mask ceph/daemon mon

None of the above keeps the container running. docker ps -a shows an exited container each time. 
I also run them with --privileged=true, same results.

Could you provide some instructions as how do we start the containers?

I was able to start the base containers but had trouble to ssh to them; either I messed up the keys or sshd not running. 

Your help is greatly appreciated.

**Comment by leseb** [comment]
@gator1 have you tried ceph-ansible to deploy that? It'll be easier.
You do not ssh into a container because there is no ssh daemon running.

If you want to get into a container once it's running you can do: `docker exec -ti <container id> bash`

**Comment by gator1** [comment]
I did. I got 
TASK [ceph.ceph-common : fail if systemd is not present] ***********************
fatal: [mon-node1]: FAILED! => {"changed": false, "failed": true, "msg": "Systemd must be present"}
fatal: [mon-node2]: FAILED! => {"changed": false, "failed": true, "msg": "Systemd must be present"}
fatal: [mon-node3]: FAILED! => {"changed": false, "failed": true, "msg": "Systemd must be present"}
	to retry, use: --limit @/root/ceph-ansible/site.retry

that is kind of odd. I am on ubuntu 16.04 and I thought systemd is on that version. 

That's why I asked what image I should use. I used ceph/base with the assumption that ansible would install ceph from scratch.  Please advise.  

I really think this project needs a step by step guide. I went through your request list and saw this guy had the same request. https://github.com/ceph/ceph-docker/issues/172

If I can get through and make it work, I can write a step by step guide how to set up on ubuntu.

**Comment by leseb** [comment]
Pease use this as an example: https://github.com/ceph/ceph-ansible/blob/master/tests/functional/centos/7/docker-cluster/group_vars/all

Yes, I'll update the wiki when I have time, sorry about this.

**Comment by gator1** [comment]
I am still having the same problem. I am running sshd so process id 1 is sshd.

Ansible might use pid to figure out ansible_service_mgr which in this case is sshd. 

How to over come this? I got to run sshd for ansible to work.

**Comment by gator1** [comment]
I am using the all file that you suggested. This is using the latest ceph-ansible. 

Using an older version that I got from redhat test drive, I could go a lot further. But ansible hangs at 
TASK: [ceph-mon | collect admin and bootstrap keys] *************************** 
Looking into the fix it seems that latest ceph-ansible would have a fix. 

The older version has ansible-playbook --version 1.9.6
ansible-playbook --version       
ansible-playbook 1.9.6
  configured module search path = None
1.9.6 doesn't complain about systemd.

**Comment by leseb** [comment]
Is it a containerized or non-containerized? This task is from the non-containerized scenario but you mentioned a containerized deployment, I'm confused.

**Comment by gator1** [comment]
It's not container. I gave up on container 

I am trying to set up centos vm on Ubuntu kvm

**Comment by gator1** [comment]
I tried to use container but now I have no idea how could docker handle ansible. I assume ansible needs each ceph node to be accessible through ssh.  Anyway I have given up ceph on container. I hope I can make it work on kvm vms but as I posted on ceph ansible I have trouble with ceph ansible with centos 7.3 vm too

**Comment by leseb** [comment]
Ok I'm closing this one then. We will follow up on the other issues.

**Comment by gator1** [comment]
I finally set up a non-containered ceph.

I really want to go back to containered one.

If I use ansible and the target containers (mons and osds) are not running
sshd as you said, how does the ansible management node reach the other
nodes?
I watched your video and the node that run ansible has to be able to reach
the other nodes, no?
