### ISSUE TITLE
Kraken ubuntu 16.04: /config.kv.sh: line 53: uudecode: command not found

### ISSUE THREAD

**Issue by osixia** [ceph/ceph-docker#528]
Just tested to upgrade from jewel to kraken and got this error:
/config.kv.sh: line 53: uudecode: command not found

**Comment by leseb** [comment]
sorry about that, this will be fixed by this PR: https://github.com/ceph/ceph-docker/pull/508

**Comment by osixia** [comment]
No problem thanks for the quick reply :)
