### ISSUE TITLE
Ceph REST API container

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#55]
I will add an image as soon as this lands: https://github.com/ceph/ceph/pull/4191

**Comment by Ulexus** [comment]
Excellent, thanks.  That's the first I've seen of ceph-rest-api.  

`<rant>`(And also WSGI... did we really need _another_ web server gateway interface protocol?)`</rant>`

**Comment by tobegit3hub** [comment]
Any process about this? We're really looking forward to this :smile:

**Comment by tobegit3hub** [comment]
And can you give the tutorial abut how to run `ceph-rest-api ` in `ceph/demo` container? @leseb @Ulexus

**Comment by tobegit3hub** [comment]
Great! Thanks @leseb :smiley:

**Comment by leseb** [comment]
@tobegit3hub np :)
