### ISSUE TITLE
Request for upgrade/update instructions (and feature compatibility matrix)

### ISSUE THREAD

**Issue by PAStheLoD** [ceph/ceph-docker#554]
Hello,

I was unable to find anything regarding how to upgrade a dockerized deployment. (Let's say a Jewel cluster to a Kraken version. Or a latest to a later latest?)

Also, is using a KV store mandatory?

Furthermore, does BlueStore work with ceph-docker?

Thanks!

**Comment by leseb** [comment]
The upgrade procedure will consist of using a new image from a new tag (see tags available on the repo). KV is not mandatory for this. How did you deploy your containers? Manually? With ceph-ansible? Other?

The procedure will remain the same as a non-containerized deployment, monitors first, then OSDs, MDS/RGW and clients. Obviously one by one.
The procedure changed when upgrading from Jewel to Kraken where you may upgrade OSDs, Monitors, and MDSs in any order. RGW daemons should be upgraded last.

**Comment by PAStheLoD** [comment]
I've used Ceph Ansible, but then added a new node manually, because ansible created a few unnecessary systemd service units. (That's when I tried to find some instructions regarding different versions, because I thought the new docker image is already using Kraken, but then noticed that despite the new image ID, latest is still Jewel.)

Okay, I'll try to add BlueStore OSDs to the cluster.
