### ISSUE TITLE
[Question] How to get cephx_service_require_signatures and cephx_require_signatures working

### ISSUE THREAD

**Issue by galexrt** [ceph/ceph-docker#556]
I'm currently trying to enable `cephx_service_require_signatures` and `cephx_require_signatures`.
But the mons are not connecting to each other. It seems that they are staying in a "wait" connect state because of the keys not being the same?:
```
2017-03-17 22:54:57.942023 7fe4f6add700  0 -- 192.168.10.3:6789/0 >> 192.168.20.3:6789/0 conn(0x5567ae7fe000 :6789 s=STATE_ACCEPTING_WAIT_CONNECT_MSG_AUTH pgs=0 cs=0 l=0).handle_connect_msg accept connect_seq 0 vs existing csq=0 existing_state=STATE_CONNECTING
```
Is there anything that can be done to allow full usage of `cephx` in the cluster and the "services"?

The docs page can be found here http://docs.ceph.com/docs/master/rados/configuration/auth-config-ref/#signatures

**Comment by leseb** [comment]
All the mons need to have the flag set to true. You can check the admin socket to make sure the option is enabled.
I don't think the issue is about the keys, it's just about all of them sharing the same config option.

**Comment by galexrt** [comment]
It seemed to be an issue with the mon keyring.
In the `start_mon.sh` all keys are imported to the mon keyring at `/etc/ceph/ceph.mon.keyring`.

The problem seems that Kubernetes is overwriting changes made to the file, so that when the keys are added to the keyring file, the changes get overwritten by Kubernetes "too fast" that it can happen that not keys are then added/installed in the `ceph-mon` "process".

At least after I added all other created keys to the `ceph.mon.keyring` file, like this:
```
[mon.]
key = ...
caps mon = ...
[client.admin]
...
[client.bootstrap-mds]
...
[client.bootstrap-osd]
...
[client.bootstrap-rgw]
...
```
The cephx "authentication" started to work. They all were/are using the same Secrets.

**Comment by galexrt** [comment]
I'm closing this as the issue is resolved for me with the solution mentioned in my comment above.
