### ISSUE TITLE
Cannot start demo container with RGW_CIVETWEB_PORT

### ISSUE THREAD

**Issue by hrchu** [ceph/ceph-docker#557]
Since s3cfg https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/demo/s3cfg does not change port conresponding to  RGW_CIVETWEB_PORT, the container will start failed.

**Comment by leseb** [comment]
Only if you change to something else than port 80 right?

**Comment by hrchu** [comment]
@leseb Y

**Comment by leseb** [comment]
@hrchu should this line be changed accordingly? https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/demo/s3cfg#L42

**Comment by hrchu** [comment]
You could change L20 and L21. It works after I manually edited it inside the running container.
