### ISSUE TITLE
Ownership of off-OSD bluestore block.wal and block.db devices is not correctly set during prepare.

### ISSUE THREAD

**Issue by netservers** [ceph/ceph-docker#614]
When preparing a bluestore OSD, where the wal and/or db pre-exists on a separate device (like an SSD), the osd_disk_prepare.sh script does not set ownership of the /dev/sdXX device to ceph:ceph.

Lines 77 to 80 of osd_disk_prepare.sh iterate over partitions 1 to 4 of the OSD device setting ownership of /dev/sdX[1-4] to ceph.

Consequently if the wal and db devices have not manually been chown'd the OSD will fail to start as follows:

>2017-04-25 17:52:48.041705 7f58e8d69a40 -1 bluestore(/var/lib/ceph/tmp/mnt.PFV7CE) _setup_block_symlink_or_file failed to open block.wal file: (13) Permission denied
2017-04-25 17:52:48.041733 7f58e8d69a40 -1 OSD::mkfs: ObjectStore::mkfs failed with error -13
2017-04-25 17:52:48.041837 7f58e8d69a40 -1  ** ERROR: error creating empty object store in /var/lib/ceph/tmp/mnt.PFV7CE: (13) Permission denied

**Comment by leseb** [comment]
That's a bit tricky but I should be able to come up with something decent soon.
Thanks for reporting this.

**Comment by leseb** [comment]
First quick stab in: https://github.com/ceph/ceph-docker/pull/616 please test

**Comment by netservers** [comment]
Sorry for leaving this for so long. I've been tied up with other things. I've still got a few issues with the fix as currently written. I've got my own modifications variation on the patch that work for me, in the sense that all permissions are correctly set and the daemon starts when it should.

However, as I hinted at before I think there's an underlying problem with Luminous, whereby the OSDs never come "up" after I reboot the host system. I get no such problem with Kraken, so I don't think this restart problem related this this issue or patch. It just means that I can't say 100% that my fix is good.

If it's OK with you I'd like to submit a fresh pull request with the latest changes I've made and see what you think.

**Comment by leseb** [comment]
Sure, if you don't mind taking over this PR: https://github.com/ceph/ceph-docker/pull/616 so I can save my earlier commit. Just re-work the parts that need to be re-written.

What do you think? Thanks!
Anyway, I'll have a fresh look into this this week.
