### ISSUE TITLE
namespace hardcoded to ceph

### ISSUE THREAD

**Issue by ReSearchITEng** [ceph/ceph-docker#625]
```
++ kubectl get pods --namespace=ceph -l daemon=mon -o template '--template={{range .items}}{{if .status.podIP}}--add {{.metadata.name}} {{.status.podIP}}:6789 {{end}} {{end}}'
No resources found.
+ MONMAP_ADD=
+ ((  timeout--  ))
+ sleep 1
+ [[ -z '' ]]
+ [[ 7 -gt 0 ]]
+ [[ 0 -eq 0 ]]
```
Image tested: docker.io/ceph/daemon:tag-build-master-luminous-centos-7

**Comment by leseb** [comment]
What is this command supposed to accomplish?

**Comment by ReSearchITEng** [comment]
Sorry for not being clear, this is a copy/paste from the log output.
I've installed with the helm charts to a different namespace, but in the logs I still see commands are run with ceph namespace.
It might be coming from the variable CLUSTER=ceph (aka ceph.cluster=ceph in values.yml) , and ignoring the namespace being set at helm install.
It's a minor thing, but the limitation was not obvious at the beginning. 
I'm using ceph namespace to work around it.

**Comment by leseb** [comment]
No worries, I recently pushed a change here: https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh#L19

I might forgotten to build a new image, doing this now.
