### ISSUE TITLE
Best approach to add additional monitors

### ISSUE THREAD

**Issue by far-blue** [ceph/ceph-docker#631]
I'm new to Ceph and I'm trying to interpret the normal ceph docs for deploying a second or additional Mon instance to the ceph-docker workflow. The normal ceph docs lead you through the process of extracting the monmap and keyring data from an exiting mon instance and then using this to add a second monitor to the cluster. `ceph auth` doesn't seem to be part of the ceph-docker offering so is there any documentation or a recommended approach for how to add a second ceph-docker based monitor?

**Comment by leseb** [comment]
To add a second monitor, simply copy the entire `/etc/ceph` of the initial monitor to the second host. Then start the monitor container. If you want to avoid manual steps, please use https://github.com/ceph/ceph-ansible

**Comment by far-blue** [comment]
great, thanks :)
