### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-docker#646]
At the risk of stating the obvious, is there documentation on how to use these containers?  I'd have expected something in README.md

**Comment by leseb** [comment]
https://github.com/ceph/ceph-docker/tree/master/ceph-releases/luminous/ubuntu/16.04/daemon?

**Comment by dmick** [comment]
That looks pretty reasonable, if I'd had any idea it existed.  I'll file a PR to point noobs to those READMEs

**Comment by leseb** [comment]
Thanks @dmick
