### ISSUE TITLE
OSD does not start if OSD_BLUESTORE_BLOCK_WAL or OSD_BLUESTORE_BLOCK_DB is used

### ISSUE THREAD

**Issue by mmailand** [ceph/ceph-docker#663]
The osd_disk_prepare.sh script does not work if OSD_BLUESTORE_BLOCK_WAL or OSD_BLUESTORE_BLOCK_DB.

The command is:

docker run -it --pid=host --net=host --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph -v /dev/:/dev -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e OSD_FORCE_ZAP=1 -e OSD_DEVICE=/dev/sda -e OSD_BLUESTORE_BLOCK_WAL=/dev/nvme0n1p9 -e OSD_BLUESTORE_BLOCK_DB=/dev/nvme0n1p5 ceph/daemon:tag-build-master-luminous-ubuntu-16.04 osd

The error log is:
...
...
command: Running command: /usr/bin/flock -s /dev/sda /sbin/partprobe /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command_check_call: Running command: /sbin/udevadm trigger --action=add --sysname-match sda1
Waiting for /dev/sda3 to show up
Waiting for /dev/sda3 to show up
Waiting for /dev/sda3 to show up
Waiting for /dev/sda3 to show up
Waiting for /dev/sda3 to show up
Waiting for /dev/sda3 to show up
Waiting for /dev/sda3 to show up
Waiting for /dev/sda3 to show up
Waiting for /dev/sda3 to show up
Waiting for /dev/sda3 to show up

Then the container exits.

I think the issue is the osd_disk_prepare.sh

line 76+
  elif [[ ${OSD_BLUESTORE} -eq 1 ]]; then
    for part in $(seq 1 4); do
      wait_for_file $(dev_part ${OSD_DEVICE} $part)
      chown ceph. $(dev_part ${OSD_DEVICE} $part)
    done
  else

It should change is something like this:

  elif [[ ${OSD_BLUESTORE} -eq 1 ]]; then
    for part in $(seq 1 4); do
      wait_for_file $(dev_part ${OSD_DEVICE} $part)
      chown ceph. $(dev_part ${OSD_DEVICE} $part)
    done
  elif [[ ${OSD_BLUESTORE} -eq 1 ]] && [[ ${OSD_BLUESTORE_BLOCK_WAL} -eq 1 ]] && [[ ${OSD_BLUESTORE_BLOCK_DB} -eq 1 ]]; then
for part in $(seq 1 2); do
      wait_for_file $(dev_part ${OSD_DEVICE} $part)
      chown ceph. $(dev_part ${OSD_DEVICE} $part)
 done 
      wait_for_file $(dev_part ${OSD_BLUESTORE_BLOCK_WAL})
      chown ceph. $(dev_part ${OSD_BLUESTORE_BLOCK_WAL})
      wait_for_file $(dev_part ${OSD_BLUESTORE_BLOCK_DB})
      chown ceph. $(dev_part ${OSD_BLUESTORE_BLOCK_DB})
 else

Thanks for the great docker image.
best regards,
martin

**Comment by leseb** [comment]
@mmailand thanks for reporting this, do you mind pushing a PR to fix this? Thanks!

**Comment by leseb** [comment]
The fix is actually included in https://github.com/ceph/ceph-docker/pull/616

**Comment by mmailand** [comment]
Yes, the PR #616 fixes this issue.
