### ISSUE TITLE
How about pushing images in docker hub

### ISSUE THREAD

**Issue by tobegit3hub** [ceph/ceph-docker#67]
It would be better to push these images in docker hub so that we don't need to build them again :smiley:

**Comment by tobegit3hub** [comment]
We always setup automatic build in docker hub so that once we update the image, everybody can use it. And we don't need to do anything like building image locally and pushing it into docker hub manually.

**Comment by Ulexus** [comment]
These are in Docker Hub, and they are set to automatically build on updates:
[https://registry.hub.docker.com/repos/ceph/](https://registry.hub.docker.com/repos/ceph/)

**Comment by tobegit3hub** [comment]
I didn't notice it because the latest ceph/demo is not there. Maybe just add this image later. Anyway, thanks for all your work :+1:

**Comment by Ulexus** [comment]
Ah, good point.  

@leseb  Is the demo sufficiently rugged/flexible to add an autobuild for it?

**Comment by leseb** [comment]
Oh yes I believe it is.

**Comment by tobegit3hub** [comment]
Thanks @Ulexus and @leseb :smiley:

**Comment by Ulexus** [comment]
I just kicked off the automated build for `ceph/demo`

**Comment by tobegit3hub** [comment]
Great!
