### ISSUE TITLE
Add detailed instruction for demo docker container

### ISSUE THREAD

**Issue by tobegit3hub** [ceph/ceph-docker#68]
I would like to try demo docker container but I'm confused about the parameters.

Here's my error message and I have no idea how to fix it. More instruction is really welsome :smiley: 

```
➜  demo git:(master) docker run -d --net=host -v /etc/ceph:/etc/ceph -e MON_IP=172.17.42.1 -e CEPH_NETWORK=172.17.0.0/24 ceph/demo                                                                                  
ee3fa8858386595b7e66d7eeebf016694b0ee59a5a19a0d4b2a7f10d3fce5e87
➜  demo git:(master) docker logs -f ee3fa8858386595b7e66d7eeebf016694b0ee59a5a19a0d4b2a7f10d3fce5e87                              
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
2015-05-20 10:07:18.471878 7f54afc4b8c0 -1 unable to find any IP address in networks: 96.126.0.0/24
```

**Comment by Ulexus** [comment]
I'll let @leseb handle any further details, but the problem you're running into is that you're running with `--net=host`, meaning Docker will run the container in the host's network instead of the Docker network.  However, you are referencing IP addresses (`MON_IP`, for instance) in the Docker network.

You need to choose one or the other, not both.

**Comment by leseb** [comment]
@Ulexus comment is correct, you should chose the IP address of the host running Docker since you use `--net=host`.

**Comment by tobegit3hub** [comment]
I was following the command in README.md. If I just use `--net=host`, I got another error.

```
➜  demo git:(master) sudo docker run -d --net=host -v /etc/ceph:/etc/ceph ceph/demo                                                                                                                                 
5697fd7af0cc426d7b2cf1b59be5b63f43058f1e0ae776d394444be0661ea69f
➜  demo git:(master) sudo docker logs 5697fd7af0cc426d7b2cf1b59be5b63f43058f1e0ae776d394444be0661ea69f
ERROR- CEPH_NETWORK must be defined as the name of the network for the OSDs
```

Please tell us the correct way to launch ceph/demo container and how can we configure it.

**Comment by leseb** [comment]
Get the IP address of your machine running Docker. Then use this IP in the `MON_IP` variable.

**Comment by tobegit3hub** [comment]
Hi @leseb . Please checkout my error log. It fails and said "unable to find any IP address in networks: 192.168.0.0/24". However, I passed "172.16.0.0/24" when I ran the container.

```
➜  ~  sudo docker run -d --net=host -v /etc/ceph:/etc/ceph -e MON_IP=172.16.0.206 -e CEPH_NETWORK=172.16.0.0/24 ceph/demo
392dddf8a5c2b926e0551e0d71a98b7f9afaabcd4fbd9f3eb7678953adaebb0b
➜  ~  sudo docker logs -f 392dddf8a5c2b926e0551e0d71a98b7f9afaabcd4fbd9f3eb7678953adaebb0b                               
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
2015-05-25 09:10:19.809116 7f23106208c0 -1 unable to find any IP address in networks: 192.168.0.0/24
```

It seems the script doesn't accept the environment variable to run the ceph processes.

**Comment by tobegit3hub** [comment]
Oh, it's the problem of ceph configuration in my localhost. It didn't update the ceph.conf when I try to pass another `MON_IP` or `CEPH_NETWORK`. This's not a issue but takes time to find out the problem. Maybe we should not use `-v /etc/ceph:/etc/ceph` and rely on nothing from the host.

Thanks for all your help and the image works well every time :smiley:

**Comment by leseb** [comment]
Great!

**Comment by tobegit3hub** [comment]
I have tested to run demo container without `-v /etc/ceph:/etc/ceph` and it worked. How about removing this parameter in README and just tell us we can do it to pass the configuration files.

**Comment by leseb** [comment]
I think we should keep the `-v` option as it is maybe we should include a warning in the README.
Do you want to push this PR? :)

**Comment by tobegit3hub** [comment]
It's a minor change. You can add it by the way. And thanks for all your work :+1:

**Comment by steffenmllr** [comment]
Trying to get this to work within `boo2docker` on osx but it doesn't seem to work:

`docker run -d -e MON_IP=$(boot2docker ip 2>/dev/null) -e CEPH_NETWORK=172.17.42.1/24 ceph/demo`

which results in `2015-07-20 21:21:44.936721 7fd6194e48c0 -1 unable to find any IP address in networks: 172.17.42.1/24`

What exactly do I need to pass into the `CEPH_NETWORK` the IP of the docker network bridge  ?

**Comment by tobegit3hub** [comment]
Hi @steffenmllr , it's the CIDR of your IP. If your `boot2docker ip` is 172.17.42.1, then use `CEPH_NETWORK=172.17.42.0/24 `. Make sure the last number is 0 and it should work.

**Comment by steffenmllr** [comment]
thanks for the hint @tobegit3hub, but that somehow doesn't work for me:

```bash
$ boot2docker ip                                                                                                                                       
192.168.59.103

$ docker run -d -e MON_IP=192.168.59.103 -e CEPH_NETWORK=192.168.59.0/24 ceph/demo                                                                       
0d95d75d7a5ecfce52483c95f8e27f01c6b4e4b98801c599fe5a1fe6c57f2047

$ docker logs 0d95d75d7a5ecfce52483c95f8e27f01c6b4e4b98801c599fe5a1fe6c57f2047                                                                           creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
monmaptool: monmap file /etc/ceph/monmap
monmaptool: set fsid to 22460643-77d3-4d4f-8359-3ac566497ff5
monmaptool: writing epoch 0 to /etc/ceph/monmap (1 monitors)
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
2015-07-20 23:07:52.330215 7fcf3de2d8c0 -1 unable to find any IP address in networks: 192.168.59.0/24
```

**Comment by leseb** [comment]
@steffenmllr please look at the README for ceph/demo. You have to use `--net=host` to work.
So this will give you:

```
$ docker run -d --net=host -v /var/lib/ceph:/var/lib/ceph -v /etc/ceph:/etc/ceph -e MON_IP=192.168.59.103 -e CEPH_NETWORK=192.168.59.0/24 ceph/demo

**Comment by musha68k** [comment]
+1 thanks @leseb I'm on OSX like @steffenmllr and ran into the same issues - the part of MON_IP pointing to the IP address of your docker-machine / build2docker just booted my container successfully!

**Comment by hrchu** [comment]
The -v option is still a problem today :(

**Comment by zealotous** [comment]
@hrchu, take a look at https://github.com/ceph/ceph-docker/issues/496 there are the solution.
