### ISSUE TITLE
Kubernetes - How to persist ceph-mon

### ISSUE THREAD

**Issue by fjudith** [ceph/ceph-docker#692]
Hello,

In the [Kubernetes example](https://github.com/ceph/ceph-docker/tree/master/examples/kubernetes) there is a warning about ceph-mon storage persistence.

Could you please clarify the impact ? 
Will that mean that OSD configuration will be lost after host reboot or ceph-mon rescheduling ?

**Comment by ktosiek** [comment]
It will, if you lose quorum while doing those restarts. I think the `local` storage in 1.7 might be a way around that in the future.

**Comment by leseb** [comment]
Currently, the only way to persist the ceph mon store is to bind-mount it.

**Comment by fjudith** [comment]
thank you @leseb 

Do you have an example ?

**Comment by leseb** [comment]
I do not but you can do something similar to that https://github.com/ceph/ceph-docker/blob/master/examples/kubernetes/ceph-mon-v1-dp.yaml#L71-L73 for `/var/lib/ceph/mon`.
