### ISSUE TITLE
Retrive bootstrap keys from cluster instead of generating new one

### ISSUE THREAD

**Issue by AlessandroLorenzi** [ceph/ceph-docker#704]
I see that when i bootstrap first node the osd bootraps correctly, while the others nodes fails because of auth error.

I suggest to retrive the bootstrap keys from cluster rather then generate a new one. 
Example: 

```bash
  if [ ! -e "$OSD_BOOTSTRAP_KEYRING" ]; then
    # Generate the OSD bootstrap key
    ceph-authtool "$OSD_BOOTSTRAP_KEYRING" --create-keyring --gen-key -n client.bootstrap-osd --cap mon 'allow profile bootstrap-osd'
  fi
```

```bash
  if [ ! -e "$OSD_BOOTSTRAP_KEYRING" ]; then
    # Generate the OSD bootstrap key
    ceph auth get-or-create client.bootstrap-osd mon 'allow profile bootstrap-osd' -o "$OSD_BOOTSTRAP_KEYRING"
    chown ceph. "$OSD_BOOTSTRAP_KEYRING"
  fi
```

**Comment by AlessandroLorenzi** [comment]
(I'm using tag-build-master-luminous-ubuntu-16.04)

**Comment by leseb** [comment]
@AlessandroLorenzi retrieving the key assumes that you have the admin key available.
On a static deployment, it's expected that a tool like Ansible will distribute the bootstrap keys across all the nodes. So the behaviour can not be changed.

**Comment by AlessandroLorenzi** [comment]
oki, thanks anyway!
