### ISSUE TITLE
typo in the shell scripts

### ISSUE THREAD

**Issue by likunbyl** [ceph/ceph-docker#707]
I found the following in the start_mon.sh: 
```
 ceph "${CLI_OPTS}" auth get-or-create mgr."$MGR_NAME" mon 'allow profile mgr' osd 'allow *' mds 'allow *' -o "$MGR_KEYRING"
```
shouldn't be :  ceph "${CLI_OPTS[@]}" ....... ?

also in the osd_common.sh: 

 echo "${CLUSTER}-${OSD_ID}: /usr/bin/ceph-osd ${CLI_OPTS} -f -i ${OSD_ID} --setuser ceph --setgroup disk" | tee -a /etc/forego/"${CLUSTER}"/Procfile

also ${CLI_OPTS}

**Comment by leseb** [comment]
This is fixed, let me push a new version.
