### ISSUE TITLE
Something wrong with Newest kraken image 

### ISSUE THREAD

**Issue by likunbyl** [ceph/ceph-docker#713]
I have just downloaded the newest version of  ceph/daemon:tag-build-master-jewel-ubuntu-16.04, has several questions:

1.  in `start_mon.sh`, has the following line:
```
timeout 7 ceph "${CLI_OPTS}" mon add "${MON_NAME}" "${MON_IP}:6789" || true
```

in `osd_common.sh`: 

```
echo "${CLUSTER}-${OSD_ID}: /usr/bin/ceph-osd ${CLI_OPTS} -f -i ${OSD_ID} --setuser ceph --setgroup disk" | tee -a /etc/forego/"${CLUSTER}"/Procfile
```
    
in `start_mgr.sh`, has the following line:
```
ceph "${CLI_OPTS}" auth get-or-create mgr."$MGR_NAME" mon 'allow profile mgr' osd 'allow *' mds 'allow *' -o "$MGR_KEYRING"
```

    `${CLI_OPTS}` shouldn't be `${CLI_OPTS[@]}` ?

2.  What's `CEPH_PUBLIC_NETWORK` used for, I have this values setted, could it work? 
```
+start_mon.sh:95: start_mon(): CEPH_PUBLIC_NETWORK='10.3.3.0/26
10.3.3.64/26
172.16.72.0/30
172.16.72.4/30
172.16.72.8/30
172.16.72.12/30
172.16.72.16/30
172.16.72.20/30
172.16.72.24/30
172.16.72.28/30
172.22.5.64/26
172.22.10.192/26
172.22.14.128/26
172.22.40.128/26
172.22.44.192/26
172.22.49.0/26
172.22.76.64/26
172.22.76.128/26
172.22.90.0/26
172.22.93.128/26
172.22.97.192/26
172.22.104.64/26 '
```

**Comment by leseb** [comment]
@likunbyl addressing your first questions in https://github.com/ceph/ceph-docker/pull/736
Now regarding: `CEPH_PUBLIC_NETWORK`, it's used so the osds can listen on an ip on that network.

The script does:

1. `grep -vE "lo:|face|Inter" /proc/net/dev | sort -n -k 2 | tail -1 | awk '{ sub (":", "", $1); print $1 }'``
2. then used the interface and run, e.g: `ip -4 route show dev "enp0s31f6" | grep proto | awk '{ print $1 }' | grep -v default | grep "/"``

It looks like you have many subnet configured on that interface, am I right?

**Comment by leseb** [comment]
@likunbyl https://github.com/ceph/ceph-docker/pull/736
