### ISSUE TITLE
Docker container for Journal device and data as osd-directory

### ISSUE THREAD

**Issue by dhirajh** [ceph/ceph-docker#716]
I would like to run a OSD container with Journal set to block device and OSD data set to a file system for Jewel release (Centos 7). What this means is that I would like to set OSD_TYPE=directory and OSD_JOURNAL=/dev/xxx. However, as per ceph-docker documentation this mix of settings is not supported. Is there a reason for not supporting this? or did I misread the documentation?

**Comment by dhirajh** [comment]
@leseb I was wondering if you had any thoughts on this issue.

**Comment by leseb** [comment]
That's easy, just set `-e OSD_DEVICE=/dev/sda` and `-e OSD_JOURNAL=/dev/sdb`. The container will do the rest and configure the fs for ceph data and the block device for the journal.

**Comment by dhirajh** [comment]
@leseb To clarify, the scenario I am describing is where I want to set OSD_DIRECTORY=directory as I have a file system directory that I want to bind mount to  /var/lib/ceph/osd/. At the same time, I want to expose a block level device for the journal. It looks like the docker image does not support this combination.

**Comment by leseb** [comment]
Well in this case, you will have to manually symlink the journal to the block device. This is not supported by the directory scenario because this allows us to run with unpriviledged container (since you have a file for the journal and the ceph data store on a fs, no block device access is required).

**Comment by dhirajh** [comment]
Ah OK, So all I need is a symlink ( that is named journal) to the block device under the osd_directory and the container would make appropriate use of it as a journal? Thanks.

**Comment by leseb** [comment]
Correct
