### ISSUE TITLE
cannot override osd_cluster_network and ose_public_network

### ISSUE THREAD

**Issue by rootfs** [ceph/ceph-docker#727]
Tried `example/kubernetes` but couldn't override them through environmental variables. I had to manually change them in `ceph-docker/examples/kubernetes/generator/templates/ceph/ceph.conf.jinja`. 

Looking at jinja2 doc, there is no builtin filter to pick up the environmental variables. 

@leseb

**Comment by font** [comment]
Ah, yes, that's a problem and the workaround is as you mentioned or switching back to `sigil`. Here are a couple links to comments for more context:
https://github.com/ceph/ceph-docker/pull/618#issuecomment-303453232
https://github.com/ceph/ceph-docker/pull/652#issuecomment-303766097

**Comment by font** [comment]
Looks like a PR with the fix was just opened. 😃  https://github.com/ceph/ceph-docker/pull/726

**Comment by rootfs** [comment]
+1
