### ISSUE TITLE
chown -R /var/lib/ceph slowing down osd startup

### ISSUE THREAD

**Issue by prymitive** [ceph/ceph-docker#739]
I tried to upgrade OSDs running jewel to the latest image but it turns out that a test OSD was starting slowly, chowning everything on start.
I see that [create_mandatory_directories](https://github.com/ceph/ceph-docker/blob/build-master-jewel-ubuntu-16.04/ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh#L74) run chown on the entire `/var/lib/ceph/`, which in my case means a few hours (6TB 7200RPM drives with millions of files).
I'm not sure if I'm suppose to have OSD dirs in some other place now and this is my config issue, or is the chown usage too optimistic and assumes it will run quickly. I have 12 volumes in docker with `-v /disk/0:/var/lib/ceph/osd/ceph-0 ...` right now. Should I mount those volumes in a different location now? How can I avoid doing `chow -R` on those directories every time osd starts?

Doing find on one disk:
```
$ time find /disk/data0 > /dev/null 

real	16m50.946s
user	0m2.072s
sys	0m15.527s
```
and there's 12 of those, let's round it down to 15m, 12*15m = 180m = 3h of startup delay

**Comment by leseb** [comment]
I figured that out yesterday as well, will send a fix to not run on OSD data dir.
Thanks!

**Comment by leseb** [comment]
@prymitive please review https://github.com/ceph/ceph-docker/pull/742

**Comment by prymitive** [comment]
That should do it in terms of startup speed, but if ceph daemon runs as a non-root user now then I'll need to manually `chown -R` all OSD disks (which is fine, but might want to warn users).
