### ISSUE TITLE
Can't launch mgr container with env var `MGR_DASHBOARD=1`

### ISSUE THREAD

**Issue by guits** [ceph/ceph-docker#746]
see comment [here](https://github.com/ceph/ceph-docker/commit/4843e283ae867c8767c9432ea14c404c0a9d14d6#commitcomment-23597370)

**Comment by leseb** [comment]
Hum, AFAIR the container is always run by root so the script execution shouldn't be a problem. Only the ceph process runs as 'ceph'.

**Comment by mkkie** [comment]
BTW, in 12.1.2 or later version. I have to enable mgr module for showing the dashboard. http://docs.ceph.com/docs/master/mgr/dashboard/#enabling

**Comment by leseb** [comment]
@mkkie thanks for the pointer!
