### ISSUE TITLE
CAnnot populate KV store using docker images

### ISSUE THREAD

**Issue by pgeorgiev333** [ceph/ceph-docker#747]
Following the procedure i first:

- start ETCD container
- poplulate the KV store using the "populate_kvstore" command
- start the mon service

The mon service part fails:

2017-08-15 10:56:40  /entrypoint.sh: Importing Keyrings and Monmap to KV.
/config.kv.etcd.sh: line 83: /etc/ceph/ceph.mon.keyring: No such file or directory

I looked at the script i it seems the $MON_KEYRING is not created anywhere in the script so there is nothing to import. I suspsect that line

https://github.com/ceph/ceph-docker/blob/master/ceph-releases/kraken/ubuntu/16.04/daemon/config.kv.etcd.sh67 or 59 is wrong as in both places the same keyring is created:

>  log "Creating Keyrings."
    ceph-authtool **"$ADMIN_KEYRING"** --create-keyring --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'
    if [ -z "$ADMIN_SECRET" ]; then
      # Automatically generate administrator key
      CLI+=(--gen-key)
    else
      # Generate custom provided administrator key
      CLI+=("--add-key=$ADMIN_SECRET")
    fi
    ceph-authtool **"$ADMIN_KEYRING"** --create-keyring "${CLI[@]}" -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'

I use the kraken images. Now i looked at the jewel ones and i see this line:

 ` ceph-authtool "$MON_KEYRING" --create-keyring --gen-key -n mon. --cap mon 'allow *'`

So it should work. I'll test that soon

**Comment by pgeorgiev333** [comment]
works. So the kraken script should be fixed

**Comment by leseb** [comment]
Thanks for reporting this, fixed in https://github.com/ceph/ceph-docker/pull/753
