### ISSUE TITLE
migrate from consul to etcd

### ISSUE THREAD

**Issue by Raboo** [ceph/ceph-docker#749]
Hi,

Since consul got deprecated I need to migrate our consul kv to etcd.
I can easily read out all data from consul like this `consul kv get -http-addr=$KV:8500 -recurse ceph-config`

And I can easily write single k/v to etcd like this `etcdctl --endpoints http://labb01:2379 mk ceph-config/ceph/osd/osd_mkfs_options_xfs '"-f -i size=2048"'`

But how can I write multi line values like the **ceph-config/ceph/monmap** with the following content?
```
begin 644 -
M`P/8`0``Q5V4G`;31EZ\1G[P0)H[50,````#````!````'9M,#$`````````
M```"&H4*`SP9````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````!````'9M
M,#(````````````"&H4*`SP7````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````!````'9M,#,````````````"&H4*`SP5````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
<````````````````V2#P5CUKC@7'(/!6N/C,%```
`
end
```

**Comment by mkkie** [comment]
https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/config.kv.etcd.sh#L40

**Comment by Raboo** [comment]
Ok, cool
Didn't know that I could pipe in data via etcdctl

So now I did this

```bash
./consul kv get -http-addr=vm01:8500 -recurse ceph-config | grep : | cut -d: -f1 | while read line ; do ./consul kv get -http-addr=vm01:8500 $line | ./etcdctl --endpoints http://labb01:2379 set $line ; done
```

But all the values inserted have an extra empty line at the end.
I need to figure out how to get that removed.

**Comment by leseb** [comment]
@Raboo perhaps the extra line comes from `consul kv get`, if so you can trim this using a bash substitution.

**Comment by Raboo** [comment]
`./consul kv get -http-addr=vm01:8500 -recurse ceph-config | grep : | cut -d: -f1 | while IFS= read -r line ; do ./consul kv get -http-addr=vm01:8500 $line |head -c-1 | ./etcdctl --endpoints http://labb01:2379 set $line ; done`
