### ISSUE TITLE
etcdctl unsupported protocol scheme

### ISSUE THREAD

**Issue by Raboo** [ceph/ceph-docker#758]
Hi,

Don't know if this is a everyone bug or just a me bug..

Trying to start for instance our MDS we get the following error looping:
```
2017-08-24 15:16:16  /entrypoint.sh: OSD: Waiting for monitor setup to complete...
Error:  unsupported protocol scheme "vm01.prod"
```
I've traced this to https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/variables_entrypoint.sh#L74

Basically the problem is that etcdctl is beeing executed without a protocol scheme.
So this is beeing executed:
```
# etcdctl --peers vm01.prod:2379 get ceph-config/ceph/monSetupComplete
Error:  unsupported protocol scheme "vm01.prod"
```

But this is how it should work
```
# etcdctl --peers http://vm01.prod:2379 get ceph-config/ceph/monSetupComplete
true
```

And my question is, why am I the only one affected by this?
Can i submit a PR that adds http:// before ${KV_IP} or perhaps a `if` that  checks for $KV_CA_CERT and adds https or http depending on the situation?

**Comment by Raboo** [comment]
hmm
I figured it out. It's because I use hostname instead of IP. And the variable is called KV_IP, so I guess IP should be used.

So this is a side effect coming from consul where hostname worked.
Maybe we should add support for having a hostname in KV_IP variable?

**Comment by leseb** [comment]
@Raboo if etcd supports it then yes :)

**Comment by Raboo** [comment]
Should I assume http or should it be http or https based if KV_CA_CERT variable is set?

**Comment by gbritton** [comment]
I've hit this with https, you need the protocol scheme in that case otherwise it defaults to http.  I fixed it by doing so in the scripts if a cert was set, otherwise I used http://.  I never got around to submitting the fix though and would have to dig around to find it again.

**Comment by shift** [comment]
My fix for this is the following https://github.com/shift/ceph-docker/commit/de8b6a91626ded60175482d8d59f8d7f6d7433f1

**Comment by Raboo** [comment]
added a PR https://github.com/ceph/ceph-docker/pull/765

**Comment by Raboo** [comment]
PR was merged, so I'll close this issue.
