### ISSUE TITLE
ceph-mgr dashboard can't be enabled with the latest docker-images

### ISSUE THREAD

**Issue by JrCs** [ceph/ceph-docker#759]
Hi,
i'm using the latest ceph/daemon:tag-build-master-luminous-centos-7 image and when the entrypoint (start_mgr.sh) try to enable the dashboard with the command
```bash
ceph "${CLI_OPTS[@]}" mgr module enable dashboard
```
it failed with the error:
`Error ENOENT: all mgr daemons do not support module 'dashboard', pass --force to force enablement`

I think it in relation with commit 7bcef34

**Comment by leseb** [comment]
@liewegas this seems to be related to https://github.com/ceph/ceph/commit/d953198aff3e5aaa6e2eadcf8a53c9e0279a30de, should we force the execution for the dashboard? Thanks!
