### ISSUE TITLE
Can't create mon , Centos 7

### ISSUE THREAD

**Issue by troychn** [ceph/ceph-docker#772]
[root@node01 network-scripts]# docker run -d \
>         --name=mon \
>         --net=host \
>         --restart=always \
>         -v /etc/ceph:/etc/ceph \
>         -v /var/lib/ceph:/var/lib/ceph \
>         -e MON_IP=192.168.188.107 \
>         -e CEPH_PUBLIC_NETWORK=192.168.188.0/24 \
>         ceph/daemon mon
d7fecb0cfc35684a6b898981e150458706be817c723904b345ddbfbd71ea201f
[root@node01 network-scripts]# docker logs -f mon
ownership of '/var/run/ceph/' retained as ceph:ceph
changed ownership of '/var/lib/ceph/bootstrap-osd' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/bootstrap-mds' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/bootstrap-rgw' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/mon' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/mon/ceph-node01' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/osd' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/mds' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/mds/ceph-node01' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/radosgw' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/radosgw/node01' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/tmp' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/mgr' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/mgr/ceph-node01' from root:root to ceph:ceph
creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
creating /var/lib/ceph/bootstrap-osd/ceph.keyring
creating /var/lib/ceph/bootstrap-mds/ceph.keyring
creating /var/lib/ceph/bootstrap-rgw/ceph.keyring
creating /var/lib/ceph/bootstrap-rbd/ceph.keyring
bufferlist::write_file(/var/lib/ceph/bootstrap-rbd/ceph.keyring): failed to open file: (2) No such file or directory
could not write /var/lib/ceph/bootstrap-rbd/ceph.keyring
ownership of '/var/run/ceph/' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph
changed ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' from root:root to ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph
changed ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' from root:root to ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph
changed ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' from root:root to ceph:ceph
ownership of '/var/lib/ceph/mon' retained as ceph:ceph
ownership of '/var/lib/ceph/mon/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/osd' retained as ceph:ceph
ownership of '/var/lib/ceph/mds' retained as ceph:ceph
ownership of '/var/lib/ceph/mds/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw/node01' retained as ceph:ceph
ownership of '/var/lib/ceph/tmp' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr/ceph-node01' retained as ceph:ceph
creating /var/lib/ceph/bootstrap-rbd/ceph.keyring
bufferlist::write_file(/var/lib/ceph/bootstrap-rbd/ceph.keyring): failed to open file: (2) No such file or directory
could not write /var/lib/ceph/bootstrap-rbd/ceph.keyring
ownership of '/var/run/ceph/' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/mon' retained as ceph:ceph
ownership of '/var/lib/ceph/mon/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/osd' retained as ceph:ceph
ownership of '/var/lib/ceph/mds' retained as ceph:ceph
ownership of '/var/lib/ceph/mds/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw/node01' retained as ceph:ceph
ownership of '/var/lib/ceph/tmp' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr/ceph-node01' retained as ceph:ceph
creating /var/lib/ceph/bootstrap-rbd/ceph.keyring
bufferlist::write_file(/var/lib/ceph/bootstrap-rbd/ceph.keyring): failed to open file: (2) No such file or directory
could not write /var/lib/ceph/bootstrap-rbd/ceph.keyring
ownership of '/var/run/ceph/' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/mon' retained as ceph:ceph
ownership of '/var/lib/ceph/mon/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/osd' retained as ceph:ceph
ownership of '/var/lib/ceph/mds' retained as ceph:ceph
ownership of '/var/lib/ceph/mds/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw/node01' retained as ceph:ceph
ownership of '/var/lib/ceph/tmp' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr/ceph-node01' retained as ceph:ceph
creating /var/lib/ceph/bootstrap-rbd/ceph.keyring
bufferlist::write_file(/var/lib/ceph/bootstrap-rbd/ceph.keyring): failed to open file: (2) No such file or directory
could not write /var/lib/ceph/bootstrap-rbd/ceph.keyring
ownership of '/var/run/ceph/' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/mon' retained as ceph:ceph
ownership of '/var/lib/ceph/mon/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/osd' retained as ceph:ceph
ownership of '/var/lib/ceph/mds' retained as ceph:ceph
ownership of '/var/lib/ceph/mds/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw/node01' retained as ceph:ceph
ownership of '/var/lib/ceph/tmp' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr/ceph-node01' retained as ceph:ceph
creating /var/lib/ceph/bootstrap-rbd/ceph.keyring
bufferlist::write_file(/var/lib/ceph/bootstrap-rbd/ceph.keyring): failed to open file: (2) No such file or directory
could not write /var/lib/ceph/bootstrap-rbd/ceph.keyring
ownership of '/var/run/ceph/' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/mon' retained as ceph:ceph
ownership of '/var/lib/ceph/mon/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/osd' retained as ceph:ceph
ownership of '/var/lib/ceph/mds' retained as ceph:ceph
ownership of '/var/lib/ceph/mds/ceph-node01' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw/node01' retained as ceph:ceph
ownership of '/var/lib/ceph/tmp' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr/ceph-node01' retained as ceph:ceph
creating /var/lib/ceph/bootstrap-rbd/ceph.keyring
bufferlist::write_file(/var/lib/ceph/bootstrap-rbd/ceph.keyring): failed to open file: (2) No such file or directory
could not write /var/lib/ceph/bootstrap-rbd/ceph.keyring

**Comment by troychn** [comment]
no such file or directory
[root@node01 network-scripts]# ll /var/lib/ceph/
总用量 0
drwxr-xr-x. 2 64045 64045 25 9月  12 11:21 bootstrap-mds
drwxr-xr-x. 2 64045 64045 25 9月  12 11:21 bootstrap-osd
drwxr-xr-x. 2 64045 64045 25 9月  12 11:21 bootstrap-rgw
drwxr-xr-x. 3 64045 64045 24 9月  12 11:21 mds
drwxr-xr-x. 3 64045 64045 24 9月  12 11:21 mgr
drwxr-xr-x. 3 64045 64045 24 9月  12 11:21 mon
drwxr-xr-x. 2 64045 64045  6 9月  12 11:21 osd
drwxr-xr-x. 3 64045 64045 19 9月  12 11:21 radosgw
drwxr-xr-x. 2 64045 64045  6 9月  12 11:21 tmp
您在 /var/spool/mail/root 中有新邮件

**Comment by guits** [comment]
@troychn can you link your `group_vars/*` and inventory host file?

**Comment by troychn** [comment]
hi @guits
I don't understand what you mean, can you explain it? 
thanks!

**Comment by yoke88** [comment]
The same error when using the lastest docker image

``` bash
core@core-02 /var/lib/ceph $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ceph/daemon         latest              5ba8f9974cf7        9 hours ago         981MB

```

mannully create the folder /var/lib/ceph/bootstrap-rbd and set owner to 64045 will resolve the problem

``` bash
sudo mkdir /var/lib/ceph/bootstrap-rbd
sudo chown -R 64045:64045 /var/lib/ceph/bootstrap-rbd
```

**Comment by leseb** [comment]
Thanks for reporting this, fix here: https://github.com/ceph/ceph-docker/pull/779
