### ISSUE TITLE
Can't start mon Centos7 luminous 12.2.0

### ISSUE THREAD

**Issue by JrCs** [ceph/ceph-docker#778]
Hi,
when i try to start a monitor (previously in version 12.1.4) with the image tag-build-master-luminous-centos-7 it failed when it try to register himself in the etcd database:
```bash
$ etcdctl --peers 10.203.37.218:2379 set ceph-config/ceph/mon_host/node69ceph01 10.203.37.218
parse 10.203.37.218:2379: first path segment in URL cannot contain colon
```

**Comment by leseb** [comment]
Could this PR be the culprit? https://github.com/ceph/ceph-docker/pull/765/files

**Comment by JrCs** [comment]
The problem is that in the image i take from docker-hub, the ETCD_SCHEMA variable doesn't exists. So the schema is missing for the etcdctl command. With http:// in front of peers ip:port it works.
I close this issue because it must work with a new image.
For your information the --peers option is deprecated in etcd3 in favor of --endpoints option.
