### ISSUE TITLE
Error when I run osd container

### ISSUE THREAD

**Issue by olivetree123** [ceph/ceph-docker#796]
I have ran ceph-docker like this:
`docker run -d --net=host --name=osd --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph -v /dev:/dev -e OSD_DEVICE=/dev/vdb ceph/daemon osd_ceph_disk`

Error: 
`docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/var/lib/docker/containers/d6a753ae5eb58634cb708adc5c741d64ee514abf0f56a048325b35be45769209/shm\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/ec24240543bbd80a11fc32f44913d8cd3a18434d658ac733284aca0b263126e9\\\" at \\\"/dev/shm\\\" caused \\\"evalSymlinksInScope: too many links in /var/lib/docker/aufs/mnt/ec24240543bbd80a11fc32f44913d8cd3a18434d658ac733284aca0b263126e9/dev/shm\\\"\"".`

**Comment by olivetree123** [comment]
another question , will it clean up data in /dev/vdb ?

**Comment by leseb** [comment]
The error you are seeing is not related to the container image but more to your container engine.
By default, it won't clean up data, unless you force it with `OSD_FORCE_ZAP=1`.

Hope that helps.
