### ISSUE TITLE
Tag represents the LTS version

### ISSUE THREAD

**Issue by hrchu** [ceph/ceph-docker#806]
I would like to get the luminous/12.2.1 demo image since it's the least LTS version, which tag should I specify to get that?

**Comment by leseb** [comment]
We just started doing stable releases, so please use `tag-stable-3.0-luminous-ubuntu-16.04` or `tag-stable-3.0-luminous-centos-7`.
Thanks!

**Comment by hrchu** [comment]
Just for curious, what's the meaning of "3.0"?

**Comment by leseb** [comment]
It's alined with the ceph-ansible version we use to deploy a containerized cluster.

**Comment by hrchu** [comment]
Hmm I don't see  tag-stable-3.0-luminous-ubuntu-16.04 or tag-stable-3.0-luminous-centos-7 in docker hub. Should I wait for a while?

**Comment by leseb** [comment]
https://hub.docker.com/r/ceph/daemon/builds/bmicjy4vy9qlvfqxoeaf9y9/

**Comment by hrchu** [comment]
@leseb is ceph/demo unavailable?

**Comment by leseb** [comment]
demo merged in daemon since Luminous.
