### ISSUE TITLE
Refactor OSD setup

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#81]
Hey,

The way the OSDs are currently setup is not straightforward at all. It's really confusing how pieces interact with each other. Thus I'm proposing to rework a bit how we bootstrap the OSD.

In #78 I started integrating bootstrap-keys, so we don't need to have the ceph.admin key inside all the containers and more importantly on all the hosts running the containers.
So yes there is a prefetching operation that needs to collect the appropriate keys.
The operation will create the following entries:

```
/var/lib/ceph/
|-- bootstrap-mds
|   `-- ceph.keyring
|-- bootstrap-osd
|   `-- ceph.keyring
|-- bootstrap-rgw
|   `-- ceph.keyring
```

Later the idea is to use `ceph-disk`.
So basically this is how I set an OSD (manually):

```
$ sudo docker run -ti -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev/:/dev/ --net=host --privileged=true ceph/base /bin/bash
root@coreos:/# ceph-disk zap /dev/vdc ; ceph-disk prepare /dev/vdc ; ceph-disk activate /dev/vdc1                                                                                                                                   [33/38422]
Creating new GPT entries.
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
Creating new GPT entries.
The operation has completed successfully.
The operation has completed successfully.
The operation has completed successfully.
meta-data=/dev/vdc1              isize=2048   agcount=4, agsize=1304255 blks
         =                       sectsz=512   attr=2, projid32bit=0
data     =                       bsize=4096   blocks=5217019, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
The operation has completed successfully.
got monmap epoch 1
sh: 1: /sbin/hdparm: not found
2015-06-12 13:01:20.358696 7f843ec13900 -1 journal _check_disk_write_cache: pclose failed: (0) Success
2015-06-12 13:01:20.359526 7f843ec13900 -1 journal check: ondisk fsid 00000000-0000-0000-0000-000000000000 doesn't match expected 924fd2e5-c3ea-4d7f-b3c5-9bb81abefa07, invalid (someone else's?) journal
sh: 1: /sbin/hdparm: not found
2015-06-12 13:01:20.362257 7f843ec13900 -1 journal _check_disk_write_cache: pclose failed: (0) Success
sh: 1: /sbin/hdparm: not found
2015-06-12 13:01:20.533410 7f843ec13900 -1 journal _check_disk_write_cache: pclose failed: (0) Success
sh: 1: /sbin/hdparm: not found
2015-06-12 13:01:20.536231 7f843ec13900 -1 journal _check_disk_write_cache: pclose failed: (0) Success
2015-06-12 13:01:20.536667 7f843ec13900 -1 filestore(/var/lib/ceph/tmp/mnt.0_cGmZ) could not find 23c2fcde/osd_superblock/0//-1 in index: (2) No such file or directory
2015-06-12 13:01:20.747410 7f843ec13900 -1 created object store /var/lib/ceph/tmp/mnt.0_cGmZ journal /var/lib/ceph/tmp/mnt.0_cGmZ/journal for osd.7 fsid fe49246f-9655-4034-ae32-7ff81a416e90
2015-06-12 13:01:20.748599 7f843ec13900 -1 auth: error reading file: /var/lib/ceph/tmp/mnt.0_cGmZ/keyring: can't open /var/lib/ceph/tmp/mnt.0_cGmZ/keyring: (2) No such file or directory
2015-06-12 13:01:20.759898 7f843ec13900 -1 created new key in keyring /var/lib/ceph/tmp/mnt.0_cGmZ/keyring
added key for osd.7
root@coreos:/var/log/ceph# ceph-osd -i 7
starting osd.7 at :/0 osd_data /var/lib/ceph/osd/ceph-7 /var/lib/ceph/osd/ceph-7/journal
root@coreos:/var/log/ceph# ps x
  PID TTY      STAT   TIME COMMAND
    1 pts/1    Ss     0:00 /bin/sh /entrypoint.sh /bin/bash
    7 pts/1    S      0:00 /bin/bash
  226 ?        Ssl    0:00 ceph-osd -i 6
  599 pts/1    R+     0:00 ps x
```

This is pretty straightforward and easy to bootstrap.
I can easily prototype this.

@Ulexus what do you think?

**Comment by hookenz** [comment]
I might tie the bootstrap keys into the ceph-cli work.   The way i now have the osds bootstapping is fast. I am pretty sure i can hotplug them.

**Comment by Ulexus** [comment]
@leseb I think it sounds like a good idea.  The additional `--privileged` requirement makes me less sanguine, but it seems there is the choice of having the OSD fully bootstrapped (with the privileges that entails) or having to work something outside the container.  

I'm also not sold on the use of `ceph-disk`;  it's an enormous script with a lot of assumptions built in.  I was fairly permanently put off of `ceph-deploy` thanks to those assumptions and complexity.  On the other hand, it's maintained by the Ceph project, so it's probably less fragile than manually building the OSDs.

Originally, I preferred the approach of separation, but for more massive deployments than my own, a fully-bootstrapped approach seems more sensible.

You'll still need to be able to safely reference which block devices to use, and unless we open up ceph-disk, configuration-wise, this will be less flexible.  I would definitely prefer to maintain a path for handing over a filesystem to the OSD, rather than have it all done for you, but I think that could be best done with better detection, rather than explicit environment variables, as is done currently.

Overall, I like it.

**Comment by leseb** [comment]
The prototype can be found in #78 here: https://github.com/ceph/ceph-docker/pull/78/files#diff-b9c25bf1154f3e0eb1449dd01310fbc3R187

**Comment by leseb** [comment]
I'm really in favour of using `ceph-disk` can (as your said) its maintained by the Ceph core developer. It is intended to best user experience, along with best practices.
What I don't like with the OSD directory path is that it requires a pre-configuration (it can be automated on the host though) where with `ceph-disk` you just pass a block device and that's it.

**Comment by Ulexus** [comment]
I'd like to make sure its options (filesystem and journal types) are exposed, but if you're confident in it, I'm fine with using it.

I certainly agree regarding the preconfiguration, but I do think that should still be an allowed setup.  I don't think that's a mutually-exclusive feature; we just need to tighten up the detection mechanism.  The OSD store has everything necessary in it in a nicely-readable format.  We just need to use it.

**Comment by leseb** [comment]
I agree. Operators shouldn't be forced to use `--privileged` thus we need to propose different ways of setting up the OSD. At the moment I can think of two:

* keep the current format where we need to prepare the OSD disk, filesystem, mount, create and expose the OSD directory
* use `ceph-disk`
