### ISSUE TITLE
Bootstrap cluster not caterred for providing your own ceph.conf

### ISSUE THREAD

**Issue by hookenz** [ceph/ceph-docker#92]
As the pre-generated ceph.conf is very basic when bootstrapping a new cluster, it's often better to supply one.

However, the entrypoint.sh scripts on the mon and daemon skip the generation of admin & monitor keys if ceph.conf exists.  It'd be better to prompt for them to be created, or just create them if ceph.conf is there, but those files are missing.

So in my case I had to run the authtool directly to complete the missing steps.

**Comment by leseb** [comment]
Yes there is preparation step needed when you want to scale your infrastructure.
We assume that `ceph.conf`, `monmap` and various keys (admin and bootstraps) will be present on the destination system.
Later when we move to etcd or consul we won't need this as the entry point itself will know how to retrieve those files.

**Comment by hookenz** [comment]
I think use of etcd or consul should be optional.  I don't like the idea of using etcd to hold my keys while the implementation is so open.   Same with consul. In my case i provide the keys and config through cloud init and pass them through.

**Comment by Ulexus** [comment]
Certainly, this would not be to the exclusion of providing your own files.

On Wed, Jun 17, 2015, 16:01 hookenz <notifications@github.com> wrote:

> I think use of etcd or consul should be optional. I don't like the idea of
> using etcd to hold my keys while the implementation is so open. Same with
> consul. In my case i provide the keys and config through cloud init and
> pass them through.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph-docker/issues/92#issuecomment-112929329>.
>
-- 
Seán C McCord
CyCore Systems, Inc
888-240-0308

**Comment by hookenz** [comment]
Sean, just watched your presentation on CoreOS Fest.  Nicely done.  Glad I'm not to the only one trying to run this in production.  It seems everything I'm trying to run in production is the bleeding edge :)

**Comment by Ulexus** [comment]
Thanks!  Yeah, this is about where I like to stay.  Anything else is too boring.

Anyway, I do think the bootstrapping scripts should be a bit more granular, creating things which are needed so that you _can_ supply your own `ceph.conf`, for instance.

However, this leaves open the possibility that people will expect the `ceph.conf` to be _parsed_ by the bootstrapping script, too, and I don't really want to go that far.  For instance, I do _not_ want to check the `ceph.conf`, see that an OSD is supposed to run on this server (by hostname?  IP?), and then bootstrap it up.  Down that road lies madness.

**Comment by hookenz** [comment]
Agreed. Didn't think if that.   I never put osd configs in ceph.conf actually.  

I've been looking at ceph-disk activate which won't work with docker unless it's modified.  I will start a thread on it. I've got some ideas based around ceph-tools and mount-osds script.

**Comment by leseb** [comment]
@hookenz what does not work with ceph-disk? I've got it perfectly working with `ceph/daemon`, just as explained in #81. Oh ok I'll look at #98
